.github/workflows/release.yaml

Adds the `release-plz` release pipeline.
**Metadata**
closes #3

feat: `release-plz` release pipeline

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/README.md
crates/derive/src/lib.rs

Initializes the `kona-derive` library.

feat: Add `kona-derive` boilerplate crate

---

crates/derive/src/types/eips/deposit.rs
crates/derive/src/types/eips/eip2718.rs
crates/derive/src/types/eips/mod.rs
crates/derive/src/types/receipt.rs
crates/derive/src/types/transaction/envelope.rs

Adds the Optimism fields to the `Receipt` type.

feat: Add OP receipt fields

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/types/spans/mod.rs
crates/derive/src/types/spans/signature.rs
crates/derive/src/types/spans/transactions.rs

Introduces [Span Batch Transactions](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/span_batch_txs.go#L17).

feat(types): span batches transactions

---

crates/derive/src/stages/l1_retrieval.rs

Small doc comment fix to the l1 retrieval flag

fix(derive): L1Retrieval Comment Fix

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/stages/channel_bank.rs
crates/derive/src/stages/channel_reader.rs
crates/derive/src/stages/mod.rs

Implements the `ChannelReader`.
**Metadata**
Fixes #51

feat(derive): Channel Reader Implementation

---

crates/derive/src/types/batch/span_batch/transactions.rs
crates/derive/src/types/batch/span_batch/utils.rs

Adds the protected V check to the `add_txs` function in the `SpanBatchTransactions` type.
reference: https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/span_batch_txs.go#L425-L435

feat(derive): Add signature protection check in `SpanBatchTransactions`

---

crates/derive/src/stages/attributes_queue.rs
crates/derive/src/stages/mod.rs
crates/derive/src/stages/test_utils/attributes_queue.rs
crates/derive/src/stages/test_utils/batch_queue.rs
crates/derive/src/stages/test_utils/mod.rs
crates/derive/src/traits/data_sources.rs
crates/derive/src/traits/mod.rs
crates/derive/src/types/attributes.rs
crates/derive/src/types/errors.rs
crates/derive/src/types/mod.rs

Fixes up the `AttributesQueue` abstractions/traits and adds a bunch of testing.

fix(derive): Abstractions and Testing

---

README.md

Removes the blue underlines around badges due to malformatted spacing between link and image html tag.

fix(readme): Remove Blue Highlights

---

crates/derive/src/types/batch/span_batch/batch.rs

Rebases the span batch validation tests on top of #123

fix(derive): Rebase span batch validation tests

---

Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/mpt/Cargo.toml

Fixes the release plz job by using the same versions of `alloy-*` crates in `kona-mpt` as in `kona-derive`

fix(workspace): Release plz

---

Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/mpt/Cargo.toml
crates/primitives/Cargo.toml

I *think* this should fix release plz. Tried to add a check before PRs, but wasn't working. This removes a possible dependency clash based off of multiple declarations of `alloy-consensus`.

fix(ci): Release plz

---

book/src/fpp-dev/epilogue.md
book/src/fpp-dev/execution.md
book/src/fpp-dev/prologue.md
book/src/intro.md
book/src/links.md

Adds some documentation for each program stage in the [book](https://static.optimism.io/kona).

feat(book): Add minimal program stage documentation

---

crates/derive/src/online/blob_provider.rs
crates/derive/src/pipeline/builder.rs
crates/derive/src/pipeline/mod.rs

Implements a pipeline builder with a doc comment example using online provider implementations.
Also updates the online blob provider to remove the unused RPC client.

feat: Pipeline Builder

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/online/alloy_providers.rs
crates/derive/src/online/beacon_client.rs
crates/derive/src/online/mod.rs
crates/derive/src/traits/mod.rs
crates/derive/src/traits/reset.rs
justfile

Small fixes to the derivation pipeline.
Fixes the providers.
Removes unneeded trait impls.

fix: Derivation Pipeline

---

.github/codecov.yml
.github/workflows/rust_ci.yaml

feat(ci): Add codecov

---

.github/dependabot.yml
Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/mpt/Cargo.toml
crates/plasma/Cargo.toml
crates/preimage/Cargo.toml
crates/primitives/Cargo.toml

Introduces jonhoo's dependabot config, which notifies on outdated github
actions as well as outdated crate dependencies.

feat(ci): Dependabot config

---

crates/derive/src/pipeline/core.rs
crates/derive/src/pipeline/mod.rs

Cleans up tracing in the pipeline.

chore(derive): Cleanup Pipeline Tracing

---

.github/codecov.yml

Removes codecov from the binaries.

chore(ci): Remove codecov from binaries

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/stages/utils.rs

fix: another one

---

examples/trusted-sync/Cargo.toml

Fixes a small dependency feature flag that wasn't caught by ci checks.

fix(examples): Alloy Dependency Feature Flag

---

bin/client/justfile

Improves the justfile in the `client` program to fetch boot information remotely rather than having to statically declare it.

chore(client): Improve justfile

---

README.md
crates/derive/README.md

Cleans up labels to use the same label bg color. Adds a `kona-derive` crates.io link.

chore(docs): Label Cleanup

---

.github/workflows/docker.yaml
.gitignore
examples/trusted-sync/Dockerfile
examples/trusted-sync/run.sh
justfile

Dockerizes the `trusted-sync` example to run as a part of infrastructure.

feat(build): Dockerize trusted-sync

---

.github/workflows/trusted_sync_docker.yaml

fix(ci): Publish trusted sync docker

---

crates/derive/src/stages/channel_reader.rs
crates/derive/src/stages/frame_queue.rs
examples/trusted-sync/src/main.rs
examples/trusted-sync/src/metrics.rs

Fixes the `trusted-sync` example to follow tip.

fix(examples): Follow Tip

---

examples/trusted-sync/src/main.rs
examples/trusted-sync/src/metrics.rs

Adds a metric to track pipeline steps.

feat(examples): Pipeline Step Metrics

---

bin/client/src/l2/precompiles/kzg_point_eval.rs
bin/client/src/l2/precompiles/mod.rs

Adds an acclerated precompile for KZG point evaluation to the client program.

feat(client): KZG point evaluation accelerated precompile

---

bin/client/src/l1/driver.rs
crates/derive/src/online/alloy_providers.rs
crates/derive/src/online/mod.rs
crates/derive/src/pipeline/core.rs
crates/derive/src/pipeline/mod.rs
crates/derive/src/traits/mod.rs
crates/derive/src/traits/pipeline.rs
examples/trusted-sync/src/main.rs
examples/trusted-sync/src/metrics.rs

Increase granularity for pipeline steps.
Adds a few tracking metrics to increase dashboard visibility.

feat(examples): Increase Granularity

---

.github/workflows/trusted_sync_docker.yaml

quick fix to trusted-sync publish

fix(actions): ghcr prefix

---

examples/trusted-sync/src/main.rs

Resets the pipeline if a drift occurs. Also, extends the drift to `500` for a little more buffer. Can probably parameterize this down the road if it occurs frequently.

fix: drift reset

---

examples/trusted-sync/src/cli.rs
examples/trusted-sync/src/main.rs

Drift walkback fix using time updates.

fix: Drift Walkback

---

Cargo.lock
crates/primitives/Cargo.toml
examples/trusted-sync/Cargo.toml

Pins the version of the `superchain-registry` and `superchain-primitives` dependencies.

fix(deps): Pin superchain-registry Version

---

README.md

Fixes broken FPVM tests link in readme.

fix: Broken link in readme

---

bin/client/src/l2/precompiles/mod.rs

Ensures that the `p256` precompile is activated with Fjord.

chore(client): Ensure p256 precompile activation

---

book/src/fpp-dev/env.md

fix: link to section `prologue`
cc. https://static.optimism.io/kona/fpp-dev/env.html#full-example

fix: link to section

---

bin/host/src/server.rs

Removes the TODO comments in the host server; The catch-all error handling here fits our usecase.
closes #192

chore(host): Remove TODOs

---

.gitmodules
Cargo.lock
bin/kdn/Cargo.toml
bin/kdn/src/cli.rs

Updates with `op-test-vectors` rename.

fix(kdn): Update with Repository Rename

---

bin/client/Cargo.toml
bin/client/src/boot.rs

feat: serde Serialization/Deserialization to BootInfo struct

---

.gitmodules

Updates git submodules to use `https` instead of ssh.

fix(submodules): HTTPS

---

Cargo.lock
bin/client/Cargo.toml
bin/host/Cargo.toml
bin/kt/Cargo.toml
crates/derive/Cargo.toml
crates/executor/Cargo.toml
crates/primitives/Cargo.toml
examples/trusted-sync/Cargo.toml

Downgrades crate versions so `release-plz` works properly.

fix: Downgrade for Release Plz

---

Cargo.lock
crates/primitives/Cargo.toml
examples/trusted-sync/Cargo.toml
examples/trusted-sync/src/main.rs

Updates the `superchain` dependencies to use the [new bindings repo](https://github.com/anton-rs/superchain).

chore(deps): Update Superchain Deps

---

Cargo.toml

> [!NOTE]
>
> This PR is part of a larger stack to reorganize the workspace and its dependencies.
Reorganizes and cleans up the top-level workspace cargo manifest.

chore(workspace): Reorg Workspace Manifest

---

Cargo.toml
bin/client/Cargo.toml
bin/host/Cargo.toml
crates/common-proc/Cargo.toml
crates/common/Cargo.toml
crates/derive/Cargo.toml
crates/executor/Cargo.toml
crates/mpt/Cargo.toml
crates/preimage/Cargo.toml
crates/primitives/Cargo.toml
examples/trusted-sync/Cargo.toml

> [!NOTE]
>
> This PR is part of a larger stack to reorganize the workspace and its dependencies.
Hoists dependencies to the top-level cargo manifest for significantly easier dependency version management.

chore(workspace): Hoist Dependencies

---

Cargo.toml
bin/client/Cargo.toml
bin/host/Cargo.toml
crates/common-proc/Cargo.toml
crates/derive/Cargo.toml
crates/executor/Cargo.toml
crates/preimage/Cargo.toml
examples/trusted-sync/Cargo.toml

Re-exports crates from the workspace.

feat(workspace): Workspace Re-exports

---

Cargo.toml

Fixes the `default-features` directive in a few dependencies within the workspace `Cargo.toml`.

chore(workspace): Fix `default-features` in workspace root

---

.github/workflows/trusted_sync_docker.yaml
crates/primitives/Cargo.toml
crates/primitives/src/sidecar.rs

Enables revm features for kzg.

fix(examples): Revm Features

---

Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/executor/benches/execution.rs
crates/executor/src/lib.rs

chore: Bumps Dependency Versions

---

crates/derive/README.md
crates/derive/USAGE.md
crates/derive/src/pipeline/builder.rs

Touches up `kona-derive` docs.

feat(derive): Touchup Docs

---

crates/derive/src/stages/frame_queue.rs

Verifies the `FrameQueue` handles frames with interleaved channels.

feat(derive): Interleaved Channel Tests [HOLOCENE]

---

crates/derive/src/stages/batch_queue.rs
crates/derive/src/stages/batch_stream.rs
crates/derive/src/stages/channel_reader.rs
crates/derive/src/stages/mod.rs
crates/derive/src/stages/test_utils/batch_stream.rs
crates/derive/src/stages/test_utils/mod.rs

Introduces the `BatchStreamProvider`.
Makes progress on #559

feat(derive): BatchStreamProvider

---

justfile

Fixes action tests in CI - Platforms team refactored recently, new makefile recipe is `make devnet-allocs-tests`.

fix(ci): Action tests

---

crates/derive/src/pipeline/core.rs
crates/derive/src/stages/attributes_queue.rs
crates/derive/src/stages/batch_queue.rs
crates/derive/src/stages/batch_stream.rs
crates/derive/src/stages/channel_reader.rs
crates/derive/src/traits/attributes.rs
crates/derive/src/traits/mod.rs
crates/derive/src/traits/stages.rs

Adds the channel flushing functionality for Holocene.

feat(derive): Holocene flush signal

---

crates/derive/src/stages/frame_queue.rs

Tests a single frame in the `FrameQueue`.

chore(derive): Frame Queue Single Frame Test

---

bin/client/src/l1/driver.rs

Per Holocene spec, retries failed block execution with a deposit only block. If a block fails execution, and is replaced, the batch and channel it is contained in must be forwards invalidated as well.
If the deposit only block fails execution, throw a critical error.
closes #561

feat(client): Pass flush signal

---

Cargo.lock
crates/primitives/src/blob.rs
crates/primitives/src/blob_hash.rs
crates/primitives/src/lib.rs

Refactors indexed blob hash and adds test coverage.

chore: Add Test Coverage

---

crates/common/src/executor.rs
crates/common/src/io.rs
crates/common/src/linux.rs
crates/common/src/types.rs

Adds test coverage for `kona-common`.

chore(common): Test Coverage

---

crates/primitives/src/blob.rs

feat(primitives): Blob Test Coverage

---

crates/common/src/types.rs
crates/preimage/src/key.rs
crates/preimage/src/oracle.rs
crates/preimage/src/pipe.rs

Adds test coverage to `kona-preimage`.

chore(preimage): Test Coverage

---

Cargo.lock
Cargo.toml

Small PR to update dependencies.

chore: Dependency Updates

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/lib.rs
crates/derive/src/pipeline/core.rs
crates/derive/src/test_utils/mod.rs
crates/derive/src/traits/pipeline.rs

Adds test coverage for the pipeline core mod.

chore(derive): Pipeline Core Test Coverage

---

crates/providers-alloy/src/blob_provider.rs

Increases test coverage around the blob provider with fallback.

chore(providers-alloy): Blob Provider With Fallback Test Coverage

---

README.md

feat: Codecov Shield

---

.github/codecov.yml

Fixes codecov and bumps the threshold to 85%.

fix: Codecov

---

crates/mpt/src/db/mod.rs

Small PR to add test coverage over the `TrieDB`.

chore(mpt): Test Coverage over the TrieDB

---

crates/derive/src/sources/blobs.rs
crates/derive/src/sources/calldata.rs
crates/derive/src/sources/variant.rs

Adds test coverage over data sources.

chore(derive): Test Coverage over Data Sources

---

crates/derive/src/batch/mod.rs

Small PR to cover batch timestamp.

chore(derive): Batch Timestamp Tests

---

Cargo.lock
crates/derive/Cargo.toml
crates/derive/src/batch/span_batch/bits.rs
crates/derive/src/batch/span_batch/element.rs
crates/derive/src/batch/span_batch/transactions.rs
crates/derive/src/batch/span_batch/utils.rs

Tests and cleans derivation batch types.

chore(derive): Test and Clean Batch Types

---

crates/derive/src/stages/batch_queue.rs
crates/derive/src/stages/channel_bank.rs

More test coverage around `kona-derive` stages.

chore(derive): Adds more test coverage to Stages

---

crates/executor/src/builder.rs

Small coverage over the executor builder.

chore(executor): Cover Builder

---

README.md
book/src/CONTRIBUTING.md
book/src/glossary.md
build/README.md

Hello
I fixed several minor spelling issues.

docs fix spelling issues

---

crates/providers-alloy/src/beacon_client.rs

chore(providers-alloy): Remove Version Types

---

Cargo.lock
crates/providers/Cargo.toml
crates/providers/src/test_utils.rs

In an effort to eradicate anyhow, I am

chore(providers): Eradicate Anyhow

---

Cargo.lock
crates/mpt/Cargo.toml

Cleans up `kona-mpt` dependencies.

chore(mpt): Cleans up kona-mpt Dependencies

---

bin/host/src/fetcher/mod.rs

Removes `MAX_RETRIES` in `kona-host`'s prefetcher. The `op-program` just [absolutely sends it](https://github.com/ethereum-optimism/optimism/blob/cl%2Fcannon-sol-64bit/op-program/host/prefetcher/retry.go#L14-L14), and waits for the RPC
it depends on to come back online.

feat(host): Remove `MAX_RETRIES`

---

crates/derive/src/sources/mod.rs

Small PR to update source module docs.

chore(derive): Source Module Docs

---

.monorepo
Cargo.lock
bin/client/Cargo.toml
bin/client/src/errors.rs
bin/client/src/kona.rs
bin/client/src/l1/chain_provider.rs
bin/client/src/l1/driver.rs
bin/client/src/l2/chain_provider.rs
bin/client/src/lib.rs
crates/derive-alloy/Cargo.toml
crates/derive-alloy/src/alloy_providers.rs
crates/derive-alloy/src/errors.rs
crates/derive-alloy/src/lib.rs
crates/derive/src/attributes/stateful.rs
crates/derive/src/errors/pipeline.rs
crates/derive/src/pipeline/core.rs
crates/derive/src/sources/calldata.rs
crates/derive/src/stages/l1_traversal.rs
crates/derive/src/test_utils/chain_providers.rs
crates/derive/src/test_utils/sys_config_fetcher.rs
crates/derive/src/traits/mod.rs
crates/derive/src/traits/providers.rs

Adds support for trace extension within `kona-client`.

fix(client): Trace extension support

---

Cargo.lock
bin/client/Cargo.toml
bin/client/src/boot.rs
bin/client/src/errors.rs
bin/client/src/fault/handler/bn128_pair.rs
bin/client/src/fault/handler/ecrecover.rs
bin/client/src/fault/handler/kzg_point_eval.rs
bin/client/src/hint.rs
bin/client/src/kona.rs
bin/client/src/l1/blob_provider.rs
bin/client/src/l1/chain_provider.rs
bin/client/src/l1/driver.rs
crates/common-proc/src/lib.rs
crates/derive/src/traits/data_sources.rs

Removes `anyhow` from the `kona-client` crate.

feat(client): Remove `anyhow`

---

.github/codecov.yml

Small PR to clean up the codecov config.

chore: Clean up Codecov

---

crates/derive/src/errors/pipeline.rs
crates/derive/src/errors/sources.rs

Test coverage around kona-derive errors.

chore(derive): Error Test Coverage

---

.github/codecov.yml
crates/derive-alloy/src/errors.rs

Fixes test coverage for `kona-derive-alloy`.

chore(derive-alloy): Test Coverage

---

Cargo.lock
crates/derive/src/lib.rs

chore(derive): Re-export types

---

Cargo.lock
Cargo.toml
bin/host/src/fetcher/mod.rs
bin/host/src/providers/blob.rs
crates/derive/src/attributes/stateful.rs
crates/derive/src/sources/calldata.rs
crates/derive/src/stages/batch/batch_provider.rs
crates/mpt/src/test_util.rs

Updates `op-alloy` to `0.6.6`.

chore: v0.6.6 op-alloy

---

Cargo.lock
Cargo.toml
crates/driver/src/pipeline.rs
crates/proof-sdk/proof/src/l1/pipeline.rs

Patches snuck into trunk. This fixes the imports.

fix: imports

---

Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/driver/Cargo.toml
crates/executor/Cargo.toml
crates/mpt/Cargo.toml
crates/proof-sdk/common-proc/Cargo.toml
crates/proof-sdk/common/Cargo.toml
crates/proof-sdk/preimage/Cargo.toml
crates/proof-sdk/proof/Cargo.toml

The first minor release of kona!

chore: Minor Release

---

crates/driver/src/core.rs

Make driver internals publicly visible for now, until we have a really solid driver api.

chore(driver): Visibility

---

book/src/sdk/fpvm-backend.md

Makes updates to the proof SDK section of the book with the separation of the platform-specific FPVM code from the base proof SDK downstack.

feat(book): Update book for FPVM crate changes

---

bin/client/src/lib.rs
crates/driver/src/core.rs

Advance driver with optional target.

chore(driver): Advance without target

---

bin/client/src/lib.rs
crates/driver/src/core.rs
crates/driver/src/executor.rs
crates/driver/src/lib.rs
crates/executor/src/errors.rs
crates/proof-sdk/proof/src/executor.rs

Proofs is a specific use case for kona's driver.
This PR cleans up the executor interface that the kona driver uses such that the proofs use case of re-creating the stateless block executor is abstracted away.

feat(driver): Executor Interface

---

Cargo.lock
Cargo.toml
bin/client/Cargo.toml
bin/host/Cargo.toml
crates/executor/Cargo.toml
crates/mpt/Cargo.toml
crates/proof-sdk/proof/Cargo.toml

Update deps and removes workspace-level features which should never be used.

chore(deps): Update Deps

---

crates/driver/src/core.rs
crates/driver/src/executor.rs
crates/proof-sdk/proof/src/executor.rs

Make the payload execution method async.

fix(driver): Async Payload Execution

---

Cargo.lock
Cargo.toml
crates/derive/Cargo.toml
crates/derive/src/stages/channel/channel_bank.rs
crates/proof-sdk/proof/Cargo.toml
crates/proof-sdk/proof/src/boot.rs

Replaces `alloy-rs/op-alloy-registry` with `op-rs/maili-registry`. Ref https://github.com/alloy-rs/op-alloy/pull/366.

chore(deps): Replace dep `alloy-rs/op-alloy-registry`->`op-rs/maili-registry`

---

Cargo.lock
Cargo.toml
README.md

chore: Bump Maili

---

README.md

edited the link in the documentation

docs: edited the link in the documentation

---

.github/workflows/coverage.yaml

Fixes codecov in CI, [updating to codecov-action@v5](https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes)

fix(ci): codecov

---

Cargo.lock
Cargo.toml
crates/executor/Cargo.toml
crates/executor/src/executor/env.rs
crates/executor/src/executor/mod.rs

Updates `maili` deps to `0.1.10`.

chore: Update Maili Deps

---

Cargo.lock
Cargo.toml
crates/executor/src/executor/env.rs

Bumps the `op-alloy` dependency version.

chore: Bump op-alloy dep

---

Cargo.lock
Cargo.toml

Updates `maili` to include the system config update.

chore: Maili Dependency Update

---

Cargo.lock
Cargo.toml

Small PR to use the updated maili and op-alloy deps.

chore: Use Updated Maili and op-alloy Deps

---

crates/derive/src/attributes/stateful.rs

feat: Isthmus upgrade txs

---

Cargo.lock
Cargo.toml

chore: Bump Dependencies

---

crates/interop/src/graph.rs

Chatted with the interop team, and the "horizon timestamp" is more of a virtual concept used within the node for lagging cross-safe updates. In the proof, it's not consequential, and we just need to check against the timestamp invariant.

chore(interop): Remove horizon timestamp

---

book/src/archives/intro.md
book/src/archives/monorepo.md

Moves the monorepo doc to the archives.

chore(book): Move the Monorepo Doc to Archives

---

.github/codecov.yml
Cargo.lock
Cargo.toml
crates/external/rpc/maili/Cargo.toml
crates/protocol/genesis/maili/Cargo.toml
crates/protocol/interop/Cargo.toml
crates/protocol/interop/maili/Cargo.toml
crates/protocol/interop/maili/README.md
crates/protocol/interop/maili/src/lib.rs
crates/protocol/interop/src/derived.rs
crates/protocol/interop/src/lib.rs
crates/protocol/interop/src/message.rs
crates/protocol/interop/src/root.rs
crates/protocol/interop/src/supervisor.rs
crates/protocol/protocol/maili/Cargo.toml
crates/protocol/protocol/maili/README.md
crates/protocol/protocol/maili/src/lib.rs
crates/protocol/registry/maili/src/lib.rs
crates/utilities/serde/maili/Cargo.toml
scripts/check_no_std.sh

Fixes up `maili` shadow crates.

fix: Maili Shadows

---

crates/protocol/genesis/src/chain/addresses.rs
crates/protocol/genesis/src/chain/altda.rs
crates/protocol/genesis/src/chain/config.rs
crates/protocol/genesis/src/chain/hardfork.rs
crates/protocol/genesis/src/chain/roles.rs
crates/protocol/genesis/src/genesis.rs
crates/protocol/genesis/src/rollup.rs
crates/protocol/genesis/src/superchain/chain.rs
crates/protocol/genesis/src/superchain/chains.rs
crates/protocol/genesis/src/superchain/config.rs
crates/protocol/genesis/src/superchain/info.rs
crates/protocol/genesis/src/system/config.rs
scripts/check_no_std.sh

Denies unknown fields on `kona-genesis` types.
Closes #1047

feat(genesis): Deny Unknown Fields

---

.github/dependabot.yml

Small PR to update dependabot labeling.

chore(ci): Dependabot Label Update

---

crates/protocol/genesis/src/system/config.rs
deny.toml

Fixes the `SystemConfig` tests to properly test deserialization.

fix(genesis): System Config Tests

---

.github/workflows/deny.yaml
.github/workflows/no_std.yml
Cargo.lock
crates/protocol/genesis/Cargo.toml
crates/protocol/genesis/src/chain/addresses.rs
crates/protocol/genesis/src/chain/altda.rs
crates/protocol/genesis/src/chain/config.rs
crates/protocol/genesis/src/chain/hardfork.rs
crates/protocol/genesis/src/chain/roles.rs
crates/protocol/genesis/src/genesis.rs
crates/protocol/genesis/src/rollup.rs
crates/protocol/genesis/src/superchain/config.rs

Ports over https://github.com/op-rs/maili/pull/245 from `maili` to `kona` opened by @yohkaz.
Also adds some more testing ontop and adds @yohkaz as a co-author :D

chore(genesis): Serde Test Types

---

crates/protocol/registry/etc/configs.json

Automated PR to update git submodules.

[BOT] Update Submodules

---

book/src/examples/batch-to-frames.md
book/src/examples/frames-to-batch.md
book/src/examples/load-a-rollup-config.md
book/src/examples/new-l1-block-info-tx-hardfork.md
book/src/protocol/genesis/intro.md
book/src/protocol/genesis/rollup-config.md
book/src/protocol/genesis/system-config.md
book/src/protocol/intro.md
book/src/protocol/protocol/batches.md
book/src/protocol/protocol/block-info.md
book/src/protocol/protocol/channels.md
book/src/protocol/protocol/frames.md
book/src/protocol/protocol/intro.md

Updates Kona's book to rename from `maili` to `kona`.

chore(book): Maili Rename

---

.github/workflows/deny.yaml

fix(ci): Cargo Deny Checks

---

crates/node/engine/src/client.rs
crates/node/engine/src/controller.rs

Fixes up the `EngineClient` to use the proper engine api methods

fix(engine): Engine Client

---

Cargo.lock
Cargo.toml

Small PR to update `op-alloy` dependencies.

chore(workspace): Updates op-alloy Dependencies

---

Cargo.lock
book/src/rfc/umbrellas.md

chore(book): Teeny Update

---

README.md

Makes a small change to the `README.md` file, moving a bit of the clutter towards the top further down. Also removes the mention of the `client` program being a fault proof program, to better advertise that it's prover-agnostic.

chore(docs): Update `README.md`

---

crates/node/engine/src/actor.rs
crates/node/engine/src/lib.rs
crates/node/engine/src/macros.rs
crates/node/engine/src/tasks/forkchoice/errors.rs
crates/node/engine/src/tasks/forkchoice/messages.rs
crates/node/engine/src/tasks/forkchoice/mod.rs
crates/node/engine/src/tasks/forkchoice/task.rs
crates/node/engine/src/tasks/mod.rs

Cleans up the FCU task further in the `kona-engine` crate.

feat(engine): FCU Task Updates

---

Cargo.lock
Cargo.toml

chore: Bump op-alloy Deps

---

Cargo.lock
Cargo.toml
crates/node/engine/src/client.rs
crates/protocol/protocol/Cargo.toml
crates/protocol/protocol/src/block.rs

Refactors conversion from an RPC block into an `L2BlockInfo`.

chore(protocol): RPC Block -> L2BlockInfo

---

deny.toml

Pulls cargo deny changes out of #1208

chore: Fix Deny Config

---

crates/node/service/src/actors/derivation.rs
crates/node/service/src/actors/l1_watcher_rpc.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/core.rs
crates/node/service/src/sync_start.rs

Small stylistic PR to use tracing macros without needing to import everywhere.

chore(node): Tracing Macros

---

bin/node/src/cli/mod.rs
bin/node/src/cli/node.rs
bin/node/src/cli/p2p.rs

Sets up the initial set of p2p cli args.
Follow up prs will add other args and hook them up to the networking service.

feat(node): P2P CLI Args

---

crates/node/rpc/src/interop/api.rs
crates/node/rpc/src/interop/error.rs
crates/node/rpc/src/interop/mod.rs
crates/node/rpc/src/jsonrpsee.rs
crates/node/rpc/src/lib.rs
crates/node/rpc/src/reqwest.rs
crates/protocol/interop/src/access_list.rs
crates/protocol/interop/src/errors.rs
crates/protocol/interop/src/lib.rs
crates/protocol/interop/src/message.rs

Closes https://github.com/op-rs/kona/issues/1237

Add InteropTxValidator for supervisor validation

---

Cargo.lock
bin/node/src/commands/node.rs
bin/node/src/flags/p2p.rs
crates/node/p2p/Cargo.toml
crates/node/p2p/src/discovery/bootnodes.rs
crates/node/p2p/src/lib.rs
crates/node/p2p/src/utils/mod.rs
crates/node/p2p/src/utils/secret_key.rs

Fixes up the P2P Secret Key parsing.

chore(node): P2P Secret Key

---

.github/workflows/rust_ci.yaml
Cargo.lock
Justfile
crates/proof/proof/src/eip2935.rs
crates/utilities/cli/Cargo.toml

Fixes the `cargo-udeps` check. I've also added it as required to CI so we don't get a failure in `main` again.

chore(workspace): Fix udeps check

---

crates/protocol/genesis/src/system/config.rs

Localizes import to avoid lint warnings.

chore(genesis): Localize Import for Lints

---

.github/workflows/rust_ci.yaml
Justfile

Small PR to fixup the benchmark ci job.

chore: Fixup Benchmark CI Job

---

Cargo.toml

Small PR to bump dependencies before release.

chore: Bump Deps before Release

---

CHANGELOG.md
Cargo.lock
Cargo.toml
README.md
crates/node/rpc/Cargo.toml
crates/proof/executor/Cargo.toml
crates/proof/mpt/Cargo.toml
crates/proof/preimage/Cargo.toml
crates/proof/proof-interop/Cargo.toml
crates/proof/proof/Cargo.toml
crates/proof/std-fpvm-proc/Cargo.toml
crates/proof/std-fpvm/Cargo.toml
crates/protocol/derive/Cargo.toml
crates/protocol/driver/Cargo.toml
crates/protocol/genesis/Cargo.toml
crates/protocol/hardforks/Cargo.toml
crates/protocol/interop/Cargo.toml
crates/protocol/protocol/Cargo.toml
crates/protocol/registry/Cargo.toml
crates/providers/providers-alloy/Cargo.toml
crates/utilities/cli/Cargo.toml
crates/utilities/serde/Cargo.toml

Bumps published crates by a minor version.

chore: Minor Crate Releases

---

crates/protocol/protocol/src/batch/single.rs
crates/protocol/protocol/src/batch/span.rs
crates/protocol/protocol/src/lib.rs
crates/protocol/protocol/src/utils.rs

Cleans up utilities used in the `kona-protocol` crate.

chore(protocol): Cleanup Utilities

---

Cargo.toml
crates/node/engine/src/task_queue/tasks/build/task.rs

Small cleanup to the cargo manifest.

chore: Small Manifest Cleanup

---

Cargo.lock
Cargo.toml
bin/node/src/commands/node.rs
bin/node/src/flags/mod.rs
bin/node/src/flags/rpc.rs

RPC CLI arguments.
Closes #1312.

feat(node): RPC CLI Args

---

crates/node/rpc/src/config.rs
crates/node/rpc/src/lib.rs

Small PR that implements the RPC Configuration.
Closes #1309.

feat(node): RPC Config

---

Cargo.lock
crates/node/service/Cargo.toml
crates/node/service/src/actors/mod.rs
crates/node/service/src/actors/rpc.rs
crates/node/service/src/lib.rs

Implements an actor in the `kona-node-service` that handles the RPC server.
Closes #1317

feat(node): Rpc Actor

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/commands/node.rs
bin/node/src/flags/rpc.rs
crates/node/service/Cargo.toml
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/mod.rs

Wires in the `RpcConfig` to the `RollupNode`.
Closes #1316.

feat(node): Wire in the RpcConfig

---

bin/node/src/commands/node.rs
bin/node/src/flags/globals.rs
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/mod.rs

Fixes the rollup node to use the correct unsafe block signer.

fix(node/service): Unsafe Block Signer

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/cli.rs
bin/node/src/commands/mod.rs
bin/node/src/commands/net.rs
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/discv5/handler.rs
crates/node/p2p/src/net/driver.rs
crates/node/p2p/src/net/ext.rs
crates/node/p2p/src/rpc/mod.rs
crates/node/rpc/src/net.rs

Wires in P2P RPC to the node with a new `net` subcommand.

feat(node): P2P RPC Wiring

---

Cargo.lock
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/discv5/handler.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/driver.rs
crates/node/p2p/src/rpc/server.rs
crates/node/rpc/src/net.rs

Handles rpc requests sent to the network stack.

chore(node/p2p): Network RPC Request Handling

---

bin/node/src/commands/node.rs
bin/node/src/flags/mod.rs
bin/node/src/flags/rpc.rs

Small PR that renames `RpcArgs`.

chore(bin): Rename RpcArgs

---

bin/node/src/flags/globals.rs

Use the correct unsafe block signer.

fix(bin): Correct Unsafe Block Signer

---

bin/node/src/commands/net.rs
bin/node/src/commands/node.rs
bin/node/src/flags/p2p.rs

Deduplicates the constructor for the P2P config.

chore(bin/node): P2P Config Constructor

---

crates/node/service/src/service/core.rs
crates/node/service/src/service/standard/builder.rs

Small PR to allow the node's mode to be configured dynamically.
Closes #1324

chore(node/service): Dynamic Node Mode

---

crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/gossip/handler.rs
crates/node/p2p/src/net/driver.rs

chore(node/p2p): Small Log Cleanup

---

bin/node/src/commands/net.rs
bin/node/src/commands/node.rs
bin/node/src/flags/globals.rs
crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/gossip/error.rs
crates/node/p2p/src/gossip/handler.rs
crates/node/p2p/src/gossip/mod.rs
crates/node/p2p/src/lib.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/driver.rs

Publishes unsafe payloads.
Closes #1356.

feat(node/p2p): Unsafe Payload Publishing

---

Cargo.lock
crates/node/service/Cargo.toml
crates/node/service/src/actors/l1_watcher_rpc.rs
crates/node/service/src/service/standard/node.rs
crates/node/service/src/service/validator.rs
crates/protocol/genesis/src/lib.rs
crates/protocol/genesis/src/system/errors.rs
crates/protocol/genesis/src/system/log.rs
crates/protocol/genesis/src/system/mod.rs
crates/protocol/genesis/src/system/update.rs
crates/protocol/genesis/src/updates/mod.rs
crates/protocol/genesis/src/updates/signer.rs

Properly wires up unsafe block signer updates using the `L1WatcherRpc` and the `SystemConfigUpdate` log type.
Closes #1326.

feat(node/service): Unsafe Block Signer Updates

---

crates/node/service/src/actors/engine.rs
crates/node/service/src/actors/mod.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/node.rs

Wires in the engine arguments.

feat(node/service): Wire in Engine Arguments

---

Cargo.lock
crates/node/service/src/actors/engine.rs
crates/node/service/src/actors/mod.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/node.rs

Minimal init for the `EngineActor`.
Progress on #1110

feat(node/service): Init the Engine Actor

---

Cargo.lock
crates/node/service/src/actors/engine.rs
crates/node/service/src/actors/mod.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/error.rs
crates/node/service/src/service/standard/node.rs
crates/node/service/src/service/validator.rs

Wires in the `EngineActor`. Not refactored nicely yet. Avoiding premature abstractions for something that works.
Makes progress on #1110.

feat(node/service): Wire in the Engine Actor

---

Cargo.lock
Cargo.toml
bin/node/Cargo.toml
bin/node/src/cli.rs
bin/node/src/commands/mod.rs
bin/node/src/commands/registry.rs
crates/protocol/registry/Cargo.toml
crates/protocol/registry/src/chain_list.rs

A `registry` subcommand for the `kona-node` that prints out a list of chains in the `superchain-registry`.

feat(bin/node): Registry Subcommand

---

Cargo.lock
crates/node/engine/Cargo.toml
crates/node/engine/src/client.rs
crates/node/engine/src/lib.rs
crates/node/engine/src/state/builder.rs
crates/node/engine/src/state/mod.rs

Part of #916 
Open for feedback, especially around naming.

chore(node/engine): Use thiserror instead of anyhow

---

crates/node/service/src/actors/engine.rs
crates/node/service/src/actors/mod.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/standard/error.rs
crates/node/service/src/service/validator.rs

Small PR to use the engine state builder error for better error propagation.

chore(node/service): Engine State Builder Error

---

crates/node/service/src/actors/engine.rs

Tiny PR to touchup the `EngineActor`.

chore(node/service): Touchup EngineActor

---

crates/node/engine/src/attributes.rs

This PR checks the eip1559 inside the consolidation step. I tried to stick as much as possible to the behavior of the op-node and reproduce their edge cases (in particular, *only substitute default params inside the attributes and not the block*).
I have added extensive test coverage to try and reproduce all the different edge-case configurations.
Merging this PR will close #1399

feat(node/engine): check eip1559 parameters inside consolidation

---

bin/node/src/flags/p2p.rs
crates/node/p2p/src/discv5/builder.rs
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/config.rs

Allow the discovery interval to be configurable.

feat: Discovery Interval Configurability

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/flags/p2p.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/config.rs

chore(bin/node): Discovery Config Wiring

---

crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/node.rs
crates/node/service/src/service/validator.rs

Wires in the p2p Rpc Module. Pretty ugly wiring right now but at least it's working.

chore(node/service): P2P Rpc Module Wiring

---

.github/workflows/docker.yaml
docker/apps/README.md
docker/docker-bake.hcl

Use a generic binary target in the docker bake.
Closes #1466

feat(ci): Generic Binary

---

bin/client/src/single.rs
crates/proof/executor/src/builder/assemble.rs
crates/proof/executor/src/builder/core.rs
crates/proof/proof/src/l1/blob_provider.rs
crates/protocol/derive/src/stages/attributes_queue.rs
crates/protocol/driver/src/pipeline.rs

Makes some tweaks to the common traces in the proof program. Favors native k/v trace attributes and moves some `snake_case` targets to `kebab-case`.

chore(workspace): Improve proof tracing

---

crates/utilities/cli/src/lib.rs
crates/utilities/cli/src/tracing.rs

feat: function to init tracing in testing

---

bin/node/src/commands/node.rs
bin/node/src/flags/mod.rs
bin/node/src/flags/sequencer.rs

feat: add sequencer CLI params

---

Cargo.lock
Cargo.toml
crates/proof/mpt/src/test_util.rs

new round of releases, getting towards stable 1.0 on alloy

chore: bump alloy 0.15

---

bin/node/src/flags/p2p.rs
crates/node/p2p/src/gossip/builder.rs
crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/config.rs
crates/node/p2p/src/net/driver.rs
crates/node/p2p/tests/common/mod.rs

Redial peers with a configurable CLI argument.
Closes #1468

feat(node): Redial Peers

---

bin/node/Cargo.toml
bin/node/src/commands/discover.rs
bin/node/src/commands/info.rs
bin/node/src/commands/mod.rs
bin/node/src/commands/node.rs
bin/node/src/flags/globals.rs
bin/node/src/flags/metrics.rs
bin/node/src/flags/p2p.rs
bin/node/src/flags/rpc.rs
bin/node/src/main.rs

The `kona-node` binary was missing lints which it now deserves.

fix(bin/node): Adds Lints

---

crates/node/p2p/Cargo.toml
crates/node/p2p/src/discv5/builder.rs
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/discv5/handler.rs
crates/node/p2p/src/gossip/behaviour.rs
crates/node/p2p/src/gossip/block_validity.rs
crates/node/p2p/src/gossip/builder.rs
crates/node/p2p/src/gossip/config.rs
crates/node/p2p/src/gossip/event.rs
crates/node/p2p/src/gossip/handler.rs
crates/node/p2p/src/gossip/mod.rs
crates/node/p2p/src/lib.rs
crates/node/p2p/src/net/broadcast.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/peers/any.rs
crates/node/p2p/src/peers/enr.rs
crates/node/p2p/src/peers/mod.rs
crates/node/p2p/src/peers/score.rs
crates/node/p2p/src/peers/store.rs
crates/node/p2p/src/peers/utils.rs
crates/node/p2p/tests/common/mod.rs

Adds lints and fixes up the `kona-p2p` crate

fix(node/p2p): Add Lints

---

Cargo.lock
Cargo.toml
crates/node/p2p/Cargo.toml
crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/lib.rs
crates/node/p2p/src/macros.rs
crates/node/p2p/src/metrics/mod.rs

Introduces a peer count metric.
Closes #1528

chore(node/p2p): Peer Count Metric

---

crates/node/p2p/src/rpc/request.rs
crates/node/p2p/src/rpc/server.rs
crates/node/rpc/src/jsonrpsee.rs
crates/node/rpc/src/lib.rs
crates/node/rpc/src/net.rs

Small PR that adds a couple of p2p rpc endpoints to the node to help debugging the p2p stack.

feat(node/p2p): add simple p2p rpc endpoints

---

bin/node/src/commands/discover.rs

Small fix to the `discover` subcommand since the discovery config is unset.

fix(bin/node): Discovery Config Unset

---

crates/node/p2p/src/discv5/builder.rs
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/peers/enr.rs
crates/node/p2p/src/peers/store.rs

Small PR to use `EnrValidation`.

fix(node/p2p): Use EnrValidation

---

bin/node/src/commands/discover.rs
bin/node/src/flags/p2p.rs
crates/node/p2p/src/discv5/builder.rs
crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/gossip/builder.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/config.rs

Extends P2P configurability options in the cli.

feat(bin/node): Extend P2P Configurability

---

crates/node/p2p/src/rpc/request.rs

Small PR that fixes the address list returned by the `opp2p_self` endpoint to match the [`op-node`'s behavior](https://github.com/ethereum-optimism/optimism/blob/174e55f0a1e73b49b80a561fd3fedd4fea5770c6/op-node/p2p/rpc_server.go#L127-L133). The list of addresses returned there matches the list of addresses listened to by the gossip layer

fix(node/p2p): Fix the address list returned by `opp2p_self`

---

crates/protocol/protocol/src/batch/single.rs

Adds a new rule to `SingleBatch` validity for the interop hardfork, where in the transition block, the batch _must_ be empty.
spec ref: https://github.com/ethereum-optimism/specs/pull/692

feat(protocol): Interop transition batch validity rule

---

crates/protocol/hardforks/src/ecotone.rs
crates/protocol/hardforks/src/fjord.rs
crates/protocol/hardforks/src/isthmus.rs

feat: add code hash tests

---

crates/proof/mpt/src/traits.rs
crates/protocol/derive/src/traits/providers.rs
crates/protocol/driver/src/executor.rs
crates/protocol/interop/src/traits.rs
crates/protocol/protocol/src/batch/traits.rs
crates/providers/providers-alloy/src/beacon_client.rs

Display is ToString
Error is Display + Debug

chore: rm redundant bounds

---

crates/protocol/interop/src/constants.rs

https://github.com/ethereum-optimism/specs/pull/696

chore(interop): Reduce message expiry window

---

crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/gossip/behaviour.rs
crates/node/p2p/src/gossip/builder.rs

Does some small log cleanup to make the node startup more digestible.

chore(bin/node): Cleans up Logs Some More

---

crates/node/p2p/src/gossip/builder.rs
crates/utilities/cli/src/prometheus.rs

chore(node): Log Cleanup

---

Cargo.lock
crates/node/engine/src/state/builder.rs
crates/node/engine/src/state/error.rs
crates/node/engine/src/state/mod.rs

Small PR to touch up engine docs and builder error msgs

chore(node/engine): Small Engine Touchups

---

bin/node/src/commands/node.rs

Small PR to add some unit tests to the `kona-node` binary.
Helps prevent us borking the cli in the future when adding new cli arguments.

chore(bin/node): CLI Argument Unit Tests

---

bin/host/src/interop/handler.rs

Adds a tracing span for the optimistic block re-execution subroutine within the interop hint handler to make the scope of the logs a bit more clear.
| Before | After |
| ------ | ----- |
| <img width="2476" alt="Screenshot 2025-05-06 at 10 23 07 AM" src="https://github.com/user-attachments/assets/c5d1354b-7c99-4d14-b2d1-ed5cd75be970" /> | <img width="2558" alt="Screenshot 2025-05-06 at 10 22 06 AM" src="https://github.com/user-attachments/assets/03117477-5f97-463c-99c1-3dec80717c5f" /> |

feat(host): Trace span for `L2BlockData` re-execution

---

crates/proof/proof/src/caching_oracle.rs

Adjusts the `CachingOracle` to drop its spinlock before an `await` to prevent blocking concurrent tasks from reading from the oracle while the `OracleReader` is fetching and streaming the missing data. We don't want to use something like `tokio`'s mutex here (which can yield) due to the crate's `no_std` compatibility requirements, but we also want to allow other tasks to access / update the `CachingOracle`'s contents if the `OracleReader` future yields.
This type already assumes that k/v mappings returned by the underlying `OracleReader` are one-to-one, so any task that updates a key in the cache while a `get` / `get_exact` has yielded is safe as long as this assumption is held.
closes #1615

chore(proof): Drop lock before `await`

---

RELEASES.md

Adds reminder to verify permissions on crates affected in release

Add permissions sanity check TIP to RELEASES.md

---

bin/node/src/commands/node.rs
crates/node/service/src/actors/engine.rs
crates/node/service/src/actors/runtime.rs

Fixes the `kona-node` binary to wire up runtime config loading.

fix(bin/node): Runtime Config Wiring

---

crates/node/engine/src/task_queue/core.rs
crates/node/service/src/actors/derivation.rs
crates/node/service/src/actors/engine.rs
crates/node/service/src/service/validator.rs

Only produce payload attributes when the l2 safe head is updated.
Closes #1240.

feat(node/service): Update L2 Safe Head

---

Cargo.lock
crates/node/engine/src/task_queue/tasks/build/error.rs
crates/node/engine/src/task_queue/tasks/build/task.rs
crates/protocol/protocol/src/attributes.rs

Re-imports deposits-only payload on invalid payload post-holocene.
Closes #1239

feat(node/service): Re-import Deposits Only Payload

---

crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/node/service/src/actors/derivation.rs
crates/node/service/src/actors/engine.rs

Updates the safe head post-consolidation.

feat(node/engine): Set Safe Head Consolidation

---

crates/node/engine/src/lib.rs
crates/node/engine/src/task_queue/tasks/insert/task.rs
crates/node/engine/src/task_queue/tasks/mod.rs
crates/node/engine/src/task_queue/tasks/unknowns.rs
crates/node/service/src/actors/derivation.rs

Updates the insert unsafe payload task to initialize unknowns if needed.

fix(node/engine): Initialize Unknowns

---

crates/node/service/src/service/standard/error.rs
crates/node/service/src/service/validator.rs

fix(node/rpc): removed the panic and added error when building RPC actor

---

Cargo.lock
Cargo.toml
bin/client/src/fpvm_evm/factory.rs
bin/client/src/fpvm_evm/precompiles/provider.rs
crates/node/engine/src/client.rs
crates/node/service/Cargo.toml
crates/node/service/src/actors/engine.rs

Small pr to update `revm` + it's associated evm dependencies.

chore(workspace): Update REVM Deps

---

crates/node/engine/Cargo.toml
crates/node/engine/src/lib.rs
crates/node/engine/src/metrics/mod.rs
crates/node/engine/src/state/core.rs

chore(engine): Chain label metrics cleanup

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/cli.rs
bin/node/src/commands/bootstore.rs
bin/node/src/commands/discover.rs
bin/node/src/commands/info.rs
bin/node/src/commands/net.rs
bin/node/src/commands/node.rs
bin/node/src/commands/registry.rs
bin/node/src/flags/rpc.rs

Small PR to add tests to cover `kona-node` subcommands

chore(bin/node): Subcommand Tests

---

Cargo.lock
bin/node/Cargo.toml
bin/node/src/commands/net.rs
bin/node/src/flags/rpc.rs
crates/node/rpc/src/config.rs
crates/node/rpc/src/launcher.rs
crates/node/service/src/service/standard/node.rs
crates/node/service/src/service/validator.rs

Small cleanup to the `kona-node-service`.

chore(node/service): Small Cleanup

---

LICENSE.md

Extends the license copyright into `2025` under "kona contributors"

chore: Update LICENSE.md

---

crates/node/engine/src/metrics/mod.rs
crates/node/engine/src/task_queue/tasks/build/task.rs
crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/node/engine/src/task_queue/tasks/forkchoice/task.rs
crates/node/engine/src/task_queue/tasks/insert/task.rs
crates/node/macros/src/metrics.rs

Adds a counter that tracks the number of engine tasks processed.

feat(engine): Task count metrics

---

crates/node/p2p/src/net/broadcast.rs
crates/node/p2p/src/net/driver.rs

Broadcasts blocks asynchronously with a backoff.
Closes #1529

fix(node/p2p): Async Broadcast with Backoff

---

crates/node/p2p/src/net/driver.rs

Fixes the default channel size when not set.

fix(node/p2p): Default Channel Size

---

Cargo.lock
Cargo.toml
bin/client/Cargo.toml
bin/node/Cargo.toml
crates/node/p2p/Cargo.toml
crates/proof/executor/Cargo.toml
crates/proof/proof-interop/Cargo.toml
crates/proof/proof/Cargo.toml
crates/protocol/driver/Cargo.toml

Cleans up the top level cargo manifest so as to not leak features into crates.
Also touches up the import ordering to cascade imports for aesthetic.

chore(workspace): Manifest Hygiene

---

.gitignore
.vscode/settings.json

Removes and gitignores the `.vscode` directory which is a *local* configuration file.

chore(workspace): Remove + Ignore Vscode Config

---

Cargo.lock
crates/protocol/registry/src/lib.rs

Removes the default hasher in the registry's hashmaps

chore(protocol/registry): Remove Default Hasher

---

crates/node/engine/src/task_queue/tasks/build/error.rs
crates/node/engine/src/task_queue/tasks/build/task.rs
crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/protocol/protocol/src/block.rs

Fixes the condition under which block building is triggered during payload attributes consolidation, and also fixes the build task.

fix(node): Build task + consolidate condition

---

crates/protocol/interop/Cargo.toml
crates/protocol/interop/src/derived.rs
crates/protocol/interop/src/lib.rs

feat(protocol/interop): derived ref pair

---

crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/net/builder.rs
crates/node/p2p/src/net/driver.rs
crates/node/service/src/actors/derivation.rs
crates/node/service/src/actors/network.rs
crates/node/service/src/actors/rpc.rs

This PR fixes future polling behaviors inside the kona-node to ensure that the CPU usage is kept low enough

fix(node/async): fix cpu usage from future polling

---

tests/devnets/simple-supervisor.yaml

fix: supervisor kurtosis devnet

---

crates/supervisor/core/src/lib.rs
crates/supervisor/core/src/syncnode/error.rs
crates/supervisor/core/src/syncnode/mod.rs
crates/supervisor/core/src/syncnode/node.rs

Closes https://github.com/op-rs/kona/issues/1907

chore(supervisor): Add `SubscriptionError`

---

crates/supervisor/core/src/lib.rs
crates/supervisor/core/src/syncnode/error.rs
crates/supervisor/core/src/syncnode/mod.rs
crates/supervisor/core/src/syncnode/node.rs

Closes https://github.com/op-rs/kona/issues/1909

chore(supervisor): Define `AuthenticationError`

---

docker/apps/justfile
justfile

Small PR to import docker/app justfile in main kona justfile to be able to call the recipes from the workspace root

feat(justfile/docker): import docker/app justfile in main kona justfile

---

crates/node/service/src/service/standard/builder.rs

Add check for unset config

---

Cargo.lock
crates/protocol/derive/src/sources/blobs.rs
crates/protocol/derive/src/sources/calldata.rs

Small PR to update dependencies.

chore: Update Dependencies

---

crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/node/service/src/actors/engine/finalizer.rs
crates/protocol/protocol/src/attributes.rs

Small PR to encapsulate magic block number arithmetic into a function on the `OpAttributesWithParent`

chore(protocol): Encapsulate Magic Arithmetic

---

docker/recipes/kona-node/README.md

Small update to the grafana docs to export the dashboard when committing the recipe.

chore(docker): Small Grafana Doc Update

---

crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/metrics/mod.rs

This PR adds a new metric to track the events received from gossipsub
Depends on #1914 and #1915

feat(node/p2p): adding gossipsub event metrics

---

crates/node/p2p/src/discv5/driver.rs
crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/metrics/mod.rs
crates/node/p2p/src/net/driver.rs
crates/node/rpc/src/p2p.rs
crates/utilities/macros/src/metrics.rs

Adds proper labeling for gossip event metrics.
Sets up #1925

fix(p2p): Labels for Gossip Events

---

crates/node/rpc/src/rollup.rs

Adds a simple gauge for rollup node rpc endpoints.

chore(rpc): Rollup Node RPC Endpoint Metrics

---

bin/node/src/commands/node.rs
bin/node/src/metrics/cli_opts.rs

Adds more CLI options to the gauge for grafana visibility.

chore(node): Additional CLI Option Stats

---

docker/recipes/kona-node/grafana/dashboards/overview.json

Updates the grafana dashboard to include some stylistic changes, `kona_node_gossipsub_connection` graph updates, and new `kona_cli_opts` panels.

chore(docker): Update grafana dashboard

---

bin/node/src/commands/discover.rs
crates/protocol/registry/src/chain_list.rs
crates/supervisor/storage/src/error.rs

chore: fix some typos in comment

---

Cargo.lock
Cargo.toml
bin/supervisor/Cargo.toml
bin/supervisor/src/cli.rs
bin/supervisor/src/flags/supervisor.rs
crates/supervisor/core/Cargo.toml
crates/supervisor/core/src/config/mod.rs
crates/supervisor/core/src/config/rollup_config_set.rs
crates/supervisor/core/src/lib.rs
crates/supervisor/core/src/supervisor.rs
crates/supervisor/service/src/service.rs

feat(supervisor/core): rollup config

---

crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/rpc/request.rs

Fix `opp2p_peers` rpc call by getting the supported peer protocols from the identify protocol.
Also does some light refactors to the gossip driver to clean-up some duplicate code and improve the code structure.
Progress towards #1562

fix(node/p2p): fix op-p2p peers rpc call

---

crates/node/p2p/src/gossip/driver.rs
crates/node/p2p/src/metrics/mod.rs
crates/node/p2p/src/net/driver.rs
crates/node/p2p/src/rpc/request.rs

Added Duration to be tracked that peers stay connected to libp2p swarm

---

bin/node/src/flags/globals.rs
bin/supervisor/src/cli.rs
bin/supervisor/src/flags/mod.rs
crates/utilities/cli/src/lib.rs
crates/utilities/cli/src/log.rs

chore: dedup GlobalArgs for log verbosity

---

crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/node/engine/src/task_queue/tasks/finalize/task.rs

Adds an `info` log for finalized head updates.

chore(engine): Log finalized head updates

---

crates/node/p2p/src/rpc/request.rs
crates/node/p2p/src/rpc/types.rs

feat(p2p): Peers Rpc Endpoint Progress

---

crates/node/p2p/src/rpc/request.rs

Teeny PR to return the banned peer count in the peer stats rpc request.

chore(p2p): Banned Peer Count

---

.github/workflows/e2e_tests.yaml
tests/devnets/large-kona.yaml
tests/devnets/simple-kona-geth.yaml
tests/devnets/simple-kona.yaml
tests/justfile
tests/node-devstack/init_test.go
tests/node-devstack/simple_preset.go
tests/node-devstack/sync_test.go

This PR adds required configuration to bootstrap devstack e2e tests for the kona-node.
In particular it:
- Does small updates to the e2e justfile to help run node devstack tests
- Adds the devstack tests to CI
- Adds the required configuration to the network configuration files
Progress towards https://github.com/op-rs/kona/issues/2100

feat(node/e2e-tests): bootstrap devstack testing suite

---

bin/node/src/flags/globals.rs

Adds an environment variable for the L2 chain ID.

chore(node): Add L2 chain ID environment variable

---

crates/supervisor/core/src/supervisor.rs

Closes https://github.com/op-rs/kona/issues/1727

feat(supervisor/rpc); Implement `supervisor_syncStatus` DB read

---

.gitignore

Adds rust compiler bug reports to gitignore

Add rustc bug reports to gitignore

---

tests/devnets/simple-supervisor.yaml
tests/supervisor/init_test.go
tests/supervisor/state_test.go
tests/supervisor/sync_test.go

chore(supervisor): state e2e

---

crates/supervisor/core/src/supervisor.rs
crates/supervisor/storage/src/chaindb.rs

fear(supervisor/core): added a new method to fetch the super head in a single tx

---

crates/supervisor/core/src/rpc/server.rs
crates/supervisor/core/src/supervisor.rs
crates/supervisor/rpc/src/jsonrpsee.rs

feat(supervisor/rpc): implement `supervisor_finalizedL1`

---

Cargo.lock
crates/protocol/interop/Cargo.toml
crates/protocol/interop/src/message.rs

feat(supervisor/interop): added a `chain_id` field to ExecutingDescriptor

---

crates/supervisor/core/src/syncnode/node.rs

fix(supervisor): use raw config l2 url

---

tests/devnets/large-kona.yaml
tests/devnets/simple-kona-geth.yaml
tests/devnets/simple-kona.yaml
tests/devnets/simple-supervisor.yaml
tests/go.mod
tests/go.sum
tests/justfile
tests/node-devstack/mixed_preset.go
tests/node/node_test.go
tests/node/rpc_test.go

Pull the latest version from the monorepo inside the test fork.

chore(node/test): update dependencies

---

crates/node/service/src/actors/derivation.rs

feat(node/service): Supervisor Engine Resets

---

crates/node/engine/Cargo.toml
crates/node/service/Cargo.toml
crates/node/sources/Cargo.toml
crates/providers/providers-alloy/Cargo.toml

Enables the `reqwest-default-tls` features in `alloy-provider` + `alloy-transport-http`

fix(node/service): Enable TLS in alloy providers / transports

---

.github/CODEOWNERS

This PR fixes the code owners list.

fix(github/codeowner): fix code owners list

---

book/src/protocol/derive/intro.md
book/src/protocol/derive/signaling.md
book/src/protocol/derive/stages.md
crates/protocol/derive/src/test_utils/mod.rs
crates/protocol/derive/src/test_utils/pipeline.rs

Updates the kona book with the indexed and polling traversal stages.

chore(book): Indexed + Polling Traversal Stage Docs

---

crates/protocol/interop/src/message.rs
crates/supervisor/core/src/supervisor.rs

fix(supervisor/rpc): invalid param `check_accesslist`

---

crates/node/engine/src/state/core.rs

Fixes the block label metrics. A recent PR removed them.

fix(node/service): Block label metrics

---

book/src/proof/intro.md

chore: fix broken url

---

crates/node/engine/src/task_queue/tasks/consolidate/task.rs
crates/node/engine/src/task_queue/tasks/forkchoice/task.rs

Cleans up the engine task logs.

chore(node/service): Clean up engine task logs

---

crates/supervisor/core/src/rpc/server.rs
crates/supervisor/core/src/syncnode/resetter.rs
crates/supervisor/rpc/src/response.rs
crates/supervisor/storage/src/chaindb.rs
crates/supervisor/types/src/head.rs

fix(supervisor/rpc): making all head ref as optional in syncStatus method

---

bin/node/src/commands/node.rs
bin/node/src/flags/sequencer.rs
crates/node/service/src/actors/mod.rs
crates/node/service/src/actors/sequencer/actor.rs
crates/node/service/src/actors/sequencer/config.rs
crates/node/service/src/actors/sequencer/mod.rs
crates/node/service/src/lib.rs
crates/node/service/src/service/standard/builder.rs
crates/node/service/src/service/standard/node.rs

Wires in the sequencer configuration from `SequencerArgs`, through the `RollupNodeBuilder`, to the `SequencerActor`

feat(node/service): Wire in sequencer configuration

---

docs/docs/pages/rfc/archived/umbrellas.mdx
docs/sidebar.ts

Move inactive RFCs to the archived section.

chore(docs): Categorize RFCs

---

docs/docs/pages/index.mdx

fix(docs): Front Page

---

crates/node/service/src/actors/engine/actor.rs
crates/node/service/src/actors/runtime.rs
crates/node/service/src/service/core.rs
crates/node/service/src/service/standard/builder.rs

Simple cleanup: decouples engine and runtime actor.

chore(node/engine): decouple engine and runtime actor

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/supervisor/rpc/Cargo.toml
crates/utilities/cli/Cargo.toml

Couple more artifacts from crate releases.

chore: More Crate Releases

---

crates/node/service/src/actors/rpc.rs

This PR logs the address to which RPC server binds to at startup.
@protolambda

feat(node/rpc): log rpc server address

---

docs/docs/pages/node/configuration.mdx

Update the flags in the `kona-node` documentation.
closes #2448

chore(docs): Update `kona-node` flags

---

crates/node/engine/src/task_queue/tasks/forkchoice/task.rs

Fixes an issue in the `ForkchoiceTask` where it throws a temporary error during EL sync, causing the insert tasks to stack up in the engine queue.

fix(engine): Allow `ForkchoiceTask` to drive EL sync

---

docker/recipes/kona-node/docker-compose.yaml

Fixes the prometheus address, should be the internal IP.

fix(docker): Prometheus addr

---

CHANGELOG.md
Cargo.lock
Cargo.toml
crates/proof/executor/Cargo.toml
crates/proof/mpt/Cargo.toml
crates/protocol/comp/Cargo.toml
crates/protocol/driver/Cargo.toml

Cut a few more crate releases to keep everything up to date.

chore: Few Crate Releases

---

docker/recipes/kona-node/cfg.env
docker/recipes/kona-node/docker-compose.yaml

Add an environment variable to specify cluster name inside the docker configuration of the kona-node to avoid clashes.

feat(docker): add env var to specify cluster name, docker images, grafana port

---

CHANGELOG.md
Cargo.lock
Cargo.toml
bin/node/Cargo.toml
crates/node/engine/Cargo.toml
crates/node/p2p/Cargo.toml
crates/node/peers/Cargo.toml
crates/node/rpc/Cargo.toml
crates/node/service/Cargo.toml
crates/node/sources/Cargo.toml
crates/protocol/comp/Cargo.toml
crates/protocol/derive/Cargo.toml
crates/protocol/genesis/Cargo.toml
crates/protocol/hardforks/Cargo.toml
crates/protocol/interop/Cargo.toml
crates/protocol/protocol/Cargo.toml
crates/protocol/registry/Cargo.toml
crates/providers/providers-alloy/Cargo.toml
crates/supervisor/rpc/Cargo.toml
crates/supervisor/types/Cargo.toml
crates/utilities/cli/Cargo.toml
crates/utilities/macros/Cargo.toml
crates/utilities/serde/Cargo.toml

Release artifacts for the `kona-node` release `v0.1.1`.

release: kona-node v0.1.1

---

crates/node/service/src/actors/sequencer/actor.rs
crates/node/service/src/actors/sequencer/origin_selector.rs

feat(node/service): support sequencer recovery mode

---

crates/supervisor/core/src/error.rs
crates/supervisor/core/src/rpc/server.rs
crates/supervisor/storage/src/error.rs
crates/supervisor/storage/src/lib.rs
crates/supervisor/storage/src/providers/derivation_provider.rs
crates/supervisor/storage/src/providers/log_provider.rs

Defines `EntryNotFoundError` to replace `String` for error variant `StorageError::EntryNotFound`

chore(supervisor/storage): Define `EntryNotFoundError`

---

crates/supervisor/core/src/safety_checker/cross.rs
crates/supervisor/core/src/safety_checker/error.rs
crates/supervisor/core/src/safety_checker/task.rs
crates/supervisor/storage/src/chaindb_factory.rs
crates/supervisor/storage/src/traits.rs
crates/supervisor/types/src/access_list.rs

feat(supervisor/core): [Safety Checker] executing message validation

---

crates/node/service/src/actors/sequencer/actor.rs
crates/providers/providers-alloy/src/blobs.rs
tests/node/conductor_test.go

This PR fixes minor spelling errors in code comments across three files to improve documentation accuracy.
- **`crates/node/service/src/actors/sequencer/actor.rs`**: Fix "occurence" → "occurrence"
- **`crates/providers/providers-alloy/src/blobs.rs`**: Fix "implemend" → "implement" 
- **`tests/node/conductor_test.go`**: Fix "transfering" → "transferring"

Fix typos in code comments across multiple files

---

crates/node/service/src/actors/rpc.rs

Exposes the `healthz` RPC method as a GET endpoint at `/healthz`.

feat(node/service): Expose standalone `healthz` endpoint

---

.github/workflows/claude-code-review.yml
.github/workflows/claude.yml

Support claude app in the kona repository.

chore: Setup Claude

---

crates/supervisor/storage/src/chaindb.rs
crates/supervisor/storage/src/chaindb_factory.rs
crates/supervisor/storage/src/metrics.rs

This PR refactors the metrics system in the supervisor storage layer, replacing hardcoded string literals with constants and improving the metrics initialization pattern.

chore(supervisor/storage): fix metrics

---

bin/supervisor/Architecture.md
bin/supervisor/README.md

chore(supervisor): architecture doc

---

crates/supervisor/storage/src/chaindb.rs
crates/supervisor/storage/src/providers/head_ref_provider.rs

feat(supervisor/storage): support activation block rewinding

---

crates/node/sources/src/runtime/mod.rs

chore: fix 404 URL

---

bin/client/justfile
crates/proof/std-fpvm/src/tracing.rs
docker/cannon/mips64-unknown-none.json
docker/fpvm-prestates/cannon-repro.dockerfile

Adds the reproducible build recipe for `cannon` back in.

chore(docker): Add back cannon reproducible build

---

crates/protocol/comp/src/channel_out.rs

a bit incompleted comment bumped into my eye

fix: complete incomplete comment in ChannelOut config field

---

Cargo.lock
Cargo.toml
bin/client/src/fpvm_evm/precompiles/bn128_pair.rs
bin/client/src/fpvm_evm/precompiles/provider.rs
bin/host/src/eth/precompiles.rs

Updates execution dependencies.

chore(deps): Execution Dependency Updates

---

crates/supervisor/core/src/syncnode/resetter.rs

fix(supervisor/core): resetter fallback finalized to activation block

---

crates/supervisor/core/src/supervisor.rs
crates/supervisor/storage/src/chaindb.rs
crates/supervisor/storage/src/providers/derivation_provider.rs
crates/supervisor/storage/src/providers/log_provider.rs

fix(supervisor): refactored error logging

---

bin/supervisor/README.md

chore: fix kona-supervisor  CLI

---

.github/codecov.yml
.github/workflows/node_e2e_sysgo_tests.yaml
tests/justfile

Close #2022, reports coverage information from the sysgo test jobs. Also make sure every important crate is reported

feat(node/ci): report coverage information from the sysgo tests

---

Cargo.toml

Add @emhane to the list of authors in the cargo.toml

chore(authors): add emhane to authors

---

.github/workflows/publish_artifacts.yaml

This PR fixes the CI job to publish proof artifacts

fix(proof): publish proof artifacts

---

docs/docs/components/SdkShowcase.tsx

https://github.com/op-rs/kailua - broken
https://github.com/boundless-xyz/kailua - correct

docs: fix broken link

---

crates/protocol/registry/README.md

https://docs.rs/kona-registry/latest/superchain/struct.CHAINS.html
https://docs.rs/kona-registry/latest/superchain/struct.OPCHAINS.html
https://docs.rs/kona-registry/latest/superchain/struct.ROLLUP_CONFIGS.html - these three looked really tired
But these three look fresh
https://docs.rs/kona-registry/latest/kona_registry/struct.CHAINS.html
https://docs.rs/kona-registry/latest/kona_registry/struct.OPCHAINS.html
https://docs.rs/kona-registry/latest/kona_registry/struct.ROLLUP_CONFIGS.html

docs: fix broken links

---

.github/workflows/node_e2e_sysgo_tests.yaml
.gitmodules
tests/go.mod
tests/go.sum
tests/justfile
tests/node/common/init_test.go
tests/node/common/p2p_test.go
tests/node/common/sync_test.go
tests/node/common/sync_ws_test.go
tests/node/long-running/init_test.go
tests/node/reorgs/init_test.go
tests/node/restart/conn_drop_test.go
tests/node/restart/init_test.go
tests/node/restart/restart_test.go
tests/node/utils/mixed_preset.go
tests/node/utils/mod.go
tests/node/utils/test_sequencer_preset.go

This PR changes our e2e tests presets to allow to deploy large mixed devnets. This deprecates kurtosis CI that was broken in #2892

feat(tests/e2e): deprecate kurtosis, replace by sysgo tests

---

.github/workflows/docker.yaml

Fix permissions of gha docker workflow to publish tags

fix(gha): fix docker workflow permissions

---

Cargo.lock
Cargo.toml
crates/providers/providers-alloy/src/beacon_client.rs
crates/providers/providers-alloy/src/blobs.rs
crates/providers/providers-alloy/src/lib.rs

Update `eth/v1/beacon/blobs` response type to use alloy's new bindings

chore(deps): upgrade alloy dependencies. update the get blobs response type
