op-rs/kona

- crates/preimage/Cargo.toml
Specifies the version of `kona-common` to use in `kona-preimage` for `release-plz`.
> fix: specify common version

- crates/common/src/executor.rs
- crates/common/src/lib.rs
Adds a simple blocking async executor to `kona-common`. This will be useful to use `async` colored data sources in the derivation pipeline.
> feat(common): Add simple blocking async executor

- crates/derive/src/types/eips/deposit.rs
- crates/derive/src/types/eips/mod.rs
- crates/derive/src/types/transaction/envelope.rs
> feat: Add `TxDeposit` type

- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/stages.rs
- crates/derive/src/types/system_config.rs
Implements the L1 retrieval stage of the derivation pipeline.
> feat: L1 retrieval

- crates/derive/src/lib.rs
- crates/derive/src/params.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/types/frame.rs
- crates/derive/src/types/mod.rs
- crates/derive/src/types/system_config.rs
Adds the frame queue stage for the derivation pipeline.
> feat: Frame queue stage

- Cargo.lock
- README.md
- crates/derive/Cargo.toml
- crates/derive/README.md
- crates/derive/src/params.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/stages.rs
- crates/derive/src/types/channel.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/frame.rs
- crates/derive/src/types/mod.rs
Implements the channel bank stage of the derivation pipeline.
> feat(derive): channel bank

- Cargo.lock
- fpvm-tests/cannon-rs-tests/Cargo.lock
Upgrades `mio`, per the dependabot PRs. Does both at once as to pass CI.
> dependabot: upgrade mio

- Cargo.lock
- crates/derive/Cargo.toml
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/test_utils.rs
- crates/derive/src/traits/test_utils/.gitignore
- crates/derive/src/traits/test_utils/data_availability.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/block.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/genesis.rs
- crates/derive/src/types/mod.rs
- crates/derive/src/types/rollup_config.rs
- crates/derive/src/types/system_config.rs
Introduces test utilities to the `derive` crate `traits` module to allow for clean `Stage` unit testing.
> feat(derive): Test Utilities

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/l1_traversal.rs
Performs the naive implementation to share the `RollupConfig` across stages by wrapping it in an `Arc`.
**Metadata**
Fixes #70
> fix(derive): Share the RollupConfig across Stages with an Arc

- .github/workflows/issue_cycler.yaml
Adds a workflow that runs every Monday morning at `05:00` that moves any issues placed in the previous cycle, that aren't `Done`, to the current cycle in the `kona-development` project.
> feat(ci): Add workflow to cycle issues

- Cargo.lock
- crates/derive/Cargo.toml
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/types/batch.rs
- crates/derive/src/types/batch_type.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/mod.rs
Implements the basic enumerable `Batch` type for the `ChannelReader`.
Implements the `ChannelReader` stage.
**Metadata**
Fixes #51
> feat(derive): Channel Reader Implementation

- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/sources/factory.rs
- crates/derive/src/sources/plasma.rs
- crates/derive/src/sources/source.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/test_utils/data_availability.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/mod.rs
Fixes up the async iterator usage.
Nested associated types were not behaving nicely, so I duped the `Item` type and piped it into the iterator.
This has the unfortunate trait that the item has to be bounded to a new `IntoFrames` trait that allows the frame queue to transform the item into frames... There must be a better way to architect this, but I'll stash this for now.
> fix: Data Sources Async Iterator

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
Fixes up frame queue bubbling. Previously, errors were being wrapped where they shouldn't have been.
Also cleans up frame queue docs and notes where logging should be introduced.
> fix(derive): Frame Queue Error Bubbling and Docs

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/l1_traversal.rs
Updates the stage params to be wrapped in `Arc`s, fixing the bricked constructor internal Arc instantiations.
> fix(derive): Bricked Stage Arc'd Param Construction

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/types/errors.rs
Cleans up the `L1Traversal` stage doc comments and adds further testing.
> chore(derive): L1Traversal Doc and Test Cleanup

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
Implements the `OriginProvider` across stages, removing the method definitions.
> fix(derive): OriginProvider Trait Usage

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/stages/test_utils/attributes_queue.rs
- crates/derive/src/stages/test_utils/batch_queue.rs
- crates/derive/src/stages/test_utils/channel_bank.rs
- crates/derive/src/stages/test_utils/channel_reader.rs
- crates/derive/src/stages/test_utils/frame_queue.rs
- crates/derive/src/stages/test_utils/mod.rs
- crates/derive/src/traits/test_utils.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/payload.rs
Decouples stages using minimal traits.
This allows for extensible, portable testing using mock providers that implement the stage provider traits.
Also has the added benefit of reducing the number of stagewise generics.
> fix(derive): Stage Decoupling

- Cargo.lock
- crates/derive/Cargo.toml
- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/traits/ecrecover.rs
- crates/derive/src/traits/mod.rs
Adds a new trait, `SignedRecoverable`, which represents the functionality for recovering a public key from a signed type that has access to the message hash.
With the `k256` feature enabled, a default implementation of this trait is implemented on `TxEnvelope` from `alloy-consensus`. This feature can be disabled to allow for a custom secp256k1 recovery method. This will be used in the program to facilitate an accelerator for signature recovery during verification through the host program.
If the `k256` feature is not enabled, and there is no implementation of the `SignedRecoverable` extension trait on `TxEnvelope`, the `kona-derive` crate will fail to compile.
> feat(derive): Add `ecrecover` trait + features

- crates/common/src/asterisc/io.rs
- crates/common/src/asterisc/syscall.rs
- crates/common/src/cannon/io.rs
- crates/common/src/cannon/syscall.rs
- crates/common/src/io.rs
- crates/common/src/lib.rs
- crates/common/src/traits/basic.rs
- crates/common/src/types.rs
- crates/preimage/src/pipe.rs
Removes the `RegisterSize` type in `kona-common` in favor of `usize`, which natively represents the pointer size of the target. https://doc.rust-lang.org/stable/std/primitive.usize.html
> feat(common): Move from `RegisterSize` to native ptr size type

- Cargo.lock
- Cargo.toml
- crates/common/src/io.rs
- crates/preimage/Cargo.toml
- crates/preimage/src/hint.rs
- crates/preimage/src/key.rs
- crates/preimage/src/lib.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/traits.rs
> [!NOTE]
> Blocked by #94 
Adds the host end of the `PreimageOracle` ABI plumbing. This includes two new traits:
* `PreimageOracleServer`
* `HintReaderServer`
as well as implementations of both of them that compliment the existing client handles, the `OracleReader` and `HintWriter`.
> feat(preimage): `OracleServer` + `HintReader`

- Cargo.lock
- crates/derive/Cargo.toml
- crates/derive/src/alloy_providers.rs
- crates/derive/src/lib.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/ecrecover.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/stages.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/attributes.rs
- crates/derive/src/types/batch/mod.rs
- crates/derive/src/types/batch/span_batch/batch.rs
- crates/derive/src/types/batch/span_batch/raw.rs
- crates/derive/src/types/block.rs
- crates/derive/src/types/mod.rs
- crates/derive/src/types/payload.rs
- justfile
> [!NOTE]
> Blocked by need for `TxDeposit` variant in `TxEnvelope`.
Implements an online implementation of the `ChainProvider` trait, backed by an alloy RPC client. This provider is gated by the `alloy-providers` feature flag.
> feat(derive): Online `ChainProvider`

- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/types/batch/mod.rs
- crates/derive/src/types/batch/span_batch/batch.rs
- crates/derive/src/types/batch/span_batch/raw.rs
Swaps over to deriving the full `SpanBatch`, now that the implementation of `RawSpanBatch` is mostly stable.
> chore(derive): Derive full `SpanBatch` in channel reader

- crates/derive/src/types/deposits.rs
- crates/derive/src/types/l1_block_info.rs
- crates/derive/src/types/mod.rs
Adds the `L1BlockInfoTx` type, which supports encoding and decoding L1 info transactions on the OP Stack for both `Bedrock` and `Ecotone` versions.
A secondary constructor, `try_new_with_deposit_tx`, has been added that allows for generating the `TxDeposit` required in the attributes builder.
> feat(derive): Add `L1BlockInfoTx`

- Cargo.lock
- crates/derive/Cargo.toml
- crates/derive/src/alloy_providers.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/stages/test_utils/attributes_queue.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/attributes.rs
- crates/derive/src/types/block.rs
- crates/derive/src/types/l1_block_info.rs
- crates/derive/src/types/mod.rs
- crates/derive/src/types/payload.rs
Updates the `L2ChainProvider` implementation to use the proper OP Stack types, and completes the block info / payload by hash fetching.
> feat(derive): `L2ChainProvider` w/ `op-alloy-consensus`

- build/justfile
- fpvm-tests/justfile
Cleans up the justfiles w/ default directives and fallbacks. Does not touch the justfiles in the example program directories.
> chore(workspace): Cleanup justfiles

- .github/workflows/ci.yaml
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/types/ecotone.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/mod.rs
Allows the CI to fail on doclint failure, and fixes our existing warnings/errors.
> chore(ci): Fail CI on doclint failure

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/types/attributes.rs
- crates/derive/src/types/errors.rs
- crates/derive/src/types/l1_block_info.rs
- crates/derive/src/types/payload.rs
Includes the `L1BlockInfoTx` within the payload builder
> feat(derive): Build `L1BlockInfoTx` in payload builder

- Cargo.toml
- crates/derive/Cargo.toml
- crates/preimage/Cargo.toml
- examples/simple-revm/Cargo.lock
Moves `alloy-primitives` to the workspace dependencies, as it's used in multiple crates at the moment.
> chore(workspace): Move `alloy-primitives` to workspace dependencies

- crates/derive/src/stages/attributes_queue/deposits.rs
Adds unit tests to the attributes queue utility method to derive deposits from fetched logs and receipts.
**Metadata**
Fixes https://github.com/ethereum-optimism/kona/issues/114
> feat(derive): Deposit Derivation Testing

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/stages/test_utils/mod.rs
- crates/derive/src/stages/test_utils/sys_config_fetcher.rs
- crates/derive/src/traits/test_utils/data_sources.rs
Adds unit tests to the `PayloadAttributes` builder. As part of this testing, a `MockSystemConfigL2Fetcher` stub is introduced into the stage `test_utils` module.
> feat(derive): Payload Attributes Builder Tests

- crates/derive/src/online/alloy_providers.rs
- crates/derive/src/sources/factory.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/stages/test_utils/sys_config_fetcher.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/l1_block_info.rs
- crates/derive/src/types/payload.rs
- crates/derive/src/types/rollup_config.rs
- crates/derive/src/types/system_config.rs
Reuses the `L2ChainProvider` for fetching the `SystemConfig` at a given block, rather than having an exlusive trait that extends the `L2ChainProvider`.
> feat(derive): Use `L2ChainProvider` for system config fetching in attributes builder

- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/test_utils/tracing.rs
- crates/derive/src/types/batch/mod.rs
- crates/derive/src/types/batch/span_batch/batch.rs
- crates/derive/src/types/batch/span_batch/element.rs
- crates/derive/src/types/payload.rs
Implements span batch validation.
Unfortunately since the fetcher is colored, we have to mark pure batch derivation methods with `async`.
**Metadata**
Fixes #120
> feat(derive): Span Batch Validation

- Cargo.lock
- README.md
- crates/mpt/Cargo.toml
- crates/mpt/README.md
- crates/mpt/src/lib.rs
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/mpt/src/test_util.rs
> [!NOTE]
> Blocked by https://github.com/alloy-rs/alloy/pull/596, which will allow for continuously testing @ tip rather than a fixed block that contains no blob transactions. _edit:_ will just update later
Adds a new crate, `kona-mpt`, where we can put utilities for interacting with the Merkle Patricia Trie in the client program.
To start off, this crate includes the `OrderedListWalker`, which allows for traversing over a merkle patricia trie root that represents an ordered list (i.e., the transactions or receipt root in ETH block headers.) It does so by taking in a preimage fetching function, which is able to return the raw RLP of blinded nodes within the MPT.
> feat: `kona-mpt` crate

- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/traits/test_utils/data_sources.rs
- crates/derive/src/types/batch/mod.rs
- crates/derive/src/types/batch/span_batch/batch.rs
- crates/derive/src/types/ecotone.rs
Removes some erroneous `#[allow(dead_code)]` declarations across the `kona-derive` crate and fixes span batch validation to set the parent block number. It previously fallibly shadowed the `parent_num` variable in a lower block.
> fix(derive): Small Fixes and Span Batch Validation Fix

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/main.rs
- bin/host/src/parser.rs
- bin/host/src/types.rs
meant to address issue #132 Host Tracking
> WIP host tracking

- crates/derive/src/types/batch/span_batch/batch.rs
- crates/derive/src/types/batch/span_batch/raw.rs
Migrates the `to_raw_span_batch` method logic into the `TryFrom` trait implementation on the `RawSpanBatch`.
Arguments to the `to_raw_span_batch` method were unused anyways. The reference implementation accepts no arguments to its [`ToRawSpanBatch`](https://github.com/ethereum-optimism/optimism/blob/6f99544c57ef837afaa96f979a6154a4e8a3604a/op-node/rollup/derive/span_batch.go#L548) conversion method.
**Tests**
Added unit tests around the trait implementation edge cases.
> fix(derive): TryFrom<SpanBatch> for RawSpanBatch

- crates/derive/src/online/mod.rs
Fixes the types in the online stack constructor to use concrete types.
> feat(derive): Concrete AttributesQueue Return Type

- crates/derive/src/online/mod.rs
Removes a duplicate `online` attribute config inside the `online` module.
> fix(derive): Remove Duplicate Online Feature Attribute

- crates/plasma/src/source.rs
**Descriptioin**
Reduces the generic verbosity on the `Plasma` source from `<CP, PIF, I>` to `<C, F, I>`. Keeping things simple.
> chore(plasma): Reduce PlasmaSource Generic Verbosity

- crates/derive/src/traits/test_utils.rs
- crates/derive/src/types/errors.rs
- crates/plasma/src/plasma.rs
- crates/plasma/src/source.rs
Unit tests the `PlasmaSource`.
Fixes the `PartialEq` implementation on some `StageError` variants not comparing the internal fields.
Also supports specifying the block transaction list in the test chain provider.
> fix(plasma): Unit Test the Plasma Source

- justfile
Optimizes the lint jobs by only including the crates with architecture-specific code (`kona-common`) in the `lint-asterisc` and `lint-cannon` recipes. All other crates have full lint coverage with the native lint recipe.
We still include all `no_std` crates in the `build` recipes for `cannon` / `asterisc` targets, as these crates still need build coverage to ensure that they always compile to our required targets.
> chore(workspace): Exclude all crates except `kona-common` from cannon/asterisc lint job

- crates/plasma/src/plasma.rs
Removes unused fields from the plasma data source.
Cleans up doc comments.
Uses the canonical block id constructor.
> fix(plasma): Plasma Data Source Cleanup

- crates/derive/src/sources/ethereum.rs
Fixes the ethereum data source to default to a calldata-based provider if the ecotone timestamp is not set, following the [reference implementation](https://github.com/ethereum-optimism/optimism/blob/develop/op-node/rollup/derive/data_source.go#L75-L82).
> fix(derive): Ethereum Data Source

- crates/derive/src/types/batch/span_batch/utils.rs
instead of copying the entire buffer, de-reference twice to make a new mutable reference of the input u8 array
> fix(derive): fix span batch utils read_tx_data()

- Cargo.lock
- crates/mpt/Cargo.toml
- crates/mpt/README.md
- crates/mpt/src/lib.rs
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/mpt/src/test_util.rs
Refactors the `TrieNode` type to not contain the intermediate `NodeElement`, but rather be recursive upon itself. This allows us to create openings on a root `TrieNode` within the cache database and cache all opened nodes throughout the execution of each block.
> feat(mpt): Refactor `TrieNode`

- crates/mpt/src/db/account.rs
- crates/mpt/src/db/mod.rs
- crates/mpt/src/lib.rs
Introduces the scaffolding for the `TrieCacheDB`, a `revm` `Database` backed by a `TrieNode` with a fetcher for the preimages of intermediate blinded nodes.
This PR only implements the logic for fetching and caching data from the state root verifiably. Follow-up PRs will implement the logic for updating the state root as well as the `DatabaseCommit` trait implementation, as these are more complex areas that should get independent review.
> feat(mpt): `TrieCacheDB` scaffold

- crates/preimage/src/key.rs
Adds the new global precompile preimage key type, as described in [the
spec](https://specs.optimism.io/experimental/fault-proof/index.html#type-6-global-precompile-key)
> feat(precompile): Add `precompile` key type

- crates/common/src/io.rs
Uses `Box::leak` to ensure that the files that are constructed from raw
file descriptors are kept alive for the static lifetime of the program,
rather than `mem::forget`.
> chore(common): Use `Box::leak` rather than `mem::forget`

- .github/workflows/cross_docker.yaml
- .github/workflows/fpvm_tests.yaml
- .github/workflows/rust_ci.yaml
Adds extra triggers to the `fpvm-tests` and `rust-ci` workflows that trigger jobs on PR creation / re-opening as well as when a PR is added to the merge queue.
This should fix CI for external contributors, cc @merklefruit
> fix(ci): Run CI on `pull_request` and `merge_group` triggers

- Cargo.lock
- crates/primitives/Cargo.toml
- crates/primitives/src/payload.rs
I believe `decode_2718()` will gracefully remove the transaction type byte, so I imported it from alloy_eips.
**Tests**
I ran all existing tests, including all the decoding unit tests in `stages`.
**Metadata**
- Fixes #147
> fix(primitives): use decode_2718() to gracefully handle the tx type

- crates/derive/src/types/channel.rs
- crates/primitives/src/block_info.rs
- crates/primitives/src/system_config.rs
> fix: Strong Error Typing

- Cargo.lock
- crates/derive/Cargo.toml
- crates/plasma/Cargo.toml
- crates/preimage/Cargo.toml
- crates/preimage/src/hint.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/traits.rs
Makes the server components in `kona-preimage` async to allow for remote
data fetching in the `host` program.
> feat(preimage): Async server components

- bin/host/src/fetcher/mod.rs
- bin/host/src/kv/disk.rs
- bin/host/src/kv/mem.rs
- bin/host/src/kv/mod.rs
- bin/host/src/main.rs
- bin/host/src/server.rs
Adds a disk-backed KV store for the host program, activated when
`--data-dir` is passed.
> feat(host): Disk backed KV store

- bin/host/src/cli/mod.rs
- bin/host/src/kv/local.rs
- bin/host/src/kv/mod.rs
- bin/host/src/kv/split.rs
- bin/host/src/main.rs
- crates/preimage/src/key.rs
Adds the `LocalKeyValueStore` and the `SplitKeyValueStore`, which routes
request for local data to the in-memory configuration.
> feat(host): Add local key value store

- justfile
Adds a few aliases in the root just file for common commands used in
local development.
> chore(workspace): Add aliases in root `justfile`

- bin/programs/simple-revm/src/main.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/pipe.rs
- crates/preimage/src/traits.rs
Makes the `HintWriterClient` + `PreimageOracleClient` traits asynchronous to prevent blocking of the host program when executing a client program natively.
Previously, since the preimage oracle bindings for the client were entirely synchronous, the loops in `PipeHandle` could cause a deadlock. Now that oracle IO is asynchronous, the runtime can interrupt a future when it yields execution (i.e. `tokio::select` works.)
In the client program, synchronous execution is still guaranteed. It can run async colored functions in a minimal runtime, such as the `block_on` runtime in `kona_common`. `simple-revm` had to be changed as a part of this PR, which has an example of this.
> feat(preimage): Async client traits

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/cli/mod.rs
- bin/host/src/main.rs
- bin/host/src/types.rs
- bin/host/src/util.rs
Improves the asynchronous logic in `kona-host` to handle gracefully exiting the parallel host and client threads if either throw.
Also does a bit of cleanup in the host.
> fix(host): Blocking native client program

- .github/workflows/fpvm_tests.yaml
- .github/workflows/rust_ci.yaml
Alters the workflow triggers such that the `push` trigger only runs when the PR is merged into `main`, and the `pull_request` trigger is agnostic to the `type`. This prevents double-runs of CI workflows in the merge queue / upon PR creation.
> chore(ci): Workflow trigger changes

- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
Adds the logic required to insert a given value into a `TrieNode` at a passed path.
> feat(mpt): Trie node insertion

- Cargo.lock
- crates/mpt/Cargo.toml
- crates/mpt/src/db/mod.rs
- crates/mpt/src/node.rs
- crates/mpt/src/util.rs
Implements the `TrieCacheDB`'s `DatabaseCommit` trait, recomputing the state root when `commit` is called using the `TrieNode`.
> feat(mpt): Trie DB commit

- crates/mpt/src/db/mod.rs
- crates/mpt/src/node.rs
Hides the recursive variable in `TrieNode::insert` and `TrieNode::open`
> chore(mpt): Do not expose recursion vars

- crates/mpt/src/db/mod.rs
- crates/mpt/src/lib.rs
- crates/mpt/src/node.rs
Simplifies `TrieDB` by assuming it will be wrapped with [`revm::State`](https://github.com/bluealloy/revm/blob/fadf6fbe43a3022c1406c0d8ee062a83e951d4d3/crates/revm/src/db/states/state.rs#L29). The `State` handles the cache layer for in-memory accounts / storage, allowing the `TrieDB` to focus solely on caching open trie state and state root recomputation.
The `State` struct in `revm` is better for our usecase, since it allows for merging a `BundleState` after a full block's execution. The previous implementation had the fatal flaw having to recompute the state root every time the `DatabaseCommit` trait implementation was invoked, which was not suitable.
Examples of usage may be found within the rustdoc for `TrieDB`.
> feat(mpt): Simplify `TrieDB`

- crates/mpt/src/db/mod.rs
Introduces the implementation for `Database::block_hash` for `TrieDB`, allowing the `BLOCKHASH` opcode to verifiably fetch a block hash within the most recent `256` blocks, not including the block that is currently being executed.
> feat(mpt): Block hash walkback

- crates/derive/src/builder.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/reset.rs
Refactors the `ResetProvider` in preparation for a pulling a default impl out of `kona-exex` and into `kona-derive`.
> chore: Refactor ResetProvider

- crates/derive/src/lib.rs
- crates/derive/src/pipeline/builder.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/pipeline/mod.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/traits/attributes.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/pipeline.rs
Refactors the derivation pipeline into it's own module with a builder.
A few previously siloed traits were pulled into the `traits` module and re-exported where needed.
On top of this pr, will be stacked a few refactors to the online helper methods and implementations.
> feat: Pipeline Builder

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/kv/local.rs
- bin/programs/client/Cargo.toml
- bin/programs/client/justfile
- bin/programs/client/src/boot.rs
- bin/programs/client/src/comms/caching_oracle.rs
- bin/programs/client/src/comms/mod.rs
- bin/programs/client/src/executor/mod.rs
- bin/programs/client/src/lib.rs
- bin/programs/client/src/main.rs
- bin/programs/minimal/Cargo.toml
- bin/programs/minimal/src/main.rs
- bin/programs/simple-revm/src/main.rs
- crates/common-proc/src/lib.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/oracle.rs
Begins the client program, adding the `BootInfo` prologue phase implementation (sans the `RollupConfig` / `ChainConfig`, waiting on https://github.com/ethereum-optimism/kona/issues/193 for these)
> feat(client): `BootInfo`

- crates/primitives/src/block.rs
- crates/primitives/src/lib.rs
Removes the custom `Withdrawal` type definition, replacing it with the [`alloy_eips::eip4895::Withdrawal`](https://github.com/alloy-rs/alloy/blob/main/crates/eips/src/eip4895.rs#L21) type.
Fixes #212.
> chore: Alloy Withdrawal Type

- crates/derive/src/types/blob.rs
- crates/derive/src/types/mod.rs
- crates/derive/src/types/sidecar.rs
Replaces `kona-derive` custom `Blob` type with `alloy_eips` 4844 Blob type.
**Metadata**
Fixes #214.
> fix(derive): Alloy EIP4844 Blob Type

- bin/host/README.md
- bin/host/src/main.rs
- bin/programs/client/src/main.rs
- bin/programs/minimal/src/main.rs
- bin/programs/simple-revm/src/main.rs
- crates/common-proc/src/lib.rs
Simplifies the host program by removing the race between the native client / native server, in favor of allowing them both to gracefully finish.
> chore(host): Simplify host

- crates/primitives/src/payload.rs
Fixes payload encoding to use the alloy eips 2718 Encodable trait and associated method.
> fix(primitives): 2718 Payload Encoding

- bin/programs/client/src/l2/executor/mod.rs
- crates/mpt/src/db/mod.rs
Adds a function to the block executor that allows for generating the current output root, based on the parent timestamp and current trie.
> feat(client): Add `compute_output_root` to block executor

- crates/derive/Cargo.toml
- crates/derive/src/online/alloy_providers.rs
- crates/derive/src/online/beacon_client.rs
- crates/derive/src/online/mod.rs
Now that alloy dependencies are updated to use revision [`cb95183`](https://github.com/alloy-rs/alloy/blob/cb95183d477024b57b27336035d10403e8ba55b8/crates/provider/src/lib.rs#L25), online `kona-derive` provider implementations can reuse the exported `ReqwestProvider` type instead of defining a custom `ReqwestClient` type.
In a later revision we won't need to specify the return type or wrap the method str in a Borrowed Cow. For now though, we comply with the compiler's demands.
> fix(kona-derive): Use Upstream ReqwestProvider

- bin/host/src/fetcher/hint.rs
- bin/host/src/fetcher/mod.rs
- bin/programs/client/src/l2/executor/canyon.rs
- bin/programs/client/src/l2/executor/fetcher.rs
- bin/programs/client/src/l2/executor/mod.rs
- bin/programs/client/src/l2/mod.rs
- crates/mpt/src/db/mod.rs
- crates/mpt/src/fetcher.rs
- crates/mpt/src/lib.rs
- crates/mpt/src/node.rs
Introcues the `TrieDBHinter` trait, which outlines an interface for sending hints to the host for trie account proofs and storage slot proofs. This enables `kona-host` to use `eth_getProof` rather than the very limited `debug_dbGet` for fetching most of the intermediate trie nodes during L2 execution.
**Caveat**: We do still need some sort of trie-node-by-hash function in order to fetch siblings within branches during node deletion. `debug_dbGet` works for hash-scheme geth nodes, though it is the only option at the moment. Might be time to build an indexer on reth to cache intermediate trie nodes.
> feat(client): Account + Account storage hinting in `TrieDB`

- crates/derive/src/lib.rs
- crates/derive/src/online/mod.rs
- crates/derive/src/online/pipeline.rs
Cleans up the online pipeline constructor.
> chore(kona-derive): Online Pipeline Cleanup

- Cargo.lock
- crates/plasma/Cargo.toml
- crates/plasma/src/lib.rs
- crates/plasma/src/online.rs
Stubs out an online plasma input fetcher.
> feat(plasma): Online Plasma Input Fetcher

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/fetcher/hint.rs
- bin/host/src/fetcher/mod.rs
- bin/host/src/main.rs
Implements several more hint routes in the host program
> feat(host): More hint routes

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/fetcher/mod.rs
- bin/host/src/main.rs
- bin/programs/client/src/hint.rs
- bin/programs/client/src/l1/blob_provider.rs
- bin/programs/client/src/l1/mod.rs
- crates/common/src/io.rs
- crates/derive/src/online/beacon_client.rs
- crates/derive/src/online/blob_provider.rs
Implements the oracle-backed blob fetcher for the client program
> feat(client/host): Oracle-backed Blob fetcher

- crates/common/src/io.rs
Fixes a rare synchronization error in the `NativeIO`, where when fetching is happening very fast concurrently, the file's contents may not be synced to disk fast enough for the other end of the pipe to recognize. Notably, `std::fs::File` _does not block_ on updating the metadata of the file to disk when it is being dropped. `File::sync_all` does exactly this, blocking until all metadata and in-memory contents have been flushed to disk.
> fix(common): Synchronize file to disk in `NativeIO`

- Cargo.lock
- bin/host/src/fetcher/mod.rs
- bin/host/src/main.rs
- bin/host/src/server.rs
- bin/host/src/util.rs
- bin/programs/client/Cargo.toml
- bin/programs/client/src/hint.rs
- bin/programs/client/src/l1/blob_provider.rs
- bin/programs/client/src/l1/chain_provider.rs
- bin/programs/client/src/l1/driver.rs
- bin/programs/client/src/l1/mod.rs
- bin/programs/client/src/l2/chain_provider.rs
- bin/programs/client/src/l2/executor/mod.rs
- bin/programs/client/src/main.rs
- crates/common/Cargo.toml
- crates/common/src/io.rs
- crates/mpt/src/db/mod.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/pipe.rs
Adds the `DerivationDriver` to the client program, bringing the first draft of the client program.
> feat(client): Derivation integration

- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
Touches up the `sources` module.
> chore(derive): Sources Touchups

- crates/derive/src/online/beacon_client.rs
- crates/derive/src/online/blob_provider.rs
- crates/derive/src/online/mod.rs
- crates/derive/src/online/pipeline.rs
- crates/derive/src/online/test_utils.rs
Cleans up the `online` module.
> chore(derive): Online Module Touchups

- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/validation.rs
Small PR to cleanup tracing in `trusted-sync`.
> chore(examples): trusted-sync tracing cleanup

- Cargo.lock
- Cargo.toml
- bin/programs/client/src/l2/chain_provider.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/types/ecotone.rs
- crates/executor/src/lib.rs
- crates/executor/src/util.rs
- crates/primitives/src/deposits.rs
- crates/primitives/src/payload.rs
Updates the `op-alloy-consensus` dependency to point to upstream [`op-alloy`][alloy] instead of a forked, outdated version.
[alloy]: https://github.com/alloy-rs/op-alloy
> chore(deps): Fast Forward op-alloy-consensus

- Cargo.lock
- crates/preimage/Cargo.toml
- crates/preimage/src/key.rs
We need to Serialize and Deserialize traits implemented on `PreimageKeys` to pass them into the zkVM. Adding a feature flag to the `preimage` crate to do that.
**Tests**
N/A
**Additional context**
N/A
**Metadata**
N/A
> feat(preimage): add serde feature flag to preimage crate for keys

- crates/derive/src/types/mod.rs
- crates/primitives/src/lib.rs
Small pr to re-export common input types.
> chore: Re-export Input Types

- bin/programs/client/src/kona.rs
- crates/common/src/io.rs
Alters the native IO to support Golang's `os.Pipe`, intended to allow for the `host` program in server mode to be able to communicate with the file descriptors passed from the VM.
> fix(common): Pipe IO support

- Cargo.lock
- bin/client/src/boot.rs
- crates/derive/src/online/alloy_providers.rs
- examples/trusted-sync/src/main.rs
Updates the `trusted-sync` example to dynamically load the rollup config based on the l1 chain id.
In the future this will be upstreamed into the superchain-registry.
**Metadata**
Fixes #292.
> fix(examples): Dynamic Rollup Config Loading

- Cargo.lock
- Cargo.toml
- bin/client/src/l2/chain_provider.rs
- bin/host/Cargo.toml
- bin/host/src/fetcher/mod.rs
- crates/derive/Cargo.toml
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/stages/attributes_queue/deposits.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/types/ecotone.rs
- crates/derive/src/types/fjord.rs
- crates/executor/src/eip4788.rs
- crates/executor/src/lib.rs
- crates/executor/src/util.rs
- crates/mpt/Cargo.toml
- crates/mpt/src/test_util.rs
- crates/plasma/Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/deposits.rs
- crates/primitives/src/payload.rs
- examples/trusted-sync/Cargo.toml
- examples/trusted-sync/src/validation.rs
Use versioned alloy dependencies.
> chore: Versioned Alloy Dependencies

- crates/derive/src/stages/channel_reader.rs
Fixes Fjord decompression by trimming the type byte off of the compressed data prior to decompression.
> fix(derive): Fjord brotli decompression

- Cargo.lock
- crates/mpt/Cargo.toml
- crates/mpt/src/db/mod.rs
- crates/mpt/src/node.rs
Fixes extension node truncation as well as branch node compaction in the `mpt` crate. Also removes the `*_inner` functions in favor of easier-to-read slice cursors.
> fix(mpt): Fix extension node truncation

- Cargo.lock
- Cargo.toml
- bin/client/Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/fetcher/precompiles.rs
- crates/executor/src/lib.rs
Prepares for the first release of the crates.
> chore(workspace): Prep release

- Cargo.lock
- Cargo.toml
Small PR to pin the `op-alloy-consensus` dep version.
Prepares for workspace release.
> chore(workspace): Pin op-alloy-consensus

- crates/derive/src/macros.rs
Fixes the compiler warnings for unused variables with the `timer!` macro in `kona-derive`.
> fix(derive): Warnings with metrics macro

- examples/trusted-sync/src/cli.rs
Small cli arg fix for the Loki server to allow the argument to be more generic.
> fix(examples): Small CLI Fix

- crates/derive/src/macros.rs
- crates/derive/src/metrics.rs
- crates/derive/src/online/alloy_providers.rs
- crates/derive/src/online/beacon_client.rs
- crates/derive/src/online/blob_provider.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/frame_queue.rs
Adds provider method call and error counter metrics.
> feat(derive): Granular Provider Metrics

- crates/derive/src/stages/batch_queue.rs
Removes the noisy batch logs in `info!` / `warn!` log levels within the `BatchQueue`. These cause a significant slowdown due to having to `Debug` format the entire batch, which can be tens of megabytes large when decompressed.
> chore(derive): Remove noisy batch logs

- crates/derive/src/macros.rs
- crates/derive/src/metrics.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/l1_traversal.rs
Adds two more stage metrics.
- Batch reader errors with labels.
- Batch compression ratio tracked as a gauge.
> feat(derive): Additional Stage Metrics

- bin/client/src/l1/driver.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/traits/pipeline.rs
- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/validation.rs
- Makes payload validation graceful - returning a `Result<bool>`.
- Rejiggers the pipeline to allow the consumer to peek at attributes for validation. This makes downstream validation easier such that if validation errors, no additional tracking needs to be done to re-try validation.
> fix(examples): Graceful Payload Validation

- crates/derive/src/metrics.rs
- examples/trusted-sync/src/metrics.rs
Prefix all metric names.
Metrics in `kona-derive` are prefixed with `kona_derive_*`.
Metrics in the `trusted-sync` binary are prefixed with `trusted_sync_*`.
This makes it easier to find metrics from the Grafana Metrics Explorer.
> fix(derive): Prefix Metric Names

- crates/derive/src/macros.rs
- crates/derive/src/metrics.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/types/channel.rs
Adds a metric to `kona-derive` to track the number of frames in the current (top) channel.
> feat(derive): Track Current Channel Size

- crates/derive/src/pipeline/core.rs
- crates/derive/src/traits/pipeline.rs
Binds the `Pipeline` trait to be an `Iterator<Item = L2AttributesWithParent>`.
This replaces the custom `next()` method definition with the [`core::iter::Iterator`](https://doc.rust-lang.org/stable/core/iter/trait.Iterator.html) trait that allows for greater fluency.
> fix(derive): Pipeline Iterator

- crates/derive/src/metrics.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/types/channel.rs
Histogram tracking the number of channels for various frame count buckets.
Will provide a nice heatmap visualization for how many channels have various amounts of frames.
> feat(derive): Frame Count -> Channels Histogram

- crates/derive/src/metrics.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/types/channel.rs
- examples/trusted-sync/src/main.rs
Resets the failed payload derivation metric back to 0.
This should allow it to be queried from grafana.
> fix(examples): Reset Failed Payload Derivation Metric

- crates/derive/src/stages/channel_reader.rs
Fixes the unused `raw_len` variable when the `metrics` feature flag is disabled.
> fix(derive): Unused var w/o `metrics` feature

- bin/client/src/kona.rs
- crates/executor/src/builder.rs
- crates/executor/src/lib.rs
Adds a builder pattern for `StatelessL2BlockExecutor`, in preparation for more configuration such as precompile stubs.
> feat(executor): Builder pattern for `StatelessL2BlockExecutor`

- Cargo.lock
- bin/client/Cargo.toml
- bin/client/src/kona.rs
- bin/client/src/l2/mod.rs
- bin/client/src/l2/precompiles/ecrecover.rs
- bin/client/src/l2/precompiles/mod.rs
Adds a host-accelerated precompile for `ecrecover` with the FPVM backend.
> feat(client): `ecrecover` accelerated precompile

- bin/client/src/l2/precompiles/bn128_pair.rs
- bin/client/src/l2/precompiles/mod.rs
Adds an `ecpairing` accelerated precompile for the FPVM backend.
> feat(client): `ecpairing` accelerated precompile

- examples/trusted-sync/run.sh
- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/telemetry.rs
- justfile
Cleans up the `trusted-sync` binary for infra deployment.
- Makes loki logging optional.
- Gracefully handles missing start block and metrics url.
> fix(examples): Dockerfile Fixes

- build/asterisc/asterisc-repro.dockerfile
- justfile
Adds a dockerfile and just recipe for building the reproducible prestate artifacts for `kona-client` compiled towards the `asterisc` FPVM target.
```sh
just build-client-prestate-asterisc <kona_tag> <asterisc_tag> [opt: output_dir]
```
> feat(docker): Reproducible `asterisc` prestate

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/main.rs
- bin/host/src/preimage.rs
- bin/host/src/server.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/lib.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/traits.rs
Removes dynamic dispatch from the host-oriented types in `kona-preimage`, in favor of a more flexible and readable alternative.
> chore(preimage): Remove dynamic dispatch

- .github/workflows/client_host.yaml
- bin/client/justfile
- bin/host/src/main.rs
Adds a few jobs to CI to run the host + client program against known witness data in offline mode, over both the Ecotone and Fjord hardfork.
> feat(ci): Run Host + Client natively in offline mode

- bin/client/justfile
- bin/host/src/cli/mod.rs
- bin/host/src/main.rs
Makes the `exec` flag optional in the host binary so that users may omit it when executing in `server` mode.
> chore(host): Make `exec` flag optional

- crates/derive/src/online/alloy_providers.rs
- examples/trusted-sync/run.sh
- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
- justfile
Adds a cli flag that allows `trusted-sync` to start N blocks back from tip.
Avoids needing to have a blob archiver by starting <18 days in the past.
> fix(examples): Start N Blocks Back from Tip

- .github/workflows/rust_ci.yaml
Builds benchmarks in CI (but doesn't run them), to ensure they stay maintained.
> feat(ci): Build benchmarks in CI

- build/asterisc/asterisc-repro.dockerfile
Pins the version of the `asterisc-builder` in the reproducible prestate builder. This allows for using the correct version of the builder image, which includes the rust compiler, when checking out historical tags.
> chore(docker): Pin `asterisc-builder` version in reproducible prestate builder

- examples/trusted-sync/src/cli.rs
Fixes the default `trusted-sync` metrics url to use `0.0.0.0` instead of localhost by default so port `9000` is exposed externally for prometheus to scrape metrics.
> fix: trusted-sync metrics url

- examples/trusted-sync/run.sh
metrics url was being overridden in the docker image exec command.
> fix: Small Docker Image Fix

- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/validation.rs
Logs derived and expected payload attributes on error to make investigation easier in the runbook for invalid derived payload attributes.
> chore(examples): Log Payload Attributes on Error

- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/metrics.rs
Fixes the l2 safe head to increment after payload attributes are derived.
Adds a reference l2 safe head tracker for drift alerting.
> fix(examples): L2 Safe Head Tracking

- examples/trusted-sync/src/main.rs
Reduces the origin advance error to warning.
If the next block isn't available causing an intended block fetch failure, this will error which happens often.
We should also work in some backoffs to the providers, especially for frequently repeated method calls like origin advancing.
> fix(examples): Reduce Origin Advance to Warn

- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/metrics.rs
Adds a metric to track the latest time that the reference l2 safe head has been updated. This effectively tells us the liveliness of `trusted-sync`, while also making sure that the reference safe head is updating for the other alerting.
> feat(examples): add metric for latest l2 reference safe head update

- .github/workflows/trusted_sync_docker.yaml
Adds a custom tag to the `trusted-sync` docker image github action.
> fix(actions): trusted sync docker publish

- crates/derive/src/metrics.rs
Channel frame counts tend to max out around 20-30. Previously there were multiple buckets > 20 that just contained redundant counts. This PR refines the buckets to introspect closer into the window between [1, 20].
> chore(derive): Refine Channel Frame Count Buckets

- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/metrics.rs
If drift exceeds 200 blocks, walk back the cursor by 10 blocks in case it is stuck due to one or multiple re-orgs.
Defines metrics around the walkbacks so we can track when they happen.
Also refines step result metrics so we can more granularly track when the step is `NotEnoughData` vs some other error.
> feat(trusted-sync): re-org walkback

- bin/host/src/fetcher/mod.rs
Currently, when the fetcher gathers blob data, it saves the preimages for each element in the blob, but does not save the KZG proof (because it is not needed in FPVM context). However, in the ZKVM context, we need this information.
This PR creates a short term workaround to save the kzg proof as a psuedo element 4096 in the Blob type (since the blob only uses elements 0 to 4095 inclusive).
For a longer term fix, I've opened this ticket for a feature to override fetcher implementations: https://github.com/ethereum-optimism/kona/issues/369
**Tests**
N/A
**Additional context**
N/A
**Metadata**
N/A
> feat(host): kzg proof for blobs

- crates/derive/src/macros.rs
- crates/derive/src/metrics.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/traits/pipeline.rs
- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/metrics.rs
Since stage resets are done using head recursion, it's been broken since the bottom stage (L1 Traversal) _always_ returns an Eof error, which bubbles up prior to any other stage resets. Without stages being properly reset, `trusted-sync` failed to actually prune any old block info in the l1 retrieval stage during the drift fast-forwarding logic. This causes `trusted-sync` to enter a stuck state where it continuously fetches for the invalid, potentially re-orged block.
> fix(derive): Pipeline Reset

- Cargo.lock
- Cargo.toml
- crates/primitives/Cargo.toml
Two upstream dependencies had patch releases that changes interfaces. This causes `kona` to break if `cargo update` is called. Pinning these two dependencies on the previous versions fixes the issue.
**Tests**
N/A
**Additional context**
- `op-alloy-consensus` upgraded `alloy-eips` to `0.2.0` which broke interface.
- `superchain-primitives` changed `batcher_address` field to `batcher_addr`, which broke interface.
**Metadata**
N/A
> fix: pin two dependencies due to upstream semver issues

- crates/common/src/io.rs
- crates/common/src/lib.rs
- crates/common/src/zkvm/io.rs
- crates/common/src/zkvm/mod.rs
As an alternative to #368, this PR involves adding a simple alternative IO target to `kona-common`, which is currently a no-op but might later be used for more advanced cycle tracking, etc.
**Tests**
N/A
**Additional context**
N/A
**Metadata**
N/A
> feat: add zkvm target for io

- bin/client/src/l2/precompiles/mod.rs
- crates/executor/src/builder.rs
- crates/executor/src/canyon.rs
- crates/executor/src/lib.rs
- crates/executor/src/precompile.rs
Drops the intermediate in-memory `revm` cache between blocks when executing multiple blocks in a row with the `StatelessL2BlockExecutor`.
This fixes a bug where, when executing multiple blocks, the client program does not reach out to the host for the path to the account in the state trie in the _new_ state root. While we do not need support for contiguous block execution in upstream, this allows downstream consumers like Succinct to perform this action with `kona-executor`.
> fix(executor): Don't hold onto intermediate execution cache across block boundaries

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- crates/derive/Cargo.toml
- crates/derive/src/sources/ethereum.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/mpt/Cargo.toml
- crates/plasma/Cargo.toml
- crates/primitives/Cargo.toml
- crates/primitives/src/block_info.rs
- crates/primitives/src/payload.rs
- examples/trusted-sync/Cargo.toml
- examples/trusted-sync/src/main.rs
Bumps all alloy dependencies to `0.2.*` as well as the `superchain-registry` + `superchain-primitives` versions. This allows `kona-derive` to be compatible with anvil and foundry deps for `op-test-vectors`.
**Metadata**
Fixes #392
Fixes #261
> fix(deps): Bump Alloy Dependencies

- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/sources/ethereum.rs
- crates/derive/src/sources/variant.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/test_utils.rs
- crates/plasma/src/source.rs
Previously, the `DataIter` returned an `Option<Result<...>>`.
Whenever the `Option` was `None`, the downstream consumers would just return a `StageError::Eof`. Instead, this PR removes the `Option`, and returns a `StageError::Eof` directly if the Option is of variant `None`.
> fix(kona-derive): Remove DataIter Option Return

- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
- examples/trusted-sync/src/metrics.rs
Since validation can produce an invalid payload attributes to compare to the derived payload attributes (eg when calling `debug_getRawTransaction`, empty tx bytes are returned when they are in fact _not_ empty), we want to retry payload validation a few times before actually recording the **derived** payload attributes as invalid.
There have been multiple instances where this has thrown an alert, without the derived payload attributes being invalid, but instead the validation payload attributes were constructed incorrectly.
Also adds a `trusted_sync_validation_retries` metric that tracks the total number of retries.
> fix(examples): Invalid Payload Retries With Backoff

- crates/derive/src/online/blob_provider.rs
- crates/derive/src/online/mod.rs
- crates/derive/src/online/pipeline.rs
- examples/trusted-sync/src/cli.rs
- examples/trusted-sync/src/main.rs
Added a fallback online blob provider in the form of `OnlineBlobProviderWithFallback`.
It will first try to fetch blobs from the primary provider, and proceed with the fallback one if the primary fails.
I added the `BlobSidecarProvider` trait because blob archive APIs aren't required to implement all functions contained in `BeaconClient` (as is the case for https://github.com/base-org/blob-archiver). Furthermore, `genesis_time` and `slot_interval` are taken from the primary provider which is already an online beacon client.
Would something like a `BlobArchiver` struct implementation be useful? 
I'm not sure if that should be left to the caller or to the library.
**Tests**
Added unit tests to make sure that blob fetching is completed even without any sidecar loaded in the …
> feat(derive+trusted-sync): online blob provider with fallback

- examples/trusted-sync/src/main.rs
Fixes `trusted-sync` not to `.expect` errors in the main loop.
> fix(trusted-sync): Remove Panics

- bin/client/src/l1/driver.rs
This PR makes `DerivationDriver` generic over the `BlobProvider` used by extending `OracleDataProvider` with a generic type parameter that replaces the previous `OracleBlobProvider` parameterization. This allows `DerivationDriver` to be instantiated with custom structs that implement the required `BlobProvider` trait.
**Tests**
The existing tests for the ecotone and fjord blocks pass. No tests were added, and no behavior was changed.
> feat(client): Generic DerivationDriver over any BlobProvider

- bin/host/src/fetcher/mod.rs
When importing `kona-host` into different repositories, the Rust compiler isn't smart enough to infer the types from `hint_data[32..40].as_ref().try_into()`.
I've explicitly set the types, which ensures the Rust compiler no longer complains.
This leads to errors such as this:
```bash
error[E0282]: type annotations needed
--> /Users/ratankaliani/.cargo/git/checkouts/kona-e1a00085bb036f5b/e069eb4/bin/host/src/fetcher/mod.rs:166:22
|
166 |                     .as_ref()
|                      ^^^^^^
167 |                     .try_into()
|                      -------- type must be known at this point
|
help: try using a fully qualified path to specify the expected types
|
165 |                 let hash: B256 = <[u8] as AsRef<T>>::as_ref(&hint_data[0..32])
| …
```
> fix(kona-host): set explicit types

- .github/workflows/coverage.yaml
- Cargo.lock
- Cargo.toml
- bin/host/src/fetcher/mod.rs
- crates/executor/src/eip4788.rs
- crates/executor/src/lib.rs
- crates/mpt/src/db/mod.rs
`revm` recently released a new version [v13](https://github.com/bluealloy/revm/releases/tag/v41) which contains great work from @BrianBland implementing the granite hard fork in revm.
This PR updates the version of `revm` to `13.0.*`.
> chore(deps): Bump revm version to v13

- Cargo.lock
- crates/derive/src/stages/channel_bank.rs
- crates/primitives/Cargo.toml
- examples/trusted-sync/Cargo.toml
> [!NOTE]
>
> Blocked by [superchain-registry#440](https://github.com/ethereum-optimism/superchain-registry/pull/440)
Updates the kona derivation pipeline to use the updated `superchain-primitives` and `superchain-registry` with the granite hardfork.
> fix(derive): Granite Hardfork Support

- crates/derive/src/stages/channel_reader.rs
- examples/trusted-sync/src/main.rs
> chore(examples): Add logs to trusted-sync

- crates/derive/src/pipeline/mod.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/stages/test_utils/attributes_queue.rs
- crates/derive/src/stages/test_utils/batch_queue.rs
- crates/derive/src/stages/test_utils/channel_bank.rs
- crates/derive/src/stages/test_utils/channel_reader.rs
- crates/derive/src/stages/test_utils/frame_queue.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/stages.rs
Removes the `PreviousStage` trait which is a relic from the reference derivation pipeline implementation where resetting stages needed to occur sequentially and the node driver needs to "walk back" the stages, resetting each one individually.
**Metadata**
Fixes #406
> chore(derive): Remove PreviousStage Trait

- .github/workflows/program_diff.yaml
- crates/derive/src/types/batch/mod.rs
Adds differential testing in CI between `op-program + cannon` and `asterisc + kona`.
It is currently scheduled to run every 12 hours, on the hour.
> feat(ci): Add scheduled FPP differential tests

- bin/host/src/fetcher/mod.rs
- bin/host/src/server.rs
Backs off the prefetching job after a `MAX_RETRY` parameter.
> fix(host): Backoff after `MAX_RETRIES`

- bin/client/src/fault/caching_oracle.rs
- bin/client/src/fault/mod.rs
- bin/client/src/fault/precompiles/bn128_pair.rs
- bin/client/src/fault/precompiles/ecrecover.rs
- bin/client/src/fault/precompiles/kzg_point_eval.rs
- bin/client/src/fault/precompiles/mod.rs
- bin/client/src/kona.rs
- bin/client/src/l2/mod.rs
- bin/client/src/lib.rs
- bin/host/src/kv/local.rs
Isolates the FPVM-specific constructs in the `kona-client` library, only exporting items that are re-usable for different backends.
> chore(client): Isolate FPVM-specific constructs

- crates/common-proc/src/lib.rs
Suppresses the missing docs warning in the `#[client_entry]` macro expansion.
> chore(common-proc): Suppress doc warning

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/test_utils/channel_bank.rs
Adds a test to the channel bank for channel timeout on OP mainnet & Base Mainnet rollup configs.
> test(derive): Channel timeout

- Cargo.lock
- bin/client/Cargo.toml
- bin/client/src/boot.rs
- bin/host/Cargo.toml
- bin/host/src/cli/mod.rs
- bin/host/src/kv/local.rs
> [!WARNING]
> This feature is _not safe_ for production unless additional validation is performed, i.e. committing to the `RollupConfig` that the user must provide in the verifier contract. Do not use dynamic `RollupConfig` loading unless you understand the implications of an underconstrained `RollupConfig` being passed into the program from the host.
Introduces the option to dynamically load the `RollupConfig` through the `BootInfo` in the bootloader phase of the program. This allows for running `kona` on devnets and alternative chains that are not present in the `superchain-registry`.
cc @zobront
> feat(client+host): Dynamic `RollupConfig` in bootloader

- Cargo.lock
- crates/primitives/Cargo.toml
- examples/trusted-sync/Cargo.toml
- Bumps the `superchain-registry` dependency to [`0.2.6`](https://crates.io/crates/superchain-registry).
- Bumps the `superchain-primitives` dependency to [`0.2.2`](https://crates.io/crates/superchain-primitives).
> chore: Bump SCR to 0.2.6

- .github/workflows/fixtures.yaml
- Cargo.lock
- bin/kdn/Cargo.toml
- bin/kdn/src/blobs.rs
- bin/kdn/src/cli.rs
- bin/kdn/src/lib.rs
- bin/kdn/src/pipeline.rs
- bin/kdn/src/providers.rs
- bin/kdn/src/runner.rs
- justfile
Updates `kdn` to use the generic `DerivationFixture` with local `kona-derive` types.
Sets up a github action to run derivation tests on pr into trunk.
**Metadata**
Closes #442
> fix(kdn): Updates `kdn` with op-test-vectors Generic Typing

- crates/derive/README.md
Removes legacy broken fpvm link in `kona-derive` README.
> fix(derive): Remove FPVM Tests in README

- bin/client/src/caching_oracle.rs
- bin/client/src/fault/mod.rs
- bin/client/src/kona.rs
- bin/client/src/lib.rs
Exports the `CachingOracle` without exporting the underlying pipes.
Expansions of kona, i.e. `op-succinct`, still use this construct.
> feat(client): Export `CachingOracle`

- Cargo.lock
- Cargo.toml
- crates/executor/Cargo.toml
- crates/primitives/src/block.rs
Switches to use the published `revm` version rather than a git pin, so that we can use `kona-mpt` + `reth-evm-optimism` in `opt8n`.
Also unblocks our releases, as we can't release w/ git deps.
> fix(workspace): Use published `revm` version

- crates/primitives/src/block_info.rs
Adds a conditional `Serialize + Deserialize` implementation for `L1BlockInfoTx`.
> feat(primitives): `serde` for `L1BlockInfoTx`

- .github/workflows/coverage.yaml
- .github/workflows/rust_ci.yaml
- Cargo.lock
- crates/derive/Cargo.toml
- justfile
Removes unused dependencies from `kona-derive` and reorganizes the `test-utils` deps such that they are not included in the default dist.
> chore(derive): Remove udeps

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- crates/derive/Cargo.toml
- crates/executor/Cargo.toml
- crates/mpt/Cargo.toml
- crates/mpt/src/db/mod.rs
- crates/mpt/src/test_util.rs
- crates/primitives/Cargo.toml
- crates/primitives/src/sidecar.rs
- examples/trusted-sync/Cargo.toml
- justfile
Bumps the versions for alloy dependencies as well as revm.
Fixes kzg setting use where revm removed the `G1_POINTS` and `G2_POINTS` exports and instead uses the new [`EnvKzgSettings`](https://github.com/bluealloy/revm/blob/3085f04ac6b144e7ac721abce9cbbf538ff6b7fe/crates/primitives/src/kzg.rs#L7) construct.
> chore(workspace): Alloy Version Bumps

- .github/codecov.yml
Configures the codecov patch job to only run on pull requests, + raises required coverage to 75%.
> chore(ci): Configure codecov patch job

- bin/client/src/l1/driver.rs
Breaks the `produce_disputed_payload` loop if the pipeline cannot advance. This needs more investigation wrt. alternative errors being "temporary," but does address current issues with not haulting derivation upon critical errors.
> fix(client): Break when the pipeline cannot advance

- justfile
Remove the `--all` flag that is deprecated in favor of `--workspace`.
> fix: Deprecate All Flag

- bin/host/src/fetcher/mod.rs
Inserts the empty MPT root hash in `store_trie_nodes` if the `nodes` array passed is empty. The `HashBuilder` will not push the preimage of the empty root hash to the `ProofRetainer` if the `nodes` arr is empty.
fixes #399
> fix(host): Insert empty MPT root hash

- .github/workflows/rust_ci.yaml
- crates/derive/Cargo.toml
- justfile
Adds a step to `cargo hack` the workspace.
> feat: Run cargo hack against workspace

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/fetcher/mod.rs
- bin/host/src/kv/disk.rs
- bin/host/src/kv/local.rs
- bin/host/src/kv/mem.rs
- bin/host/src/kv/mod.rs
- bin/host/src/kv/split.rs
Updates the disk K/V store to use [`rocksdb`](https://github.com/facebook/rocksdb). The old method was extremely inefficient on iops and compression. While the disk-backed K/V store isn't really in the hot path, having a more compression-friendly format is very convenient for testing.
> feat(host): Use `RocksDB` as the disk K/V store

- crates/mpt/src/list_walker.rs
Supports empty lists in the `OrderedListWalker`. Re-post of #491, where CI is broken for external contributors due to the `PAT_TOKEN` reference.
> fix(mpt): Empty list walker

- .github/workflows/release.yaml
- .github/workflows/rust_ci.yaml
Removes the `PAT_TOKEN` requirement, which should re-enable CI for external contributors.
> fix(ci): Remove `PAT_TOKEN` ref

- build/asterisc/asterisc-repro.dockerfile
Updates the asterisc + kona prestate builder image to include the `kona-host` binary at the `CLIENT_TAG`.
> chore(docker): Update prestate builder image

- bin/host/src/fetcher/mod.rs
Consumers of `kona-host` run into cargo type annotation issues. Similar to https://github.com/anton-rs/kona/pull/421.
There must be a way to catch this in `kona`, but after some preliminary testing, I couldn't find an easy fix.
> chore(kona-host): type annotations

- Cargo.lock
- bin/host/Cargo.toml
- bin/host/src/kv/disk.rs
Adds a `TryFrom<DiskKeyValueStore` for the `MemoryKeyValueStore`.
cc @ratankaliani
> feat(host): Add `TryFrom<DiskKeyValueStore>` for `MemoryKeyValueStore`

- bin/host/src/kv/mem.rs
Consumers of `kona` such as `op-succinct` need access to the underlying store for operations like zero-copy serialization. 
Specifically, `alloy-primitives` doesn't derive `rkyv`'s macros on types, and to reduce the cycle count for reading data into the zkVM, we convert the store keys from `B256` to `[u8; 32]`, which we can then serialize/deserialize with `rkyv`.
> feat: expose `MemoryKeyValueStore` store

- justfile
Defaults the prestate artifacts build to the `amd64` platform.
> chore(release): Default to `amd64` platform on prestate artifacts build

- .github/workflows/kona_fpp_docker.yaml
- build/asterisc/asterisc-repro.dockerfile
Adds a job to release the prestate build image.
> feat(ci): Release prestate build image

- bin/client/src/kona.rs
- bin/host/src/lib.rs
- bin/host/src/main.rs
Exits the host program with the client program's status when running in native mode. This ensures that test suites that execute the client program natively can inspect the error that occurred, between `0` (CLAIM_VALID), `1` (CLAIM_INVALID), `2` (PANIC)
closes #527
> feat(host): Exit with client status in native mode

- .gitignore
- justfile
Adds a `justfile` recipe for running the `op-e2e` action tests against `kona`. These aren't in CI yet as we're not passing all of them.
> feat(workspace): Action test runner

- crates/derive/src/stages/batch_queue.rs
Fixes sequence window expiry in `kona-derive`. Previously it was checking the wrong L1 origin to decide whether or not `force_empty_batches` was active.
> fix(derive): Sequence window expiry

- .github/workflows/action_tests.yaml
- justfile
Runs the `op-e2e` FPP action tests against `kona-client` in CI.
> feat(ci): Add action tests to CI

- bin/host/src/server.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/lib.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/traits.rs
Improves the differentiation of errors in the preimage server routes. This allows for us to throw on non-pipe related errors, rather than silently fail and assume that the exit is related to a broken pipe.
Also fixes an edge case where if the `HintReaderServer` receives bad UTF-8, it will block forever.
> fix(preimage): Improve error differentiation in preimage servers

- bin/host/Cargo.toml
- bin/host/README.md
- bin/host/src/cli/mod.rs
- bin/host/src/cli/tracing_util.rs
- bin/host/src/lib.rs
- bin/host/src/main.rs
Cleans up the host CLI validation by using the native features of the `clap::arg` proc macro over a custom validation function. Also adjusts some of the flag docs to be a bit more helpful.
and, colors, because it's kind of cool 🎨
> chore: clean up host CLI

- Cargo.lock
- Cargo.toml
Remove `op-alloy` crates.io patches since `v0.2.12` is published that removes the dependency on `superchain-primitives`.
> chore: Remove crates io patch

- bin/host/Cargo.toml
- bin/host/README.md
- bin/host/src/cli/mod.rs
- bin/host/src/cli/tracing_util.rs
- bin/host/src/lib.rs
- bin/host/src/main.rs
Re-open of #536, accidentally merged into downstack branch.
> chore(host): clean up CLI

- bin/client/src/l1/driver.rs
- crates/derive/src/stages/channel_reader.rs
Fixes the error handling in the channel reader setting logic to start passing action tests again.
> fix(client): Channel reader error handling

- Cargo.lock
- bin/client/src/fault/handler/mod.rs
- bin/client/src/kona.rs
- bin/client/src/l1/chain_provider.rs
- bin/client/src/l1/driver.rs
- bin/client/src/l2/chain_provider.rs
- crates/executor/benches/execution.rs
- crates/executor/src/builder.rs
- crates/executor/src/canyon.rs
- crates/executor/src/lib.rs
- crates/mpt/Cargo.toml
- crates/mpt/benches/trie_node.rs
- crates/mpt/src/db/mod.rs
- crates/mpt/src/errors.rs
- crates/mpt/src/fetcher.rs
- crates/mpt/src/lib.rs
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/mpt/src/test_util.rs
Migrates `kona-mpt` to typed errors.
> feat(mpt): Migrate to `thiserror`

- .github/workflows/client_host.yaml
- Cargo.toml
- bin/client/justfile
Bumps the MSRV to `1.81`, as we now rely on `core::error::Error`
> chore(workspace): Bump MSRV to `1.81`

- Cargo.lock
- bin/client/src/caching_oracle.rs
- bin/client/src/l1/chain_provider.rs
- bin/client/src/l2/chain_provider.rs
- bin/host/src/preimage.rs
- bin/host/src/server.rs
- crates/common/Cargo.toml
- crates/common/src/asterisc/io.rs
- crates/common/src/cannon/io.rs
- crates/common/src/cannon/syscall.rs
- crates/common/src/errors.rs
- crates/common/src/io.rs
- crates/common/src/lib.rs
- crates/common/src/linux.rs
- crates/common/src/traits/basic.rs
- crates/common/src/zkvm/io.rs
- crates/preimage/Cargo.toml
- crates/preimage/src/errors.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/key.rs
- crates/preimage/src/lib.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/pipe.rs
- crates/preimage/src/test_utils.rs
- crates/preimage/src/traits.rs
Migrates `kona-preimage` & `kona-common` to `thiserror`.
> feat(preimage/common): Migrate to `thiserror`

- Cargo.lock
- bin/client/src/kona.rs
- crates/executor/Cargo.toml
- crates/executor/benches/execution.rs
- crates/executor/src/builder.rs
- crates/executor/src/canyon.rs
- crates/executor/src/eip4788.rs
- crates/executor/src/errors.rs
- crates/executor/src/lib.rs
Migrates `kona-executor` to `thiserror`
> feat(executor): Migrate to `thiserror`

- bin/client/src/kona.rs
- bin/client/src/l1/driver.rs
Applies a fix to the client program's derivation driver, where it threw if a block execution failed. This case can be hit in the event that a malicious batcher posts a bad batch on L1 mainnet.
This change makes us pass the new action tests.
> fix(client): Continue derivation on execution failure

- crates/common/src/io.rs
- crates/common/src/lib.rs
- crates/executor/src/lib.rs
- crates/mpt/src/lib.rs
- crates/mpt/src/test_util.rs
- crates/preimage/src/hint.rs
- crates/preimage/src/lib.rs
- crates/preimage/src/oracle.rs
- crates/preimage/src/test_utils.rs
Allows use of `std` in `cfg(test)` without the use of `extern crate std`.
> chore(workspace): Allow stdlib in `cfg(test)`

- Cargo.lock
- Cargo.toml
- crates/preimage/src/key.rs
Bumps all workspace dependencies, except for `c-kzg`. To update `c-kzg` to v2, alloy will also need to update.
> chore(workspace): Bump dependencies

- README.md
Removes the link to the old `kona-plasma` plugin within the README. It was removed from the codebase until further notice in https://github.com/anton-rs/kona/pull/443.
> chore(readme): Remove `kona-plasma` link

- crates/derive/src/errors.rs
- crates/derive/src/pipeline/mod.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/attributes_queue/builder.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/stages/test_utils/attributes_queue.rs
- crates/derive/src/traits/attributes.rs
- crates/derive/src/traits/mod.rs
Hoists the `AttributesBuilder` trait to allow the attributes builder to be moved easier in up-stack prs.
> fix(derive): Hoist AttributesBuilder Trait

- crates/derive/src/stages/batch_stream.rs
- crates/derive/src/stages/mod.rs
Adds a new `BatchStream` stage for holocene.
Makes progress towards #559
> feat(derive): New BatchStream Stage for Holocene

- Cargo.lock
- bin/client/src/l1/driver.rs
- crates/derive/src/online/pipeline.rs
- crates/derive/src/pipeline/builder.rs
Wires up the `BatchStream` stage into pipeline instantiations.
Makes progress on #559.
> feat(derive): BatchStream Stage Wiring

- crates/derive/src/pipeline/builder.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/test_utils/frame_queue.rs
Implements the Holocene FrameQueue.
Closes #557.
> feat(derive): Holocene Frame Queue

- .github/workflows/rust_ci.yaml
- Cargo.lock
- crates/derive/src/metrics.rs
- crates/derive/src/stages/channel_bank.rs
Adds checks to the `ChannelBank` for post-holocene strict ordering that only one channel may only be buffered at a given point in time within the channel queue.
Closes #558
> feat(derive): Holocene Channel Bank Checks

- Cargo.lock
- bin/client/src/l1/driver.rs
- crates/derive/src/online/pipeline.rs
- crates/derive/src/pipeline/builder.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/batch_stream.rs
- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/test_utils/batch_queue.rs
Small PR to add buffer flushing to the batch stream.
> feat(derive): Holocene Buffer Flushing

- .github/workflows/rust_ci.yaml
- crates/mpt/src/list_walker.rs
- justfile
Splits the tests that require a network connection within the `justfile` test directives.
Locally, when running `just t`, `just tests`, or `just test`, the online tests (tests that start w/ `test_online`) are no longer ran by default.
A new justfile recipe, `just test-online` has been added to run the online tests.
> feat(ci): Split online/offline tests

- justfile
```
[01:34] 🦀 v1.81.0 cl@kona:main [$]
 just lint
error: Justfile does not contain recipe `lint`.
```
is my mortal enemy. Adds a `just lint` alias for `just lint-native`.
> chore(workspace): `just lint`

- crates/derive/src/stages/frame_queue.rs
Drains the entire previous channel at one time, rather than over multiple iterations, if the following case is met:
> If a first frame is decoded while the previous frame isn't a last frame (i.e., is_last is false), all previous frames for the same channel are dropped and this new first frame remains in the queue.
Also fixes a small issue w/ the `DERIVED_FRAMES_COUNT` metric's accounting, where it was counting dropped frames.
Added a new test for this functionality, when there is a valid, closed channel earlier on in the frame queue @ `test_holocene_replace_channel`.
> chore(derive): [Holocene] Drain previous channel in one iteration

- Cargo.lock
- Cargo.toml
- crates/derive/Cargo.toml
- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/test_utils/sys_config_fetcher.rs
- crates/derive/src/traits/test_utils.rs
Removes the `hashbrown` dependency, using the [recently introduced `map` primitive](https://github.com/alloy-rs/core/pull/743) in [`alloy-primitives`](https://github.com/alloy-rs/core/tree/main/crates/primitives).
> chore: Alloy Map

- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/batch_stream.rs
- crates/derive/src/stages/channel_reader.rs
Implements the rest of the `BatchStream`, buffering the span batch that is received and sending only `SingleBatch`es to the batch queue.
> feat(derive): `BatchStream` buffering

- bin/client/src/l1/driver.rs
- crates/derive/src/batch/mod.rs
- crates/derive/src/batch/span_batch/batch.rs
- crates/derive/src/pipeline/builder.rs
- crates/derive/src/stages/batch_stream.rs
- crates/providers-alloy/src/pipeline.rs
Adds the checks for the span batch prefix.
> feat(derive): Span batch prefix checks

- .github/workflows/action_tests.yaml
Pins the version of the `monorepo` we use for action tests in CI.
> chore(ci): Pin action tests monorepo rev

- crates/derive/src/batch/validity.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/test_utils/batch_queue.rs
Updates the `BatchQueue` for Holocene.
Closes #560
> feat(derive): BatchQueue Update [Holocene]

- Cargo.lock
- bin/client/src/l1/driver.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/traits/mod.rs
- crates/derive/src/traits/pipeline.rs
- examples/trusted-sync/Cargo.toml
- examples/trusted-sync/src/main.rs
Adds the notion of a `Signal` to the pipeline, with a `FlushChannel` variant for Holocene.
> feat(derive): Add `Signal` API

- crates/executor/src/lib.rs
Adds support for using the EIP-1559 parameters from the `PayloadAttributes` in the block executor after holocene.
> feat(executor): Use EIP-1559 parameters from payload attributes

- Cargo.lock
- examples/trusted-sync/Cargo.toml
- examples/trusted-sync/src/main.rs
Attempts to re-validate a payload with a deposit-only payload in `trusted-sync`, per Holocene fork rules.
> feat(trusted-sync): Holocene re-validate

- Cargo.lock
- crates/derive/src/attributes/mod.rs
- crates/derive/src/batch/span_batch/batch.rs
- crates/derive/src/sources/ethereum.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/batch_stream.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/traits/test_utils.rs
- crates/providers-alloy/Cargo.toml
- crates/providers-alloy/src/pipeline.rs
- crates/providers/Cargo.toml
- crates/providers/src/lib.rs
- crates/providers/src/test_utils.rs
Increases test coverage, refactoring test utilities.
> chore: Test Utils

- .github/codecov.yml
Fixes codecov to ignore all test utilities.
Also bumps the threshold up to 80 since we should not see regression > 3%
> fix(codecov): Ignore Test Utilities

- crates/derive/src/sources/blobs.rs
- crates/derive/src/traits/test_utils.rs
Adds test coverage to the blob provider source.
> chore(derive): Blob Source Test Coverage

- .github/codecov.yml
- crates/providers-alloy/src/alloy_providers.rs
Ignore codecov for alloy providers and beacon client. Tests still run in CI. We ought to still increase coverage but until a test utility exists for the inner provider type, we will see flaky results in CI.
> chore(providers): Codecov Ignore Alloy-backed Providers

- .github/CODEOWNERS
Adds a `CODEOWNERS` to the repo so owners are automatically requested for review.
> chore: Codeowners

- bin/host/src/cli/mod.rs
- bin/host/src/fetcher/mod.rs
- crates/providers-alloy/src/blob_provider.rs
- crates/providers-alloy/src/lib.rs
- crates/providers-alloy/src/pipeline.rs
Removes the `SlotDerivation` trait and inlines the `SimpleSlotDerivation` method into the `OnlineBlobProvider`. If it becomes needed elsewhere, we can refactor down the road to pull it out of the `OnlineBlobProvider` into it's own type without specifying it as a generic.
Closes #632
> fix(providers): Remove Slot Derivation

- Cargo.lock
- Cargo.toml
- crates/providers-alloy/src/beacon_client.rs
- crates/providers-alloy/src/blob_provider.rs
Patches the `BlobTransactionSidecarItem` to use `u64` with proper serde support.
A bunch of kzg verification tests are failing now though...
> patch: Blob Item Type for Serde

- crates/mpt/src/db/account.rs
Small PR to add test coverage across mpt account conversion utils.
> chore(mpt): Account Conversion Test Coverage

- crates/executor/src/lib.rs
Updates `kona-executor`'s implementation of configurable EIP-1559 parameters, per the specification update in https://github.com/ethereum-optimism/specs/pull/418.
Instead of using the parameters within the payload for the current block, we use the parameters encoded in the parent block header (or the canyon constants, if the parent header's nonce == 0). When encoding the parameters for placing in the header, we use the `eip1559Params` within the payload (or the canyon constants, if payload.eip1559Params == 0).
> feat(executor): Update EIP-1559 configurability

- .github/codecov.yml
- crates/mpt/src/fetcher.rs
- crates/mpt/src/lib.rs
- crates/mpt/src/node.rs
- crates/mpt/src/noop.rs
Moves noop impls into a `noop.rs` module that is now ignored by codecov.
Replaces #645
> chore(mpt): mpt noop trait impls

- crates/derive/src/stages/channel_bank.rs
- crates/derive/src/stages/test_utils/channel_bank.rs
Adds test coverage over the channel bank reset.
> chore(derive): Channel Bank Reset Test Coverage

- crates/derive/src/stages/channel_reader.rs
- crates/derive/src/stages/test_utils/channel_reader.rs
Small PR to add test coverage over `ChannelReader` resets.
> chore(derive): Test Coverage for ChannelReader Resets

- crates/derive/src/stages/channel_bank.rs
Adds test coverage over the `ChannelBank::try_read_channel_at_index` method.
> chore(derive): Covers ChannelBank Reading at Indices

- crates/derive/src/stages/channel_reader.rs
Small PR to add test coverage over the `ChannelReader` flushes.
> chore(derive): Test ChannelReader Flushing

- crates/executor/src/util.rs
Adds test coverage over utilities.
> chore(executor): Test Coverage over Executor Utilities

- bin/client/src/boot.rs
- bin/client/src/kona.rs
- bin/client/src/l1/driver.rs
- bin/client/src/l2/chain_provider.rs
Improves the names of the fields within `BootInfo` for clarity.
> chore(client): Improve `BootInfo` field names

- bin/client/justfile
- bin/host/src/cli/mod.rs
- bin/host/src/kv/local.rs
- bin/host/src/lib.rs
Improves the names of the CLI flags in `kona-host`. Old CLI flags are still retained as aliases for backwards compatibility with existing scripts that execute `kona-host`, i.e. for OP succinct and in the op-challenger.
> chore(host): Improve CLI flag naming

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/batch_stream.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/stages/test_utils/batch_queue.rs
- crates/derive/src/stages/test_utils/batch_stream.rs
- crates/derive/src/stages/test_utils/frame_queue.rs
- crates/derive/src/test_utils/stages/attributes_queue.rs
Tests stage resets and flushing.
> chore(derive): Test Stage Resets and Flushes

- .github/workflows/monorepo_pin_update.yaml
Reduces the frequency of the `monorepo` update auto-PR to once every 14 days. Right now it fires off every 2 days, which isn't really needed. The action tests don't update that frequently.
also moves to use the repository secret for posting PRs, similar to the `release-plz` workflow
> chore(ci): Reduce monorepo auto-update frequency

- bin/host/src/cli/mod.rs
> [!NOTE]
> Depends on #666 
>
> need `st` to remove this warning 😢 
Allows for CLI flags to be passed as environment variables in `kona-host`. Some CLI flags are excluded from this:
* `-v[vvvv]`
* `--exec`
* `--server`
mostly because these explicitly select the mode that the host runs in, or for trace verbosity, doesn't really make sense to define within the environment.
> chore(host): Support environment variables for `kona-host` flags

- Cargo.lock
- Cargo.toml
- crates/mpt/Cargo.toml
- crates/mpt/src/node.rs
Uses [`derive_more::Display`](https://docs.rs/derive_more/latest/derive_more/derive.Display.html) in `kona-mpt` to auto-derive display.
> feat(mpt): Auto derive Display

- crates/executor/src/lib.rs
Removes testing todo in executor in favor of a ticket: https://github.com/anton-rs/kona/issues/679
Part of an effort to remove all TODO comments from kona.
> chore(executor): Removes TODO in Executor

- crates/derive/src/batch/span_batch/batch.rs
`TODO` comments have been upstreamed to this issue: https://github.com/anton-rs/kona/issues/681
> chore(derive): Remove Span Batch TODOs

- crates/derive/src/stages/batch_queue.rs
Retains `l1_blocks` in the `BatchQueue` when flushing. We cannot flush this list at will, and instead have to have these L1 origins consumed as the sequencer epoch advances.
> fix(derive): Retain L1 blocks

- crates/derive/src/batch/single_batch.rs
- crates/derive/src/batch/span_batch/batch.rs
- crates/derive/src/batch/validity.rs
- crates/derive/src/errors.rs
- crates/derive/src/stages/batch_queue.rs
- crates/derive/src/stages/batch_stream.rs
Adds a new variant to the `BatchValidity` enum that activates with Holocene. When a batch is outdated, after Holocene, the `Past` variant is returned. In the `BatchQueue`, this instructs a silent drop, _without_ flushing the active span batch and channel.
We should follow this PR up with removing the additional check within `add_batch`, deferring to the validity checks in `derive_next_batch`.
> feat(derive): `Past` batch validity variant

- bin/host/src/fetcher/mod.rs
Micro-pr to remove the last `// TODO:` comment.
> chore: Removes the last TODO

- bin/host/src/kv/disk.rs
Reduces the number of proptest runs for the disk<->mem KV conversion. This test takes a long time to run locally.
> chore(host): Reduce disk<->mem KV proptest runs

- bin/client/src/l1/chain_provider.rs
- bin/client/src/l2/mod.rs
- book/src/fpp-dev/env.md
- book/src/sdk/fpvm-backend.md
- crates/mpt/src/test_util.rs
> fix: typos

- crates/derive/src/stages/channel/channel_assembler.rs
> [!NOTE]
> Needs #702 
Adds tracing to the `ChannelAssembler stage.
> chore(derive): Add tracing to `ChannelAssembler`

- crates/derive/src/stages/channel/channel_assembler.rs
> [!NOTE]
> Needs #702 
Adds a check for maximum channel size to the `ChannelAssembler` stage, which enforces that the channel being built never exceeds `MAX_RLP_BYTES_PER_CHANNEL`. This update is according to the recent update to the Holocene spec [here](https://github.com/ethereum-optimism/specs/pull/431)
Closes #698
> feat(derive): Add `ChannelAssembler` size limitation

- crates/mpt/src/node.rs
Adds coverage for the case where the root node of an MPT is the empty root hash. The previous behavior could cause a bug if an account storage root was cleared out entirely from a previously populated value during the execution of a block.
This ensures that, if the root is empty, the empty root hash is returned by `blinded_commitment`.
closes #704
> fix(mpt): Empty root node case

- .github/codecov.yml
Bumps the CODECOV threshold to 90%
> feat: Bump Codecov Threshold 

- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/ethereum.rs
- crates/derive/src/sources/variant.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/test_utils/blob_provider.rs
- crates/derive/src/test_utils/data_availability_provider.rs
- crates/derive/src/test_utils/mod.rs
- crates/derive/src/test_utils/pipeline.rs
- crates/derive/src/traits/mod.rs
Hoists test utilities from inside `kona_derive::traits::test_utils` module to the top-level `kona_derive::test_utils` module.
> chore(derive): Hoist Test Utilities

- Cargo.lock
- Cargo.toml
- bin/client/Cargo.toml
- bin/client/src/l2/chain_provider.rs
- bin/host/Cargo.toml
- crates/common-proc/Cargo.toml
- crates/common/Cargo.toml
- crates/derive/Cargo.toml
- crates/derive/src/batch/span_batch/batch.rs
- crates/derive/src/stages/batch_queue.rs
- crates/executor/Cargo.toml
- crates/mpt/Cargo.toml
- crates/preimage/Cargo.toml
- crates/providers-alloy/Cargo.toml
- crates/providers/Cargo.toml
Cleans up the workspace.
- Removes features from workspace-level imports and moves them to crates.
- Deletes unused crates in the top-level workspace manifest.
- Fixes the missing `Requests` field in the [`alloy_consensus::BlockBody`](https://docs.rs/alloy-consensus/0.5.2/alloy_consensus/struct.BlockBody.html)
> chore: Workspace Cleanup

- bin/client/src/fault/handler/bn128_pair.rs
- bin/client/src/fault/handler/mod.rs
- crates/executor/src/errors.rs
- crates/executor/src/lib.rs
- crates/executor/src/util.rs
Updates `kona-executor` to be in-line with the new spec, using `extraData` rather than `nonce` to store the EIP-1559 parameters post-holocene.
ref spec: [here](https://specs.optimism.io/protocol/holocene/exec-engine.html#dynamic-eip-1559-parameters)
closes #697
> feat(executor): EIP-1559 configurability spec updates

- Cargo.lock
- Cargo.toml
- crates/providers-alloy/Cargo.toml
- crates/providers-alloy/src/beacon_client.rs
- crates/providers-alloy/src/blob_provider.rs
- crates/providers-alloy/src/lib.rs
- crates/providers-alloy/src/test_utils.rs
Re-uses the beacon types from `alloy-rpc-types-beacon` instead of custom api response types.
> fix(providers-alloy): Recycle Beacon Types

- crates/derive/src/errors.rs
- crates/derive/src/stages/batch/batch_queue.rs
- crates/derive/src/stages/batch/batch_stream.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/stages/batch/mod.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/test_utils/batch_queue.rs
Adds a new stage to take place of the `BatchQueue` after Holocene activation, the `BatchValidator`. This stage's only role is to consume the `SingleBatch`es from the `BatchStream`, validate them, and send them off to the `AttributesQueue`.
This PR does not hook this stage up to a multiplexer stage with the `BatchQueue`, and that will be done in a follow-up.
> feat(derive): `BatchValidator` stage

- Cargo.lock
- Cargo.toml
Bumps the recently updated alloy release to the `0.5.2` patch.
> chore: Dependency Updates

- Cargo.lock
- crates/derive/src/stages/channel/channel_assembler.rs
- crates/derive/src/stages/channel/channel_bank.rs
- crates/derive/src/stages/channel/channel_provider.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/test_utils/frames.rs
- crates/derive/src/test_utils/macros.rs
- crates/derive/src/test_utils/mod.rs
Cleans up `FrameQueue` testing by creating an assertion utility and convenience frame macros.
I think we ought to clean up testing by building test utils in the top level `kona_derive::test_utils` module such that unit tests next to implementations are lean and concise. This way, `kona_derive` isn't littered with a bunch of `test_utils` modules nested in various sub-modules, but one comprehensive module at the top level, that can be placed behind the `test-utils` feature flag.
> feat(derive): Frame Queue Asserter 

- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch/batch_queue.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/stages/mod.rs
- crates/derive/src/test_utils/attributes_queue.rs
- crates/derive/src/traits/attributes.rs
- crates/derive/src/traits/mod.rs
Hoists `AttributesQueue` traits.
Hoisting stage providers to the traits module tidies up the dependency list across stages and makes the separation clearer.
Replaces #599
> feat(derive): Hoist Attributes Queue Provider Trait

- .github/workflows/kona_fpp_docker.yaml
- build/asterisc/asterisc-repro.dockerfile
- justfile
Updates the `asterisc` reproducible build image to allow for building both an image and the artifacts tar.
> feat(docker): Update asterisc reproducible build image

- .github/workflows/client_host.yaml
- bin/client/justfile
- build/asterisc/asterisc-repro.dockerfile
Updates the workspace's version of `asterisc` to `v1.0.3-alpha1`. This release contains the radix trie memory changes, which we need to start testing against.
> chore(workspace): Update `asterisc` version to `1.0.3-alpha1`

- Cargo.lock
- Cargo.toml
- bin/client/src/l2/chain_provider.rs
Updates `op-alloy` dependencies to their `0.5.1` patch release.
Ref: https://github.com/alloy-rs/op-alloy/pull/184
> chore(deps): op-alloy 0.5.1

- Cargo.lock
- Cargo.toml
- crates/common/Cargo.toml
- crates/common/src/errors.rs
- crates/derive-alloy/Cargo.toml
- crates/derive-alloy/src/test_utils.rs
- crates/derive/Cargo.toml
- crates/derive/src/batch/span_batch/errors.rs
- crates/derive/src/errors.rs
- crates/derive/src/test_utils/chain_providers.rs
- crates/executor/Cargo.toml
- crates/executor/src/errors.rs
- crates/mpt/Cargo.toml
- crates/mpt/src/errors.rs
- crates/preimage/Cargo.toml
- crates/preimage/src/errors.rs
Completely removes the [`thiserror`](https://github.com/dtolnay/thiserror) dependency, allowing us to publish our crates. Instead of deriving the [`core::error::Error`](https://doc.rust-lang.org/beta/core/error/trait.Error.html) type, we manually implement along with using [`derive_more::Display`](https://docs.rs/derive_more/latest/derive_more/derive.Display.html).
> feat: Remove thiserror

- crates/mpt/Cargo.toml
- crates/mpt/src/test_util.rs
This PR resolves compilation issues in the `kona-mpt` crate by adding `reqwest` feature, and other small fixes
> fix: tests in `kona-mpt`

- bin/host/src/fetcher/mod.rs
Doesn't throw a hard error if the prefetch operation fails, but retries it and notifies the logs of the failure.
> feat(host): Ensure prefetch is falliable

- crates/derive/src/batch/span_batch/batch.rs
- crates/derive/src/stages/batch/batch_queue.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/stages/channel/channel_assembler.rs
- crates/derive/src/stages/channel/channel_bank.rs
This PR provides fix for tracing_subscriber initialization at `kona-derive` tests.
command to reproduce:
```
cd crates/derive; cargo test 
```
the result:
```
---- batch::span_batch::batch::tests::test_check_batch_exceeds_sequencer_time_drift stdout ----
thread 'batch::span_batch::batch::tests::test_check_batch_exceeds_sequencer_time_drift' panicked at .cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.18/src/util.rs:91:14:
failed to set global default subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")
...
test result: FAILED. 216 passed; 34 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.02s
```
with this fix:
```
test result: ok. 250 passed; 0 failed; 1 ignored; 0 measured; 0 filtered out; finished in 0.05s …
```
> fix: tracing_subscriber problem in `kona-derive` tests

- .github/workflows/coverage.yaml
- .github/workflows/rust_ci.yaml
Changes the test jobs in CI such that they don't run the online tests. These tests are very flaky now that our test RPC has started to rate-limit.
> chore(ci): Don't run `online` tests in CI

- Cargo.lock
- Cargo.toml
Updates `op-alloy-*` dependencies to `v0.5.2`.
> chore(workspace): Update op-alloy Deps

- bin/client/src/l1/driver.rs
- justfile
Fixes a bug caused by shadowing the `executor` variable when retrying a deposit-only payload execution post-Holocene. This bug was caught with the Holocene action tests.
> fix(client): Remove `executor` shadow in FCU retry

- .github/workflows/action_tests.yaml
- justfile
Uses `gotestsum` for action tests CI. This makes the `stdout` stream of the job much, much smaller, which should speed up the job in the happy path. If a test fails, `gotestsum` will print the verbose output of _just_ the test(s) that fail.
> chore(ci): Use `gotestsum` for action test job

- crates/derive-alloy/CHANGELOG.md
Small PR to fix the `kona-derive-alloy` `CHANGELOG` so release-plz doesn't keep overwriting changes.
> fix(derive-alloy): changelog

- bin/client/src/l1/driver.rs
- crates/derive/src/errors/attributes.rs
- crates/derive/src/errors/mod.rs
- crates/derive/src/errors/pipeline.rs
- crates/derive/src/errors/sources.rs
- crates/derive/src/errors/stages.rs
- crates/derive/src/lib.rs
- crates/derive/src/pipeline/builder.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/pipeline/mod.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/stages/batch/mod.rs
- crates/derive/src/stages/channel/channel_assembler.rs
- crates/derive/src/stages/channel/mod.rs
- crates/derive/src/test_utils/pipeline.rs
Small PR to clean up error types and re-exports in `kona-derive`.
> chore(derive): Error Exports

- crates/derive/README.md
Small PR to touchup the README for `kona-derive`.
> chore(derive): README Touchups

- crates/derive-alloy/README.md
- crates/derive-alloy/src/lib.rs
Small PR adding docs to `kona-derive-alloy`.
> chore(derive-alloy): Docs

- crates/executor/src/executor/mod.rs
- crates/executor/src/executor/util.rs
Small PR to use the upstream receipt constructor in `op-alloy` added in https://github.com/alloy-rs/op-alloy/pull/165
> chore(executor): Remove Upstream Utility

- .github/workflows/monorepo_pin_update.yaml
Uses the `PAT_TOKEN` secret for updating the monorepo pin. This is because [github does not run workflows with `GITHUB_TOKEN`](https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#using-the-github_token-in-a-workflow)
> chore(ci): Use `PAT_TOKEN` for automated monorepo pin update

- .github/workflows/client_host.yaml
Bumps the `asterisc` version to `v1.1.0`. This is in preparation for a new alpha release, which will distribute the prestate created with the `asterisc-v1.1.0` binary.
> chore(ci): Bump `asterisc` version

- .monorepo
Temporarily updates the monocommit to @geoknee's branch, which includes the Holocene action tests. Once these are merged, we can go back to a commit sha on `develop`'s tree.
> chore(ci): Update monorepo pin to include Holocene action tests

- bin/client/src/l1/driver.rs
- crates/derive-alloy/src/blob_provider.rs
- crates/derive/src/errors/sources.rs
- crates/derive/src/sources/blobs.rs
- crates/derive/src/test_utils/blob_provider.rs
- crates/derive/src/traits/data_sources.rs
Enforces that the `BlobProvider` trait impls use an `Error` type that can be converted to `PipelineErrorKind`.
> feat(derive): `From<BlobProviderError> for PipelineErrorKind`

- bin/client/src/l1/driver.rs
- book/src/sdk/pipeline/providers.md
- crates/derive-alloy/README.md
- crates/derive-alloy/src/pipeline.rs
- crates/derive/src/sources/blob_data.rs
- crates/derive/src/sources/blob_hash.rs
- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/sources/ethereum.rs
- crates/derive/src/sources/mod.rs
- crates/derive/src/stages/l1_retrieval.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/derive/src/test_utils/data_availability_provider.rs
- crates/derive/src/test_utils/mod.rs
- crates/derive/src/traits/data_sources.rs
- crates/derive/src/traits/mod.rs
Fixes `kona-derive`'s data availability abstraction to remove the `AsyncIterator` and make the abstraction much simpler.
This allows the concrete implementation for Ethereum to handle how calldata <> blob source dispatch is done without binding the behavior to a trait abstraction that other users of `kona-derive` don't need.
> fix(derive): Data Availability Provider Abstraction

- Cargo.lock
- bin/client/src/l1/chain_provider.rs
- bin/client/src/l2/chain_provider.rs
- crates/executor/benches/execution.rs
- crates/executor/src/executor/mod.rs
- crates/mpt/Cargo.toml
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/mpt/src/noop.rs
- crates/mpt/src/test_util.rs
- crates/mpt/src/traits.rs
This PR refactors the `TrieProvider` to change the the method for fetching trie node data into one that provides `TrieNode` instances instead of raw rlp-encoded bytes:
**Before**
```rust
fn trie_node_preimage(&self, key: B256) -> Result<Bytes, Self::Error>;
```
**After**
```rust
fn trie_node_by_hash(&self, key: B256) -> Result<TrieNode, Self::Error>;
```
This allows `TrieProvider` implementations to abstract away the details of how the required instance can be created and authenticated (i.e. through RLP decoding pre-image oracle answers on-demand or otherwise). This is useful for providing entire trees as query answers, instead of single nodes with blinded children.
> feat(TrieProvider): Abstract TrieNode retrieval

- Cargo.lock
- Cargo.toml
- bin/client/src/l1/blob_provider.rs
- bin/host/Cargo.toml
- bin/host/src/fetcher/mod.rs
- crates/derive-alloy/src/alloy_providers.rs
- crates/derive-alloy/src/beacon_client.rs
- crates/derive-alloy/src/blob_provider.rs
- crates/derive-alloy/src/test_utils.rs
- crates/derive/Cargo.toml
- crates/derive/src/sources/blob_hash.rs
- crates/derive/src/sources/blobs.rs
- crates/derive/src/sources/calldata.rs
- crates/derive/src/sources/mod.rs
- crates/derive/src/test_utils/blob_provider.rs
- crates/derive/src/traits/data_sources.rs
- crates/mpt/src/test_util.rs
> Revert "chore: Bump Alloy Deps"

- bin/client/src/l1/pipeline.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/traits/pipeline.rs
- crates/driver/src/core.rs
- crates/driver/src/lib.rs
- crates/driver/src/pipeline.rs
Abstracts the driver pipeline trait to allow for a default payload production loop.
Avoids driver implementors from footgunning themselves with rolling their own payload loops.
> feat(driver): Abstract, Default Pipeline

- Cargo.lock
- bin/client/src/kona.rs
- bin/client/src/l1/pipeline.rs
- bin/client/src/lib.rs
- bin/client/src/sync.rs
- crates/driver/src/cursor.rs
Refactors the sync start out of the pipeline construction.
> fix(client): SyncStart Refactor

- bin/client/src/kona.rs
- bin/client/src/l1/pipeline.rs
- bin/client/src/sync.rs
- crates/driver/src/core.rs
- crates/driver/src/cursor.rs
- crates/driver/src/lib.rs
- crates/driver/src/tip.rs
Refactors the `SyncStart` into a new `PipelineCursor` that tracks the state of the driver.
> feat(driver,client): Pipeline Cursor Refactor

- .github/workflows/book.yaml
Touches up the kona book workflow to allow for manual dispatches
> chore: Dispatch book build without cache

- book/src/sdk/pipeline/providers.md
This book update was forgotten in this [PR](https://github.com/anton-rs/kona/pull/782/files#r1840230844)
> docs: update providers.md to use new next method instead of old open_data

- Cargo.lock
- Cargo.toml
- bin/client/Cargo.toml
- bin/client/src/errors.rs
- crates/common/Cargo.toml
- crates/common/src/errors.rs
- crates/derive/Cargo.toml
- crates/derive/src/errors/attributes.rs
- crates/derive/src/errors/pipeline.rs
- crates/derive/src/errors/sources.rs
- crates/derive/src/errors/stages.rs
- crates/derive/src/test_utils/attributes_queue.rs
- crates/derive/src/test_utils/chain_providers.rs
- crates/derive/src/test_utils/sys_config_fetcher.rs
- crates/driver/Cargo.toml
- crates/driver/src/errors.rs
- crates/executor/Cargo.toml
- crates/executor/src/errors.rs
- crates/mpt/Cargo.toml
- crates/mpt/src/errors.rs
- crates/mpt/src/node.rs
- crates/preimage/Cargo.toml
- crates/preimage/src/errors.rs
- crates/preimage/src/key.rs
Migrates all crates back to `thiserror`, now that `>=v2.0.0` has support for `no_std` with `default-features = false`.
closes #806
> chore(workspace): Migrate back to `thiserror` v2

- bin/client/src/executor.rs
- bin/client/src/fault/handler/mod.rs
- bin/client/src/l1/chain_provider.rs
- bin/client/src/l2/chain_provider.rs
- bin/client/src/sync.rs
- crates/common/src/io.rs
- crates/executor/benches/execution.rs
- crates/executor/src/db/mod.rs
- crates/executor/src/db/traits.rs
- crates/executor/src/executor/builder.rs
- crates/executor/src/executor/env.rs
- crates/executor/src/executor/mod.rs
- crates/executor/src/lib.rs
- crates/executor/src/syscalls/canyon.rs
- crates/executor/src/syscalls/eip4788.rs
- crates/mpt/Cargo.toml
- crates/mpt/README.md
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/mpt/src/noop.rs
- crates/mpt/src/test_util.rs
- crates/mpt/src/traits.rs
Cleans up the leaky `TrieProvider` abstraction by extending the `TrieProvider` trait with the added functionality it needs to back a database rather than just a merkle patricia trie.
The `TrieProvider` trait served by `kona-mpt` now has a much simpler interface, just fetching trie node preimages.
> feat(mpt): Extend `TrieProvider` in `kona-executor`

- crates/mpt/src/node.rs
This aim of this PR is to remove a very subtle yet unused `unblind` call to prevent access to unused trie nodes. Such additional access, while having minor performance impact, prevents the delegation of execution witness generation to external clients that retrieve the minimum required trie nodes, such as [zeth](https://github.com/risc0/zeth).
The PR modifies `collapse_if_possible` to avoid attempting to collapse the blinded child of an extension node. The reason is that because we assume the trie is correctly constructed prior to any execution, there is no need to unblind the child of the extension (which must be a branch) to attempt further collapse, because the execution did not unblind this child already and therefore did not perform any reads/writes to it.
> nit(mpt): Remove unnecessary `collapse_if_possible` call

- Cargo.lock
- crates/driver/src/core.rs
- crates/driver/src/lib.rs
- crates/driver/src/pipeline.rs
Adopts a nice pattern from reth to use tracing macros, removing the need to specify the dep each time.
> chore(driver): Macro use tracing

- book/src/sdk/custom-backend.md
EDIT: this might be in a few places. Just realized its also in the other page: https://anton-rs.github.io/kona/sdk/exec-ext.html
> docs: fix typo in custom-backend.md

- crates/derive/src/lib.rs
- crates/derive/src/pipeline/core.rs
- crates/derive/src/sources/blobs.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch/batch_queue.rs
- crates/derive/src/stages/batch/batch_stream.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/stages/channel/channel_assembler.rs
- crates/derive/src/stages/channel/channel_bank.rs
- crates/derive/src/stages/channel/channel_reader.rs
- crates/derive/src/stages/frame_queue.rs
- crates/derive/src/stages/l1_traversal.rs
- crates/driver/src/core.rs
- crates/driver/src/cursor.rs
- crates/driver/src/executor.rs
- crates/executor/src/db/mod.rs
- crates/executor/src/executor/mod.rs
- crates/executor/src/lib.rs
- crates/proof-sdk/preimage/src/hint.rs
- crates/proof-sdk/preimage/src/lib.rs
- crates/proof-sdk/preimage/src/oracle.rs
- crates/proof-sdk/proof/src/boot.rs
- crates/proof-sdk/proof/src/lib.rs
Applies the `macro_use` with `tracing` across the workspace, less binaries.
> chore(workspace): macro use tracing

- bin/client/src/lib.rs
- crates/proof-sdk/proof/src/sync.rs
Adds a check into the fault proof program entrypoint that invalidates any claims where the claimed L2 block number is < the safe L2 head's block number.
The short-circuit check for trace extension, if agreed == disputed, is preserved.
> feat(client): Invalidate impossibly old claims

- crates/driver/src/core.rs
- crates/driver/src/executor.rs
- crates/proof-sdk/proof/src/executor.rs
Adds support for the waiting for the engine to be ready.
> chore(driver): Wait for Engine

- bin/host/src/fetcher/mod.rs
- crates/executor/src/syscalls/canyon.rs
with alloy::map we need to be a bit careful with which hashmap functions we are using because some fns enforce certain hashers.
for example `From` is only implemented for `Randomstate`, which itself calls `from_iter` which only enforces ` S: BuildHasher + Default,`
> fix: use non problematic hashmap fns

- Cargo.toml
- build/asterisc/asterisc-repro.dockerfile
Bumps the MSRV to 1.83, since we're using some features that were unstable in 1.81
> feat(workspace): Bump MSRV

- .github/workflows/kona_fpp_docker.yaml
Adds a task for publishing the `kona-fpp` image on multiple platforms (`linux/arm64` + `linux/amd64`).
> chore(ci): Distribute `linux/arm64` `kona-fpp` image

- .gitignore
- bin/client/justfile
Needed to target a devnet which doesnt have a standard chain_id. Might need to make the same change for the offline client target as well?
We use this to test the client against the docker devnet in op's monorepo:
```
run-client-native-against-devnet verbosity='' block_number='' rollup_config_path='':
#!/usr/bin/env bash
L1_RPC="http://127.0.0.1:8545"
L1_BEACON_RPC="http://127.0.0.1:5052"
L2_RPC="http://127.0.0.1:9545"
ROLLUP_NODE_RPC="http://127.0.0.1:7545"
ROLLUP_CONFIG_PATH="../../../optimism/.devnet/rollup.json"
if [ -z "{{block_number}}" ]; then
BLOCK_NUMBER=$(cast block finalized --json --rpc-url $L2_RPC | jq -r .number | cast 2d)
else
BLOCK_NUMBER={{block_number}}
fi
just run-client-native $BLOCK_NUMBER \
$L1_RPC $L1_BEACON_RPC $L2_RPC $ROLLUP_NODE_RPC \
$ROLLUP_CONFIG_PATH …
```
> tooling: make client justfile's commands take an optional rollup_config_path

- Cargo.toml
- build/asterisc/asterisc-repro.dockerfile
- crates/derive/src/attributes/stateful.rs
- crates/derive/src/stages/batch/batch_validator.rs
`is_none_or` is stable as of Rust 1.82, while the RISC Zero zkvm toolchain is currently using 1.81
This patch introduces more verbose code to bring the MSRV back down to 1.81 to avoid compiling with unstable features.
Generally it would also be great if Kona could have an MSRV policy set (e.g. MSRV is always at least 2 versions behind) to help avoid these issues.
> chore: Reduce MSRV

- crates/derive/Cargo.toml
On main, running `cargo check -p kona-derive --tests` did not work, since the `std` feature for tracing was not enabled in tests. This enables tracing's `std` feature when it's a dev dependency.
> fix(derive): make tests compile

- README.md
- bin/client/justfile
- build/asterisc/asterisc-repro.dockerfile
- build/asterisc/asterisc.dockerfile
- crates/proof-sdk/std-fpvm/src/riscv64/mod.rs
- justfile
> [!NOTE]
> I validated locally that this target works out fine for running on asterisc, but will need to cut a release of the `asterisc-builder` cross compilation image for this to pass CI. Will do after vaca.
>
> For anyone who wants to experiment with this, head over to the `build` dir, and build the asterisc image locally w/ `just asterisc`. Then, head over to the root `justfile`, and adjust the `build-asterisc` recipe to use the local `asterisc-pipeline:latest` image that was built in the previous step.
>
> Once this is done, head over to `bin/client`, and run kona on asterisc w/ `just run-client-asterisc` to use the new `riscv64ima` binary.
>
> **e: A new image was manually published. This is good to go.**
Adjusts the build pipeline to use `riscv64imac-unknown-none-elf` as the …
> feat(build): Adjust RV target - `riscv64g` -> `riscv64ima`

- build/asterisc/asterisc-repro.dockerfile
Bumps the version of the `asterisc-builder` cross-compilation image in the `asterisc-repro` image, in preparation for the release.
> feat(build): Bump `asterisc-builder` version in repro image

- crates/executor/src/executor/mod.rs
Updates kona's stateless block executor to set the withdrawals root to the L2 to L1 message passer account when isthmus is active.
Specs: https://specs.optimism.io/protocol/isthmus/exec-engine.html#l2tol1messagepasser-storage-root-in-header
> chore: Isthmus Withdrawals Root

- .github/CODEOWNERS
Updates the github codeowners to include @emhane
> chore: Add emhane as a CODEOWNER

- crates/derive/src/sources/calldata.rs
Tests that EIP-7702 transactions are skipped by the derivation pipeline.
Replaces #886
> chore(derive): Test Ignoring EIP-7702

- book/src/sdk/exec-ext.md
Fixes a small spelling issue in the docs.
> fix: Small Spelling Issue

- crates/derive/src/pipeline/core.rs
- crates/driver/src/pipeline.rs
Closes #896
Refactors logging around some `PipelineErrorKind::TemporaryError`s to be lower level than WARN.
> Move temporary error logs to lower level than WARN

- Cargo.lock
- Cargo.toml
- README.md
- crates/interop/Cargo.toml
- crates/interop/README.md
- crates/interop/src/constants.rs
- crates/interop/src/errors.rs
- crates/interop/src/graph.rs
- crates/interop/src/lib.rs
- crates/interop/src/message.rs
- crates/interop/src/super_root.rs
- crates/interop/src/test_util.rs
- crates/interop/src/traits.rs
Adds the initial version of the `kona-interop` crate, containing core types for interop (messages, `SuperRoot`, message graph) as well as core functionality for extracting messages from logs + resolving a set of interdependent blocks' validity per [message validity rules](https://specs.optimism.io/interop/messaging.html#invalid-messages).
This crate should eventually live over in `maili`, but it's subject to change while the initial interop proof is being laid out, so it's easier for it to live in `kona` for the first phase of its life.
> feat(workspace): `kona-interop` crate

- Cargo.lock
- bin/client/src/interop/consolidate.rs
- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/host/src/interop/fetcher.rs
- crates/interop/src/errors.rs
- crates/interop/src/graph.rs
- crates/interop/src/lib.rs
- crates/interop/src/super_root.rs
- crates/interop/src/test_util.rs
- crates/interop/src/traits.rs
- crates/proof-sdk/proof-interop/Cargo.toml
- crates/proof-sdk/proof-interop/src/hint.rs
- crates/proof-sdk/proof-interop/src/lib.rs
- crates/proof-sdk/proof-interop/src/provider.rs
- crates/proof-sdk/proof/src/errors.rs
- crates/proof-sdk/proof/src/l1/chain_provider.rs
Implements the happy-path variant of the consolidation sub-problem for the interop FPP.
This will be followed up with a larger overhaul that allows for re-executing the optimistic blocks with deposits only, in the case where dependencies were found to be invalid.
> feat(client): Interop consolidation sub-problem

- Cargo.lock
- crates/executor/Cargo.toml
- crates/executor/benches/execution.rs
Removes `anyhow` as a dev-dependency of `kona-executor`
closes https://github.com/op-rs/kona/issues/920
> chore(executor): Remove `anyhow` dev-dependency

- crates/executor/src/executor/mod.rs
If Isthmus is enabled, pass empty SHA-256 hash as the requests root. Checked that this matches op-geth when passing in an empty array.
Wasn't totally sure where to put the constant for empty sha-256, but let me know if I should move it.
Spec: https://eips.ethereum.org/EIPS/eip-7685#block-header
Fixes https://github.com/op-rs/kona/issues/949
> feat: use empty requests hash when isthmus enabled

- docker/README.md
Touches up the new docker docs to provide troubleshooting for the multi-platform docker build error.
> chore(docker): Small Doc Touchup

- README.md
Adds [`kailua`](https://github.com/risc0/kailua) as a project that uses `kona` to the readme. A bit late, but they've done great work!
> chore(docs): Add `kailua` to the README

- crates/proof-sdk/preimage/src/key.rs
This PR derives Eq/Ord/Hash implementations for the (Archived) PreimageKey(Type) struct, enabling its usage in more collections.
> feat: Derive Eq/Ord/Hash for (Archived) PreimageKey(Type)

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/interop/cli.rs
- bin/host/src/interop/orchestrator.rs
- crates/derive/Cargo.toml
- crates/derive/src/pipeline/core.rs
- crates/derive/src/stages/attributes_queue.rs
- crates/derive/src/stages/batch/batch_queue.rs
- crates/derive/src/test_utils/chain_providers.rs
- crates/derive/src/test_utils/pipeline.rs
- crates/derive/src/test_utils/sys_config_fetcher.rs
- crates/derive/src/traits/attributes.rs
- crates/derive/src/traits/pipeline.rs
- crates/driver/Cargo.toml
- crates/driver/src/core.rs
- crates/driver/src/pipeline.rs
- crates/executor/src/executor/mod.rs
- crates/interop/src/test_util.rs
- crates/proof-sdk/proof-interop/src/provider.rs
- crates/proof-sdk/proof/Cargo.toml
- crates/proof-sdk/proof/src/l1/pipeline.rs
- crates/proof-sdk/proof/src/l2/chain_provider.rs
- crates/providers-alloy/src/l2_chain_provider.rs
Once Isthmus is active, we should allow 7702 receipts. Fixes #909
> feat: allow 7702 receipts after Isthmus active

- Cargo.lock
- crates/executor/src/executor/env.rs
- crates/executor/src/executor/mod.rs
Fills tx env for EIP 7702 transactions using the same format as EIP 1559, but with authorization list added.
Fixes #948 
TODO: do we need a switch for Isthmus here? Or is it OK to be active all the time - guessing the batcher shouldn't include 7702 txs until Isthmus is active?
> feat: fill eip 7702 tx env with auth list

- Cargo.lock
- Cargo.toml
Bumps `maili` crates to `0.1.9` which contains support for EIP-7702 span batch transactions.
Closes #945
> chore: Maili 0.1.9

- crates/executor/src/executor/env.rs
Updates the `revm` `SpecId` with `Isthmus`.
Closes #947.
> chore(executor): Update SpecId with Isthmus

- Cargo.lock
- crates/executor/src/executor/mod.rs
- crates/executor/src/syscalls/eip2935.rs
- crates/executor/src/syscalls/mod.rs
The `Isthmus` hardfork introduces the [EIP-2935](https://eips.ethereum.org/EIPS/eip-2935) contract to serve historical block hashes from state.
This PR adds support to kona's executor to syscall the contract.
Makes progress on #950
> feat(executor): EIP-2935 Syscall Support [ISTHMUS]

- Cargo.lock
- crates/executor/src/executor/mod.rs
- crates/executor/src/syscalls/eip7002.rs
- crates/executor/src/syscalls/mod.rs
Adds support for EIP-7002 as part of the Isthmus Hardfork.
Makes progress on #950
> feat(executor): EIP-7002 Syscall Support [ISTHMUS]

- crates/executor/src/executor/mod.rs
- crates/executor/src/syscalls/eip7251.rs
- crates/executor/src/syscalls/mod.rs
Adds support to Kona's executor for the EIP-7251 syscall for Isthmus.
Makes progress on #950
> feat(executor): EIP-7251 Syscall Support [ISTHMUS]

- crates/executor/src/syscalls/eip2935.rs
- crates/executor/src/syscalls/eip4788.rs
- crates/executor/src/syscalls/eip7002.rs
- crates/executor/src/syscalls/eip7251.rs
- crates/executor/src/syscalls/mod.rs
- crates/executor/src/syscalls/tx_env.rs
Fixes tx env stuffing in the executor contract calls.
Closes #950
> chore(executor): TxEnv Stuffing

- crates/executor/src/db/mod.rs
- crates/executor/src/executor/mod.rs
Fixes the withdrawals root feature of Isthmus. It's not currently enabled, but there was also a logic flaw where it fetched the L2ToL1MessagePasser's storage root for the parent block, not the current block.
> fix(executor): Withdrawals root

- bin/client/src/interop/transition.rs
- bin/client/src/single.rs
- crates/driver/src/core.rs
Small fix to the interop transition step, where:
1. No-op transitions were wrongfully rejected.
2. The validity of the claimed timestamp wasn't checked.
> fix(client): Interop transition rules

- Cargo.lock
- Cargo.toml
- crates/derive/src/test_utils/frame_queue.rs
- crates/interop/src/super_root.rs
- crates/mpt/benches/trie_node.rs
- crates/mpt/src/list_walker.rs
- crates/mpt/src/node.rs
- crates/proof-sdk/proof-interop/src/pre_state.rs
- crates/proof-sdk/std-fpvm/src/channel.rs
> chore: Dep Updates

- Cargo.lock
- Cargo.toml
- crates/derive/src/test_utils/frame_queue.rs
- crates/executor/Cargo.toml
- crates/executor/src/executor/env.rs
- crates/executor/src/executor/mod.rs
- crates/mpt/src/list_walker.rs
- crates/proof-sdk/std-fpvm/src/channel.rs
De-duplicates the spec id helper.
Closes #971
> chore: De-duplicate SpecId Helper

- Cargo.lock
- bin/client/src/interop/consolidate.rs
- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/client/src/interop/util.rs
- bin/client/src/single.rs
- bin/host/src/interop/fetcher.rs
- bin/host/src/interop/local_kv.rs
- crates/interop/Cargo.toml
- crates/interop/src/super_root.rs
- crates/proof-sdk/proof-interop/Cargo.toml
- crates/proof-sdk/proof-interop/src/boot.rs
- crates/proof-sdk/proof-interop/src/pre_state.rs
- crates/proof-sdk/proof/src/l2/chain_provider.rs
Adds support for loading multiple `RollupConfig`s into the client program during the boot routine.
closes https://github.com/op-rs/kona/issues/985
> feat(proof-interop): Support multiple `RollupConfigs` in boot routine

- Cargo.lock
- Cargo.toml
- bin/host/src/eth/mod.rs
- bin/host/src/interop/fetcher.rs
- bin/host/src/interop/orchestrator.rs
- bin/host/src/single/fetcher.rs
- bin/host/src/single/orchestrator.rs
- crates/executor/src/test_utils.rs
- crates/providers-alloy/src/chain_provider.rs
- crates/providers-alloy/src/l2_chain_provider.rs
Updates alloy to `0.11.0`, op-alloy to `0.10.0` and maili to `0.2.0`.
> chore: Update Dependencies

- bin/client/src/interop/util.rs
- bin/client/src/precompiles/bls12.rs
- bin/client/src/precompiles/bn128_pair.rs
- bin/client/src/precompiles/ecrecover.rs
- bin/client/src/precompiles/kzg_point_eval.rs
- bin/client/src/single.rs
- bin/host/src/interop/handler.rs
- bin/host/src/single/handler.rs
- crates/proof-sdk/proof-interop/src/boot.rs
- crates/proof-sdk/proof-interop/src/hint.rs
- crates/proof-sdk/proof-interop/src/provider.rs
- crates/proof-sdk/proof/src/hint.rs
- crates/proof-sdk/proof/src/l1/blob_provider.rs
- crates/proof-sdk/proof/src/l1/chain_provider.rs
- crates/proof-sdk/proof/src/l2/chain_provider.rs
Cleans up the hint sending API to allow for a nice builder pattern, over the previous method of constructing the raw encoded hint and sending it directly to the `HintWriterClient`.
**Old**:
```rs
self.oracle
.write(&HintType::L2AccountStorageProof.encode_with(&[
block_number.to_be_bytes().as_ref(),
address.as_slice(),
slot.to_be_bytes::<32>().as_ref(),
]))
.await
.map_err(OracleProviderError::Preimage)
```
**New**:
```rs
HintType::L2AccountStorageProof
.with_data(&[
block_number.to_be_bytes().as_ref(),
address.as_slice(),
slot.to_be_bytes::<32>().as_ref(),
])
.send(self.oracle.as_ref())
.await
````
> feat(proof-sdk): Cleanup `Hint` API

- bin/client/src/interop/transition.rs
- bin/host/src/interop/cfg.rs
- bin/host/src/interop/handler.rs
- crates/proof-sdk/proof/src/hint.rs
- crates/proof-sdk/proof/src/l2/chain_provider.rs
Adds support for the client program optionally sending an L2 chain ID with hints to specify which L2 provider to use.
closes https://github.com/op-rs/kona/issues/987
> feat(proof-sdk): Optional L2 chain ID in L2-specific hints

- bin/host/src/interop/cfg.rs
- bin/host/src/interop/handler.rs
Reintroduces the `L2BlockData` hint to the interop host. This was removed temporarily during the refactor, but is now supported by the L2 chain ID in all hints feature.
> feat(host): Reintroduce `L2BlockData` hint

- bin/client/src/interop/mod.rs
- bin/host/src/interop/cfg.rs
- bin/host/src/interop/handler.rs
- crates/proof-sdk/proof-interop/src/boot.rs
- crates/proof-sdk/proof-interop/src/lib.rs
- crates/proof-sdk/proof-interop/src/pre_state.rs
- crates/proof-sdk/proof/src/hint.rs
Contains some small bugfixes for the interop proof.
> fix(client): Interop bugfixes

- bin/client/src/precompiles/bls12_g1_msm.rs
- bin/client/src/precompiles/bls12_g2_msm.rs
- bin/client/src/precompiles/mod.rs
- bin/client/src/precompiles/utils.rs
Small cleanup PR to dedup the MSM required gas calculation utility method.
This will need to be removed and revm's utility used once it's made public in the next revm release.
> chore(client): Dedup MSM Required Gas Fn

- bin/client/src/precompiles/bls12_g1_add.rs
- bin/client/src/precompiles/bls12_g1_msm.rs
- bin/client/src/precompiles/bls12_g2_add.rs
- bin/client/src/precompiles/bls12_g2_msm.rs
- bin/client/src/precompiles/bls12_map_fp.rs
- bin/client/src/precompiles/bls12_map_fp2.rs
- bin/client/src/precompiles/bls12_pairing.rs
- bin/client/src/precompiles/bn128_pair.rs
- bin/client/src/precompiles/ecrecover.rs
- bin/client/src/precompiles/kzg_point_eval.rs
- bin/client/src/precompiles/utils.rs
Introduces a new `precompile_run` macro that rips out the highly duplicated logic across accelerated precompiles.
> chore(client): Precompile Run Macro

- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/client/src/interop/util.rs
- crates/proof-sdk/proof-interop/src/boot.rs
- crates/proof-sdk/proof-interop/src/pre_state.rs
Fixes the logic for no-op'ing sub-transitions within the Superchain STF. The superchain STF happens once every second, regardless of if each individual chain within
the dependency set has actually progressed. In this case, we need to be able to short-circuit sub-problem #1.
> fix(client): No-op sub-transitions in Superchain STF

- .github/workflows/action_tests.yaml
- .github/workflows/client_host.yaml
- .github/workflows/rust_ci.yaml
Bumps the `codecov-action` to v5, which contains a fix for tokenless uploads in forks.
> chore(ci): Bump `codecov-action` to v5

- Cargo.lock
- Cargo.toml
Bumps `maili` dependencies to `0.2.3`.
> chore(deps): Bump Maili -> `0.2.3`

- .github/workflows/action_tests.yaml
- .github/workflows/book.yaml
- .github/workflows/client_host.yaml
- .github/workflows/monorepo_pin_update.yaml
- .github/workflows/release.yaml
- .github/workflows/rust_ci.yaml
- .vscode/settings.json
- bin/host/src/single/cfg.rs
- crates/derive/src/attributes/stateful.rs
- crates/derive/src/stages/batch/batch_validator.rs
- crates/derive/src/test_utils/frame_queue.rs
- crates/interop/src/super_root.rs
- crates/mpt/src/list_walker.rs
- crates/proof-sdk/proof-interop/src/consolidation.rs
- crates/proof-sdk/proof/src/l2/chain_provider.rs
- crates/proof-sdk/std-fpvm/src/channel.rs
- justfile
- rust-toolchain.toml
Currently in `kona`, the CI runs with the latest stable toolchain.
This allows for features stabilized after the latest MSRV (e.g. https://github.com/rust-lang/rust/pull/129195) to be used, which causes crates such as OP Succinct to fail to compile. This is because SP1's Rust toolchain (as well as other zkVM Rust toolchains) are not always up to date with the latest stable Rust toolchain, though they're above the MSRV in `kona`, which is currently set to 1.81.
- Update CI to use the MSRV toolchain (1.81).
- Add a `rust-toolchain.toml` file, which ensures during local development that the MSRV toolchain is used.
- Update functions to reflect the fact that `const_mut_refs` is not stabilized.
- Set `clippy` in `justfile` to use stable, instead of nightly. `fmt` should still use nightly for …
> feat(ci): Remove support for features after MSRV

- book/book.toml
Adds a `description` and `build-dir` to the book for the [`devdocs`](https://github.com/ethereum-optimism/devdocs) aggregator.
> chore(book): adherance to devdocs

- book/book.toml
Defines the build directory as `kona` to deploy to the `kona` subdir in [`devdocs`](https://github.com/ethereum-optimism/devdocs)
> chore(book): Devdocs subdirectory

- crates/interop/src/graph.rs
- crates/interop/src/message.rs
Fixes the implementation to check against a subtle note in the spec, where:
> The timestamp at the time of inclusion of the initiating message MUST be less than or equal to **the timestamp of the executing message** as well as greater than or equal to the Interop Start Timestamp.
> fix(interop): Check timestamp invariant against executing timestamp AND horizon timestamp

- bin/host/src/single/cfg.rs
This PR changes the visibility of the following `SingleChainHost ` methods to public:
* `create_key_value_store`
* `create_providers`
This enables their reuse by Kailua.
> chore(host): expose private SingleChainHost methods

- Cargo.lock
- Cargo.toml
- book/src/sdk/pipeline/intro.md
- crates/protocol/interop/src/graph.rs
- crates/services/net/Cargo.toml
- crates/services/net/README.md
- crates/services/net/src/builder.rs
- crates/services/net/src/discovery/bootnodes.rs
- crates/services/net/src/discovery/builder.rs
- crates/services/net/src/discovery/driver.rs
- crates/services/net/src/discovery/mod.rs
- crates/services/net/src/driver.rs
- crates/services/net/src/gossip/behaviour.rs
- crates/services/net/src/gossip/config.rs
- crates/services/net/src/gossip/driver.rs
- crates/services/net/src/gossip/event.rs
- crates/services/net/src/gossip/handler.rs
- crates/services/net/src/gossip/mod.rs
- crates/services/net/src/lib.rs
- crates/services/net/src/types/enr.rs
- crates/services/net/src/types/mod.rs
- crates/services/net/src/types/peer.rs
- crates/services/providers-alloy/Cargo.toml
- justfile
Ports the P2P networking crate from hilo to kona.
> chore(services): Networking Crate

- bin/host/src/interop/handler.rs
The original code attempted to convert a byte slice to B256 using:
```rust
let hash: B256 = hint.data[..32].as_ref().try_into()?;
```
However, this resulted in the following error due to missing type inference when I ran `cargo clippy --all-features --all-targets -- -D warnings -A incomplete-features` in [op-succinct](https://github.com/succinctlabs/op-succinct) repo:
```
error[E0282]: type annotations needed
--> /Users/fakedev9999/.cargo/git/checkouts/kona-eb08956031b8bea7/cef9b87/bin/host/src/interop/handler.rs:300:50
|
300 |                 let hash: B256 = hint.data[..32].as_ref().try_into()?;
|                                                  ^^^^^^   -------- type must be known at this point
|
help: try using a fully qualified path to specify the expected types
|
300 | …
```
> fix: fix type annotations

- docker/fpvm-prestates/asterisc-repro.dockerfile
Excludes `kona-net` so the asterisc builder works
> fix: Exclude kona-net

- .github/workflows/book.yaml
- book/src/SUMMARY.md
- book/src/archives/intro.md
- book/src/rfc/intro.md
- book/src/rfc/monorepo.md
Moves the monorepo doc to the new RFC section.
Also introduces a new archives section that will be used to
hold documents like RFC documents once they are implemented
or otherwise no longer living.
> chore(book): RFC and Archives Section

- Cargo.lock
- bin/client/justfile
- docker/cannon/mips64-unknown-none.json
Diffs
- Update ruint dep to v1.13.1 (most recent)
- Patch cannon's build config to target mips64r1 on docker build.
- Patch justfile for testing kona on cannon.
Cannon with kona works with mips64r1 with the ruint patch in kona and DCLZ support for cannon. 
Tests
- Confirmed that local docker buildx build for cannon works
- Built kona on mips64r1
- Ran cannon(which supports DCLZ) with kona and validated offline host-client testing
> feat(client): support cannon mips64r1

- crates/proof/std-fpvm/src/channel.rs
- justfile
Fixes the lint routine for the `cannon-builder` image. These images use the nightly toolchain, rather than the MSRV, to build.
Also loosens the requirements for the build images' platforms, since they're now distributed as cross-platform builds. Rejoice, Apple laptop users :D
> fix(std-fpvm): Allow non-const fn with mut ref

- Justfile
Fixes the `Justfile` targets to use the correct `crates/protocol/registry` crate path.
> fix(ci): Submodule Sync Crate Path

- README.md
- RELEASES.md
Ports the release guide from [maili](https://github.com/op-rs/maili).
> docs: Release Guide

- Cargo.lock
- Justfile
- scripts/check_no_std.sh
Adds a small helper target to the `Justfile` to grab the foundry version from `mise.toml` in the monorepo and install that version using `foundryup -i`.
> chore(workspace): Foundry Install Target

- Cargo.lock
- Cargo.toml
- crates/protocol/protocol/src/errors.rs
- crates/protocol/protocol/src/utils.rs
Releasing maili shadow crates currently fails since the `cargo metadata` command will error.
This PR explicitly excludes the maili shadows in the workspace manifest to allow releases.
> fix(workspace): Exclude Maili Shadows

- crates/external/net/src/gossip/config.rs
- crates/protocol/genesis/src/chain/config.rs
- crates/protocol/genesis/src/chain/hardfork.rs
- crates/protocol/genesis/src/chain/mod.rs
- crates/protocol/genesis/src/lib.rs
- crates/protocol/genesis/src/params.rs
- crates/protocol/genesis/src/rollup.rs
- crates/protocol/genesis/src/superchain/chain.rs
- crates/protocol/genesis/src/superchain/chains.rs
- crates/protocol/genesis/src/superchain/config.rs
- crates/protocol/protocol/src/compression/config.rs
- crates/protocol/registry/src/superchain.rs
- deny.toml
- release.toml
Been wanting to do this for a while.
We've been inconsistently naming configuration types across our codebase.
Some have the suffix "Configuration" while others have "Config".
This PR renames `HardForkConfiguration` type to `HardForkConfig` and
deprecated a new `HardForkConfiguration` alias to improve devx.
I don't see a need to spell out the full "configuration" blurb when most
everywhere just uses "config" to denote a configuration, but open to discussion.
> chore(genesis): Rename HardForkConfiguration

- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/client/src/single.rs
- bin/host/src/interop/handler.rs
- crates/proof/proof/src/l1/pipeline.rs
- crates/protocol/derive/src/sources/blobs.rs
- crates/protocol/derive/src/sources/calldata.rs
- crates/protocol/derive/src/sources/ethereum.rs
- crates/protocol/derive/src/stages/l1_retrieval.rs
- crates/protocol/derive/src/test_utils/data_availability_provider.rs
- crates/protocol/derive/src/traits/data_sources.rs
Alters the data availability provider in the derivation pipeline to use a dynamic batcher address. There is currently an issue in `kona` where chains that have changed their batch submitter key since genesis will not read batches from L1 correctly.
closes https://github.com/op-rs/kona/issues/1103
> fix(derive): Use `SystemConfig` batcher key for DAP

- crates/proof/proof-interop/src/pre_state.rs
Adjusts the `TRANSITION_STATE_MAX_STEPS` to `128 -1`.
closes #1138
> chore(proof-interop): Adjust `TRANSITION_STATE_MAX_STEPS`

- crates/protocol/hardforks/src/forks.rs
Fixes `kona-hardforks` docs to use its own crate instead of the old `op_alloy_consensus` crate.
> chore(hardforks): Fix Alloy Reference

- .github/workflows/rust_ci.yaml
- Cargo.lock
- Cargo.toml
- crates/providers/providers-local/Cargo.toml
- crates/providers/providers-local/src/chain_provider.rs
Based on https://github.com/op-rs/kona/pull/1104
Replaces `reth-provider` with `reth-execution-types`. This enables bumping reth deps to v1.2.0, which wasn't possible before since `reth-provider` is not `no-std` compatible.
> chore(deps): Use `reth-execution-types` instead of `reth-provider`

- .github/workflows/rust_ci.yaml
- Cargo.lock
- Cargo.toml
- crates/providers/providers-local/Cargo.toml
- crates/providers/providers-local/src/chain_provider.rs
Based on https://github.com/op-rs/kona/pull/1094
- Bumps reth to v1.2.0
- Updates docs to reflect that `ChainProvider` is for L1 chain
> chore(deps): Bump reth

- Cargo.lock
- crates/protocol/derive/Cargo.toml
- crates/protocol/derive/src/attributes/stateful.rs
`kona-derive` was resting on a completely broken `op_alloy_consensus` dependency for Hardforks.
This PR fixes that dep to use the updated `kona-hardforks` crate as a dep.
> fix(derive): Hardfork Deps

- crates/protocol/interop/Cargo.toml
- crates/protocol/interop/src/client.rs
- crates/protocol/interop/src/lib.rs
- crates/protocol/interop/src/supervisor.rs
Replaces the `interop` feature flag in the `kona-interop` crate with a `client` feature flag that holds the client impl for the `Supervisor` trait that is now exposed without a feature flag.
> chore(interop): Replace Interop Feat Flag

- Cargo.lock
- bin/client/src/precompiles/utils.rs
Locally breaking macro rules are acceptable since crates are versioned.
Further, the newly covered `const` and `_` syntax patterns are unused
when the expression fragment specifier is used currently, so there won't
be breaking backwards compatibility.
Essentially, the change from `expr_2021` -> `expr` now covers `const` and
`_` which would be a breaking change for prior usage of the macro.
The Rust edition guide [sums this up][sum] fairly well.
[sum]: https://doc.rust-lang.org/edition-guide/rust-2024/macro-fragment-specifiers.html
> fix: 2021 Edition Fragment Specifier

- Cargo.lock
- Cargo.toml
- crates/protocol/registry/Cargo.toml
- crates/protocol/registry/src/chain_list.rs
- crates/protocol/registry/src/lib.rs
- crates/protocol/registry/src/superchain.rs
Adds some simple convenience functions that fetch `Chain` and `RollupConfig`s by their human-readable identifiers. This is useful for the rollup node entrypoint, where we want to have a nice `--network` flag that doesn't only accept opaque numeric chain IDs for the argument.
> feat(registry): Lookup `Chain` + `RollupConfig` by identifier

- crates/proof/executor/src/syscalls/eip2935.rs
- crates/proof/executor/src/syscalls/tx_env.rs
Fixes some comments in the EIP-2935 syscall module.
> chore(executor): Fix comments in EIP-2935 syscall module

- crates/proof/preimage/README.md
Adds labels to the readme of the `kona-preimage` crate, to align the `README` with other crates.
> chore(preimage): Add labels to `README.md`

- crates/proof/executor/README.md
- crates/proof/preimage/README.md
Adds labels to the `kona-executor` crate readme, to align with other crates' `README.md` files.
> chore(executor): Add labels to `README.md`

- bin/host/README.md
- crates/proof/executor/README.md
- crates/proof/preimage/README.md
Updates the `README.md` file of `kona-host` - the "Usage" section was out of date, and it didn't describe the interop mode.
> chore(host): Update `README.md`

- crates/protocol/protocol/src/info/variant.rs
Introduces a fix for the `L1BlockInfoTx`, where we weren't using the `BlobParams::prague()` when crafting the L1 block info transaction.
> fix(protocol): Use `Prague` blob fee calculation for L1 info tx

- Cargo.lock
- crates/node/engine/Cargo.toml
- crates/node/engine/src/lib.rs
- crates/node/engine/src/tasks/forkchoice/error.rs
- crates/node/engine/src/tasks/forkchoice/task.rs
- crates/node/engine/src/tasks/insert/error.rs
- crates/node/engine/src/tasks/insert/messages.rs
- crates/node/engine/src/tasks/insert/mod.rs
- crates/node/engine/src/tasks/insert/task.rs
- crates/node/engine/src/tasks/mod.rs
- crates/node/engine/src/tasks/traits.rs
Updates the insert unsafe payload task.
I'm starting to think messaging out engine api calls from the individual engine tasks doesn't make sense.
Decoupling the state from the engine controller seems like the right abstraction, but further decoupling of the engine tasks and the engine api doesn't seem warranted.
Will follow up to give engine tasks a reference to the `EngineClient` so they can perform engine api requests internal to the task. This way, the only messages that should
be needed from engine tasks are updates to and requests for the engine state.
> feat(engine): Insert Task Updates

- bin/node/src/node/mod.rs
- crates/providers/providers-alloy/src/chain_provider.rs
Refactors the `AlloyChainProvider` to use functions from the `alloy_provider::Provider` trait to fetch blocks. Since we wrote this, APIs to convert from RPC types -> consensus types have improved.
> feat(providers-alloy): Refactor `AlloyChainProvider`

- Cargo.lock
- bin/node/src/node/mod.rs
- crates/providers/providers-alloy/Cargo.toml
- crates/providers/providers-alloy/src/chain_provider.rs
- crates/providers/providers-alloy/src/l2_chain_provider.rs
Refactors the `AlloyL2ChainProvider` to use functions from the `alloy_provider::Provider` trait to fetch blocks. Since we wrote this, APIs to convert from RPC types -> consensus types have improved.
> feat(providers-alloy): Refactor `AlloyL2ChainProvider`

- Cargo.lock
- crates/node/engine/Cargo.toml
- crates/node/engine/src/actor.rs
- crates/node/engine/src/tasks/forkchoice/task.rs
- crates/node/engine/src/tasks/insert/error.rs
- crates/node/engine/src/tasks/insert/messages.rs
- crates/node/engine/src/tasks/insert/task.rs
- crates/node/net/Cargo.toml
- crates/node/net/src/driver.rs
- crates/node/net/src/gossip/handler.rs
- Updates forkchoice and insert tasks to perform engine api calls through client inside the task instead of messaging as described in #1194.
- Implements a bunch of the new payload insert logic - the type argument is taken as the output from derivation which doesn't line up with the inputs to the engine_newPayload methods though so that will need to be cleaned up.
> feat(engine): Insert New Payload

- crates/node/engine/src/actor.rs
- crates/node/engine/src/tasks/forkchoice/messages.rs
- crates/node/engine/src/tasks/insert/task.rs
- crates/node/engine/src/versions.rs
Wires up the `InsertTask` into the engine actor.
Notice, since we previously removed the engine client decoupling, passing in the engine client reference directly to the task, we can now removing custom msg processing in the engine actor. Instead, we just pass along the message for the orchestrator to handle.
> feat(engine): Wire up Insert Task

- Cargo.lock
- bin/node/Cargo.toml
- bin/node/src/cli/node.rs
- bin/node/src/node/mod.rs
- bin/node/src/node/sync_start.rs
- crates/protocol/derive/src/errors/pipeline.rs
- crates/providers/providers-alloy/src/chain_provider.rs
- crates/providers/providers-alloy/src/l2_chain_provider.rs
- crates/providers/providers-alloy/src/lib.rs
Adds an implementation of the [sync start spec](https://specs.optimism.io/protocol/derivation.html#finding-the-sync-starting-point), and uses it to determine the starting L2 forkchoice.
> feat(node): Add `sync_start` module

- crates/proof/executor/src/executor/env.rs
- crates/protocol/protocol/src/info/variant.rs
Adjusts the fork implemented in #1195 to activate based off of the L1 block time, rather than the L2 block time. This keeps the consistency where for all L2 blocks in a given epoch, the L1 block info is constant.
Also:
* Adds a test to the L1 block info variant to ensure the fork activation rules, when the fork is present, are respected.
* Adjusts `prepare_block_env` to use `BlobParams::prague` on L2 after _Isthmus activation_
* This one should be a no-op since the blob fee on L2 is constant at `1`, but for semantic reasons, I think it's good that we don't just leave that one using `BlobParams::cancun`.
> chore(protocol): Update Sepolia-only fork to activate on L1 blocktime

- crates/node/rpc/src/jsonrpsee.rs
- crates/node/rpc/src/lib.rs
Renames the `RollupNode` api trait to `RollupNodeApi`, as to not conflict with the `RollupNode` service in the node lib. Also actually exports the APIs in `jsonrpsee`.
closes #1209
> chore(rpc): Rename `RollupNode` -> `RollupNodeApi`, export

- crates/protocol/genesis/src/system/config.rs
Updates the deserialization routine of the `SystemConfig` to account for the changes in the `monorepo`'s `SystemConfig` type.
See: https://github.com/ethereum-optimism/optimism/blob/d1900114668dc40058ce4fe8573ed5c04d8ef040/op-service/eth/types.go#L520-L521 and https://github.com/ethereum-optimism/optimism/blob/d1900114668dc40058ce4fe8573ed5c04d8ef040/op-service/eth/types.go#L641-L648
> chore(genesis): Update `SystemConfig` ser

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- crates/proof/executor/Cargo.toml
- crates/proof/mpt/Cargo.toml
- crates/protocol/driver/Cargo.toml
Finally releases the `kona-driver` which was blocked on the `kona-executor` importing `kona-host` (an unpublished binary).
> release: kona-driver

- Justfile
Allows unused dependencies in lint jobs that use `-Zbuild-std`. ref: https://github.com/google/wasefire/pull/764
> chore: Allow udeps in `-Zbuild-std` lints

- bin/host/src/interop/cfg.rs
- bin/host/src/single/cfg.rs
- crates/utilities/cli/src/cli_parsers.rs
Small PR to remove the `B256` value parser that uses the default `B256` `FromStr` parsing.
Also fixes the interop cli config which required the `--l2-node-address` flag which DNE.
> chore: Remove B256 Value Parser

- crates/proof/proof/src/eip2935.rs
Removes the duplicated history storage address constant, in favor of re-using the one from `alloy-eips`.
> chore(proof): Use `HISTORY_STORAGE_ADDRESS` from `alloy-eips`

- .github/workflows/rust_ci.yaml
- Justfile
Cargo deprecated the `--all` flag in favor of the `--workspace` flag.
See: https://doc.rust-lang.org/cargo/commands/cargo-test.html#package-selection
> chore(ci): Deprecate --all Flag

- .github/workflows/rust_ci.yaml
- Cargo.lock
- Cargo.toml
- Justfile
- bin/host/Cargo.toml
- book/src/archives/monorepo.md
- crates/node/engine/Cargo.toml
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/insert/error.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/p2p/src/gossip/handler.rs
- crates/proof/executor/src/executor/mod.rs
- deny.toml
General cleanup and dependency bumps.
> chore: Cleanup and Dependency Bumps

- bin/host/src/bin/host.rs
- bin/host/src/interop/cfg.rs
- bin/host/src/single/cfg.rs
- bin/node/src/cli.rs
- bin/node/src/commands/node.rs
- bin/node/src/flags/globals.rs
- bin/node/src/flags/p2p.rs
- examples/discovery/src/main.rs
- examples/gossip/src/main.rs
This PR updates deprecated #[clap(...)] attributes to their modern equivalents in clap 4.x.
The current codebase still uses outdated syntax that has been deprecated since version 4.0.
By making this update, we ensure compatibility with future versions and maintain code quality.
I ran cargo check --features clap/deprecated after making the changes, and the previous clap deprecation warnings are no longer present.
Fixes #1284
> Refactor: Clap attribute macros from #[clap(...)] to #[arg(...)] and #[command(...)] in v4.x

- crates/protocol/protocol/src/batch/single.rs
- crates/protocol/protocol/src/utils.rs
Removes magic deposit tx identifier bytes (`0x7E`) in favor of the strongly typed `op_alloy_consensus::OpTxType::Deposit` variant.
> chore: Remove Magic 0x7E Deposit Identifier Bytes

- bin/node/src/main.rs
- crates/utilities/cli/src/backtrace.rs
- crates/utilities/cli/src/lib.rs
Micro PR to move backtrace initialization into `kona_cli` to simplify the binaries.
Part of a larger effort to simplify binary entrypoints.
> chore(cli): Refactors Backtrace Init

- bin/node/src/commands/net.rs
- crates/node/p2p/src/discv5/handler.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/src/rpc/request.rs
- examples/discovery/src/main.rs
Cleans up the network driver to remove the logs on an interval.
Allows the downstream user to request stats through the RPC channel instead of always logging on an interval, hurting perf.
Since this is an exposed mpsc, we should really move away from calling it an RPC channel since it's open to any external request and is used as such.
> chore(node/p2p): Cleanup Network Driver

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/peers/store.rs
Fixes `kona-p2p` to bootstrap the discv5 table with ENRs that contain the OP Stack CL ENR key.
Previously, we were populating the table with any enr found and recorded in the bootstore.
Quickly, as the bootstore filled up, we hit a limit on the number of ENRs that could be added to the discv5 table.
We essentially had no priority in which ENRs to place in the discovery table.
This PR filters out ENRs in the bootstore that do not contain op stack keys so the discv5 table is only initially populated with:
- Bootnodes, hardcoded into `kona-p2p`
- ENRs in the bootstore that have the op stack CL key
Bootstrapping now effectively ignores ENRs in the bootstore that do not have the op stack CL key.
> fix(node/p2p): OP Stack ENRs

- Cargo.lock
- Cargo.toml
- bin/node/src/commands/net.rs
- crates/node/p2p/src/gossip/handler.rs
Bumps `op-alloy` to `0.11.4`, a backport of changes made after `0.12.0`.
This release contains the payload hash fix and ssz encoding of the `OpNetworkPayloadEnvelope` type.
With these changes, kona's P2P stack successfully decodes unsafe blocks over p2p gossip
and is in a spot to support gossiping out unsafe blocks using the ssz encoding.
> chore: Bump op-alloy Patch

- bin/node/src/commands/net.rs
- crates/node/p2p/src/gossip/behaviour.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/gossip/handler.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/tests/common/mod.rs
- crates/node/service/src/actors/network.rs
- examples/gossip/src/main.rs
Fixes unsafe payload sending in kona's P2P stack by using a queue at the top-level.
This splits the fallible block sending logic out of the `BlockHandler`, letting the block handling solely perform validation.
Closes #1365.
> fix(node/p2p): Unsafe Payload Sending

- Cargo.lock
- bin/node/src/cli.rs
- bin/node/src/commands/net.rs
- bin/node/src/commands/node.rs
- bin/node/src/flags/globals.rs
- crates/node/p2p/src/gossip/config.rs
Allows subcommands to configure telemetry how they wish but enforces that telemetry is setup.
> chore(bin/node): Allow subcommands to customize telemetry

- crates/node/service/src/service/standard/node.rs
Tiny PR to remove `.expect` in the kona-node-service.
> chore(node/service): Remove .expect

- crates/node/service/src/service/standard/node.rs
Removes the `#[allow(unused)]` attribute since the rpc launcher is used.
> chore(node/service): The RPC Launcher is Used

- docker/docker-bake.hcl
- docker/fpvm-prestates/README.md
- docker/fpvm-prestates/cannon-repro.dockerfile
- docker/fpvm-prestates/justfile
Adds a dockerfile for reproducible builds of the `cannon` prestate with `kona-client`.
Note that `cannon` does not yet support `kona`. https://github.com/ethereum-optimism/optimism/pull/14454 must be merged before this can be used. This PR just adds the route to build the artifacts, but we will need to follow up with #1388  once the new instructions are supported and a new `cannon` tag has been released.
> feat(docker): Reproducible `cannon` prestate

- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/handler.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/gossip/handler.rs
- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/src/peers/mod.rs
- crates/node/p2p/src/peers/monitoring.rs
- crates/node/p2p/src/peers/record.rs
- crates/node/p2p/src/peers/utils.rs
- crates/proof/executor/src/syscalls/eip2935.rs
- crates/protocol/derive/src/stages/batch/batch_stream.rs
- crates/protocol/driver/src/pipeline.rs
- crates/protocol/interop/src/errors.rs
- crates/protocol/protocol/src/batch/transactions.rs
- crates/utilities/cli/src/sigsegv_handler.rs
Allows nodes to ban poorly performing peers, similarly to https://github.com/ethereum-optimism/optimism/blob/b4070c5244c8c7ba6d37b9e31fa7d43ada25070d/op-node/flags/p2p_flags.go#L20C2-L26.
This PR:
- Adds CLI flags to allow banning nodes, specify a banning threshold and a banning duration
- Incorporates the P2P flag configuration to the gossip config/driver
- Adds banning logic to the network thread. Ban checks happen every 1 sec by default.
To ban peers on the network thread we:
- Scan the gossip layer for poorly performing peers
- Remove the peers from the gossip layer
- Scan the gossip layer and detect peers to ban. Ban the peers for a given duration.
If merged, this PR completes #1371 
Small note: I have ran clippy so there might be some semi-colons added to unrelated parts of the …
> feat(bin/node): implement peer banning

- .github/workflows/action_tests.yaml
- Justfile
Hides test output in CI for the action tests. Recently we've been seeing quite a few flakes in CI due to the runner running out of disk space. Logs for these tests are usually between 1-1.5 gigabytes.
> chore(ci): Hide action test output

- Cargo.lock
- bin/node/Cargo.toml
- bin/node/src/commands/node.rs
Tiny PR that solves #1416. It adds a check for the validity of the l2 engine jwt *before starting the node*. This PR is merely a copy-paste of the code snippet from the issue with the associated invocation in the node startup.
> chore(bin/node): add jwt startup check

- crates/node/engine/src/attributes.rs
- crates/node/service/src/sync_start.rs
- crates/protocol/protocol/src/deposits.rs
remove redundant word in comment
> chore: remove redundant word in comment

- Cargo.lock
- Cargo.toml
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/peers/any.rs
- crates/node/p2p/src/peers/boot.rs
- crates/node/p2p/src/peers/utils.rs
This PR provides a fix for the bootstrapping of nodes given an enode address. 
In particular:
- it fixes the conversion from "local" `PeerId` to "p2plib" `PeerId`. These two types represent the same underlying concept (secp256k1 public key) but using different encodings (the local `PeerId` is the uncompressed representation of the public key, while the "p2plib" `PeerId` is a more complex representation, involving protobuf encoding and bitcoin encoding, defined here: https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md).
- It slightly changes the logic of the `bootstrap` method to ensure that both enode and enr encoded bootstrap nodes are added.
- It adds util methods for the conversion from local representation to "p2plib" representation of `PeerId`. 
- It adds unit testing to …
> bug(node/p2p): fix bootstrapping for enode addresses

- Cargo.lock
- Cargo.toml
- crates/proof/executor/Cargo.toml
- crates/proof/executor/src/builder/core.rs
- crates/proof/executor/src/builder/env.rs
Upgrades `op-alloy` and uses the new `OpPayloadAttributes::recovered_transactions`, rather than `decode_and_recover_tx`.
> chore: Use `OpPayloadAttributes::recovered_transactions`

- .github/workflows/action_tests.yaml
We're still seeing issues with the action tests job running out of disk space, even after #1428. This is another step to mitigate the issue.
[`free-disk-space-ubuntu`](https://github.com/marketplace/actions/free-disk-space-ubuntu) removes a lot of the pre-installed tools that aren't necessary for the job to run.
> chore(ci): Add action to free up disk space in action test job

- crates/proof/executor/src/builder/core.rs
internally this would just re-encode the tx again for l1 fee etc.
we can provide the 2718 envelope as input here
> chore: use encodedwith for execute

- .github/workflows/rust_ci.yaml
- Cargo.lock
- book/src/SUMMARY.md
- book/src/examples/executor-test-fixtures.md
- book/src/examples/intro.md
- crates/proof/executor/Cargo.toml
- crates/proof/executor/src/builder/core.rs
- crates/proof/executor/src/lib.rs
- crates/proof/executor/src/test_utils.rs
- examples/execution-fixture/Cargo.toml
- examples/execution-fixture/src/main.rs
Adds some documentation and a new example binary for generating new static test fixtures for the `StatelessL2Builder` in `kona-executor`. Also improves the test to automatically pick up on the test fixtures in `kona-executor`'s `testdata` directory, rather than having to manually specify which ones to run.
> feat(executor): Add example + docs for generating new test fixtures

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/peers/enr.rs
- crates/node/p2p/src/peers/mod.rs
Fixes ENR validation to actually use the op stack enr values to validate the ENR prior to adding the ENR to the discovery table or the libp2p swarm.
> fix(node/p2p): Enr Validation

- Cargo.lock
- crates/protocol/comp/Cargo.toml
- crates/protocol/comp/src/lib.rs
Makes `test-utils` enabled in `cfg(test)` always in `kona-comp`, removing the need to include the module if either `cfg(test)` or `feature = "test-utils` is enabled.
> chore(comp): Enable `test-utils` feature with `cfg(test)`

- Cargo.lock
- crates/protocol/comp/Cargo.toml
- crates/protocol/comp/src/lib.rs
- crates/protocol/derive/Cargo.toml
- crates/protocol/derive/src/lib.rs
- crates/protocol/derive/src/sources/blobs.rs
- crates/protocol/derive/src/sources/ethereum.rs
Makes `test-utils` enabled in `cfg(test)` always in `kona-derive`, removing the need to include the module if either `cfg(test)` or `feature = "test-utils` is enabled.
Also removes the conditional `no_std` status of the crate; All of the `test-utils` here happen to be `no_std` compatible 😄
> chore(derive): Enable `test-utils` feature with `cfg(test)`

- Cargo.lock
- crates/protocol/comp/Cargo.toml
- crates/protocol/comp/src/lib.rs
- crates/protocol/derive/Cargo.toml
- crates/protocol/derive/src/lib.rs
- crates/protocol/derive/src/sources/blobs.rs
- crates/protocol/derive/src/sources/ethereum.rs
- crates/protocol/protocol/Cargo.toml
- crates/protocol/protocol/src/lib.rs
Makes `test-utils` enabled in `cfg(test)` always in `kona-protocol`, removing the need to include the module if either `cfg(test)` or `feature = "test-utils` is enabled.
> chore(protocol): Enable `test-utils` feature with `cfg(test)`

- Cargo.lock
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/block_validity.rs
- crates/node/p2p/src/gossip/handler.rs
- crates/node/p2p/src/gossip/mod.rs
This PR does some light refactoring to the block validity checks from the handler to prepare follow-up PRs that add the remaining validation checks.
In particular, this PR:
- Moves the `block_valid` method to a separate module. This method will get more complicated in the future so this allows us to manage the complexity preemptively
- Returns a result as an output of `block_valid` to be able to pattern match the unit test results
- Refactors the existing unit tests for `block_valid` and adds a couple extra tests (ensure we can encode different block versions)
Merging this PR will make progress towards #1340
> feat(node/p2p): refactor block validity checks

- bin/node/src/commands/net.rs
Tiny PR to break after receiving the peer count.
> fix(bin/node): Break after Receiving Peer Count

- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
Updates the `P2PArgs` CLI flags to contain a new `--p2p.bootstore` flag that accepts an optional path.
This CLI flag allows the user to set the path at which `kona-node` should store and read the "bootstore".
Previously, this was set to `None` manually in `kona-p2p` which effectively used the home directory.
> fix(node): Configurable Bootstore Path

- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/block_validity.rs
Demonstrates using the [`OpExecutionPayload::try_into_block`](https://docs.rs/op-alloy-rpc-types-engine/latest/op_alloy_rpc_types_engine/payload/enum.OpExecutionPayload.html#method.try_into_block) method instead of manually constructing the block hash.
> demo: try into block

- crates/node/p2p/src/gossip/handler.rs
- crates/node/p2p/src/gossip/mod.rs
This PR, built on top of #1451, adds a couple of unit test to ensure the block decoding operations are performed correctly and help enforce some of the validations rules from [the optimism spec](https://specs.optimism.io/protocol/rollup-node-p2p.html#block-validation).
Merging this PR will make progress towards #1340. It should be reviewed after #1451
> test(node/p2p): add extensive testing for block decoding validation

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/peers/store.rs
Fixes the discovery test where a local bootstore can be read into the discovery service on bootstrap, causing test flakes when run locally.
> fix(node): Local Bootstore Conflicts

- crates/utilities/cli/src/tracing.rs
Fixes the `kona-node` missing the default env filter when set to `None`.
> fix(cli): Missing Env Filter

- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/block_validity.rs
As a follow-up of #1451, this PR adds manual block hash checks based on the block validation rules from the [spec](https://specs.optimism.io/protocol/rollup-node-p2p.html#block-validation). 
In particular, this PR:
- Manually recomputes the block header from the network payload envelope. 
- Computes the hash of the block header and compares it with the existing one.
- Adds unit testing.
Small note: I have not been able to use the `try_into_block` method from `alloy` on the `ExecutionPayload` types because I don't have access to the generic transaction type contained in the `Block` struct (in `alloy-consensus`). I had to manually port some of the methods from alloy. We could probably add a method in `alloy`/`op-alloy` to compute the block header from without having to provide the generic …
> feat(node/p2p): add manual block hash checks

- crates/node/p2p/src/gossip/block_validity.rs
This PR adds version specific block checks to the block validation method. It mostly ensures that the topic specific rules from the [spec](https://specs.optimism.io/protocol/rollup-node-p2p.html#block-validation) are respected.
Note that most of the rules are verified through type-checking and using the `ExecutionPayload::try_into_block` methods. So there is only a couple more rules left to check. I tried to detail as much as possible the remaining rules to check and why we can skip explicit checks for some of them.
It should be reviewed after #1453. Merging it will make progress towards #1340.
> feat(node/p2p): add version specific block checks

- crates/node/p2p/src/gossip/block_validity.rs
- crates/node/p2p/src/gossip/handler.rs
This PR adds the last block checks for the validation rules as specified in the [spec](https://specs.optimism.io/protocol/rollup-node-p2p.html#block-validation). In particular this PR adds checks that prevent replays (can't validate the same block twice) and limits the number of blocks that can be validated for a single height.
Merging this PR will close #1340. This PR depends on #1454
> feat(node/p2p): add remaining block checks (replays + maximum block number per height)

- .github/workflows/rust_ci.yaml
Bumps the timeout for the `rust_ci.yaml` jobs to 40 minutes rather than 20. Sometimes they can take a long time on a clean cache.
> chore(ci): Bump timeout on Rust CI jobs

- Cargo.lock
- Cargo.toml
- bin/host/Cargo.toml
- bin/host/src/interop/handler.rs
- bin/host/src/single/handler.rs
- crates/proof/proof/Cargo.toml
- crates/proof/proof/src/l1/blob_provider.rs
- crates/proof/proof/src/l1/mod.rs
Implements a fix for a bug recently found in `op-program` by @imtei that `kona-proof` shares. Our old blob preimage key seeded the field element index, rather than the corresponding bit-reversed root of unity.
The fix for this issue is to alter the blob field element preimage key construction to consist of `kzg_commitment ++ brp_root_of_unity[i]`, rather than `kzg_commitment ++ i`.
For users such as `op-succinct` + `kailua`, which use the full KZG proof to verify the entire blob at once, the preimage key @ `i = 4096` containing the full KZG proof is retained under the legacy key format. No action should be needed from these users. This issue should only affect users that run `kona-proof` in a fault proof environment, of which there currently are none to my knowledge.
A more in-depth …
> fix(proof): Blob preimage keys

- bin/host/src/backend/online.rs
- bin/host/src/server.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/proof/executor/src/builder/assemble.rs
- crates/proof/executor/src/builder/core.rs
- crates/proof/proof-interop/src/boot.rs
- crates/proof/proof/src/boot.rs
- crates/proof/proof/src/l1/blob_provider.rs
- crates/protocol/derive/src/sources/blobs.rs
- crates/protocol/derive/src/stages/attributes_queue.rs
- crates/protocol/derive/src/stages/batch/batch_queue.rs
- crates/protocol/derive/src/stages/batch/batch_stream.rs
- crates/protocol/derive/src/stages/batch/batch_validator.rs
- crates/protocol/derive/src/stages/channel/channel_assembler.rs
- crates/protocol/derive/src/stages/channel/channel_bank.rs
- crates/protocol/derive/src/stages/channel/channel_reader.rs
- crates/protocol/derive/src/stages/frame_queue.rs
- crates/protocol/derive/src/stages/l1_traversal.rs
- crates/protocol/driver/src/pipeline.rs
- crates/protocol/interop/src/graph.rs
Converts all `kebab-case` tracing targets to `snake_case` to standardize. There's quite a mix in the codebase at the moment.
Validate that none remain with `rg "target:\s*\"([a-z0-9]+(?:-[a-z0-9]+)*)\""`
> chore(workspace): Convert all tracing targets to `snake_case` format

- bin/node/src/cli.rs
Adds a few intuitive aliases for various `kona-node` subcommands.
> chore(bin/node): Subcommand Aliases

- bin/node/src/flags/metrics.rs
This metrics fixes the name of the metrics address flag to make it compliant with [op-node](https://github.com/ethereum-optimism/optimism/blob/836d50be5d5f4ae14ffb2ea6106720a2b080cdae/op-node/flags/flags.go#L287)
> bug(bin/node): fix metrics address flag

- bin/node/src/flags/globals.rs
- bin/node/src/flags/metrics.rs
Previously, global and metrics arguments were not global. Meaning, when running `kona-node`, the global and metrics args had to be specified _prior_ to the subcommand.
For example, when running the `node` subcommand the global `--l2-chain-id` argument had to be specified prior to the `node` subcommand.
This made for a weird UX as follows.
```sh
$ kona-node --l2-chain-id 11155420 node ...
```
Now, the global args are marked as `global=true` so Clap is able to parse them both before *and* _after_ the subcommand like so.
```sh
$ kona-node node --l2-chain-id 11155420 ...
```
> fix(bin/node): Global Argument Positioning

- bin/node/src/cli.rs
- bin/node/src/commands/bootstore.rs
- bin/node/src/commands/mod.rs
- crates/node/p2p/src/peers/store.rs
Upstreams a simple bootstore debugging cli tool that I've been using locally.
Prints bootstore file info with `kona-node boostore --all` (for all available bootstores).
Info for a single bootstore can be output by specifying the chain id like so.
```
kona-node --l2-chain-id 11155420 bootstore
```
> feat(node): Bootstore Debugging Tool

- bin/node/src/flags/sequencer.rs
The `disabled` cli flag was conflicting due to the addition of the sequencer cli args.
This PR updates the sequencer "disabled" arg to be called `enabled`, more closely matching it's intended behaviour.
> fix(bin/node): Sequencer Args Duplicate CLI Flag

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/handler.rs
- crates/node/p2p/src/discv5/mod.rs
- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/src/rpc/request.rs
- examples/discovery/src/main.rs
Fixes metrics responses to be spawned in tasks instead of blocking the network driver.
> fix(node/p2p): Metrics Tasks

- bin/node/src/cli.rs
- bin/node/src/commands/info.rs
- bin/node/src/commands/mod.rs
Closes #1393 
To run:
```
cargo run --bin kona-node info
```
Currently it prints:
```
-------------
CHAIN ID: 10
-------------
--> Block Time: 2
--> Name: OP Mainnet
--> Identifier: 10
--> Public RPC - https://mainnet.optimism.io
--> Sequencer RPC - https://mainnet-sequencer.optimism.io
--> Explorer - https://explorer.optimism.io
--> Hardforks: 🍴 Scheduled Hardforks:
-> Regolith Activation Time: Not scheduled
-> Canyon Activation Time: 1704992401
-> Delta Activation Time: 1708560000
-> Ecotone Activation Time: 1710374401
-> Fjord Activation Time: 1720627201
-> Granite Activation Time: 1726070401
-> Holocene Activation Time: 1736445601
-> Pectra Blob Schedule Activation Time (Sepolia Superchain Only): Not scheduled
-> Isthmus Activation Time: 1746806401
-> Interop Activation Time: Not …
```
> feat: add info subcommand to kona-node

- crates/node/p2p/src/peers/score.rs
Currently, setting the `PeerScoreLevel` to `None` isn't possible via clap since it seems to be interpreted as an option variant.
In other words, if you pass `--p2p.scoring none` to the `kona-node` it will error on parsing `none` as a variant of `PeerScoreLevel`.
This PR changes the `r#None` variant to `Off` so peer scoring can be disabled with `--p2p.scoring off`.
> [!NOTE]
>
> Notice, this creates a diff in the api of the `--p2p.scoring` cli flag between the `kona-node` and `op-node`.
> fix(node/p2p): Peer Score Level Off

- bin/node/src/commands/bootstore.rs
- bin/node/src/commands/discover.rs
- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- crates/node/p2p/src/peers/store.rs
This PR adds a new CLI flag to allow manually defining a custom list of initial bootnodes to be added to the p2p discovery layer at startup. This change will allow us to add local network addresses inside Kurtosis.
> feat(bin/node): add custom bootnode list CLI arg

- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/net/broadcast.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/src/net/mod.rs
Wraps broadcasting to encapsulate the unsafe block buffer.
Improves `kona-p2p` so the unsafe block buffer is better abstracted.
> chore(node/p2p): Broadcast Wrapper

- Cargo.lock
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/discv5/driver.rs
Fixes discovery driver tests.
Previously, if you had a local bootstore, the test would pick it up, causing inconsistent test results.
This PR isolates bootstrapping via bootnodes from bootstrapping via the bootstore, making tests repeatable and consistent.
> fix(node/p2p): Discovery Test Fixes

- bin/node/src/commands/net.rs
- bin/node/src/commands/node.rs
- bin/node/src/flags/globals.rs
- bin/node/src/flags/p2p.rs
- crates/utilities/cli/src/tracing.rs
This PR ensures that we can fully configure the rollup with a custom `rollup_config`. Currently, on node startup, some arguments (like the block time or the unsafe block signer) are retrieved from a file containing a list of known network configurations. This prevents us from defining fully custom local networks with an unknown chain ID.
This PR changes the node startup behavior by retrieving the node configuration from the `rollup_config` *first*. If the configuration is unavailable or unspecified, the node tries to retrieve the values from the known network parameters.
This PR will allow us to spin up completely custom networks from Kurtosis.
This PR depends on #1497 and #1496
> feat(bin/node): ensure genesis matches the rollup config before fetching to the known network params list.

- bin/host/src/bin/host.rs
- bin/node/src/flags/globals.rs
- crates/utilities/cli/src/tracing.rs
- examples/discovery/src/main.rs
- examples/execution-fixture/src/main.rs
- examples/gossip/src/main.rs
#1497 seems to have broke the action tests since the host logs were set to tracing by default and caused too many logs.
This PR fixes the CLI verbosity levels for all binaries that use `init_tracing_subscriber`.
> fix(utilities): CLI Verbosity Level

- crates/providers/providers-alloy/src/chain_provider.rs
- crates/providers/providers-alloy/src/l2_chain_provider.rs
Removes the mention of the `debug_*` namespace requirements in `kona-providers-alloy`. This was refactored out a while back, and these providers now operate off of the more widely used `eth_*` namespace methods.
> docs(providers-alloy): Doc touchups

- bin/client/src/interop/consolidate.rs
- bin/client/src/interop/mod.rs
- crates/proof/proof-interop/src/consolidation.rs
- crates/proof/proof-interop/src/provider.rs
- crates/protocol/interop/src/graph.rs
- crates/protocol/interop/src/test_util.rs
Fixes an issue in the interop client program where the `OracleInteropProvider` was operating off of the `cross-safe` heads, rather than the `local-safe` heads. After this change, the global interop provider is instantiated with the `local-safe` headers that were generated during the runs of the first sub-problem.
> fix(proof-interop): Operate provider off of `local-safe` heads

- bin/node/src/flags/p2p.rs
Replaces the `0.0.0.0` magic string with the [`Ipv4Addr::UNSPECIFIED`](https://doc.rust-lang.org/std/net/struct.Ipv4Addr.html#associatedconstant.UNSPECIFIED) constant. Avoids the need for parsing and unwrapping.
> fix(bin/node): Magic String

- crates/protocol/interop/src/constants.rs
- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/graph.rs
Adds a new check to the `MessageGraph` for the message expiry window.
spec ref: https://github.com/ethereum-optimism/specs/pull/671
> feat(interop): Add message expiry check

- bin/node/src/commands/discover.rs
- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/error.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- examples/discovery/src/main.rs
This PR adds flags to allow specifying custom p2p advertise address for the discovery layer. This allows a local node to define a custom address to advertise to external peers. 
This is used in the Kurtosis integration of the kona-node [here](https://github.com/ethpandaops/optimism-package/pull/229/files#diff-a03b79cfb91d58ebac65800353104cf8516c01df6a4e37272337d2dc08ad8392R201-R206).
Closes [#1374](https://github.com/op-rs/kona/issues/1374)
> feat(bin/node): add advertise p2p flags

- bin/node/src/commands/discover.rs
- bin/node/src/flags/p2p.rs
- crates/node/p2p/README.md
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/mod.rs
- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- examples/discovery/src/main.rs
- examples/gossip/src/main.rs
Small PR to add the discv5 UDP port to the advertised addresses from the network.
This matches the behavior of `op-node` more closely, see [the op-node codebase](https://github.com/ethereum-optimism/optimism/blob/174e55f0a1e73b49b80a561fd3fedd4fea5770c6/op-node/p2p/discovery.go#L65-L69)
> feat(bin/node): also advertise udp port

- bin/node/src/commands/discover.rs
- crates/node/p2p/README.md
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/tests/common/mod.rs
- crates/node/service/src/actors/network.rs
- examples/discovery/src/main.rs
- examples/gossip/src/main.rs
Uses the `Ipv4Addr::UNSPECIFIED` const over manual magic number instantiation.
> fix: Use Unspecified Ipv4Addr

- bin/node/src/flags/p2p.rs
This PR fixes the unsafe block signer import method to be compatible with unknown chain ids. Before we were using the `GlobalArgs` to import the rollup config from a registry indexed by chain id. This PR fixes this to use the rollup config provided as an argument (either at a custom path, or retrieved from the registry)
> fix(bin/node): fix the unsafe block signer to be compatible with unknown chain ids

- Cargo.lock
- bin/node/src/commands/discover.rs
- bin/node/src/flags/p2p.rs
- crates/node/p2p/Cargo.toml
- crates/node/p2p/README.md
- crates/node/p2p/src/discv5/builder.rs
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/error.rs
- crates/node/p2p/src/discv5/mod.rs
- crates/node/p2p/src/lib.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- examples/discovery/Cargo.toml
- examples/discovery/src/main.rs
- examples/gossip/Cargo.toml
- examples/gossip/src/main.rs
This PR ensures that the keys advertised by discv5 for the local node matches the one from the gossip layer. Currently the node uses different keys for discv5 and the gossip layer which may cause some of the instability we have observed at the gossip layer (nodes get dropped unexpectedly).
> fix(node/p2p): ensure that the discovery and the gossip keys match

- bin/client/src/interop/consolidate.rs
- bin/host/src/interop/handler.rs
- crates/proof/proof-interop/src/consolidation.rs
There is a small issue in this hint currently, where it is possible for the agreed block hash to equal the disputed block hash. This is because the `SuperRoot` progresses every 1s, but the chains within it do not necessarily. In the event that the agreed block hash equals the disputed block hash, the block data hint can be ignored.
> fix(host-interop): Ignore block data hint if chain hasn't progressed

- Cargo.lock
- bin/host/src/interop/handler.rs
- bin/host/src/single/handler.rs
- crates/proof/executor/src/builder/assemble.rs
- crates/proof/executor/src/constants.rs
- crates/protocol/derive/src/attributes/stateful.rs
- crates/protocol/hardforks/Cargo.toml
- crates/protocol/hardforks/src/ecotone.rs
- crates/protocol/hardforks/src/fjord.rs
- crates/protocol/hardforks/src/isthmus.rs
- crates/protocol/interop/Cargo.toml
- crates/protocol/interop/src/access_list.rs
- crates/protocol/interop/src/constants.rs
- crates/protocol/interop/src/lib.rs
- crates/protocol/interop/src/message.rs
- crates/protocol/interop/src/test_util.rs
- crates/protocol/protocol/src/info/variant.rs
- crates/protocol/protocol/src/predeploys.rs
Small aesthetic / consistency cleanup across the codebase - completes the definition of predeploys within `kona-protocol`'s `Predeploys` struct, and uses them everywhere rather than the odd one-off local constants in a few crates.
> feat(protocol): Complete `Predeploys` definition

- Cargo.lock
- crates/node/p2p/src/discv5/driver.rs
- deny.toml
Fixes the `kona-node` discovery driver to properly forward valid ENRs discovered through `discv5` to the gossip driver
> chore(node/p2p): Forward Discovery Events

- .github/workflows/action_tests.yaml
Caches foundry artifacts in the action tests workflow. Speeds up the job significantly, with contracts often taking 4-5 minutes to build.
> perf(ci): Cache forge artifacts in action tests

- bin/node/src/commands/net.rs
- crates/node/p2p/README.md
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/gossip/behaviour.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/tests/gossip_connect.rs
- crates/node/service/src/actors/network.rs
- examples/gossip/src/main.rs
Waits for the libp2p swarm to establish listening on its address before proceeding with peer connection.
Avoids the situation where it takes the swarm time to listen on the given address while the network service is sending over peers for it to connect to.
> fix(node/p2p): Wait for Swarm Address Dialing

- bin/host/src/backend/online.rs
- crates/proof/preimage/src/errors.rs
- crates/proof/std-fpvm/src/channel.rs
- crates/proof/std-fpvm/src/io.rs
Small fix for large IO operations using `NativeClientIO` in the FPVM environment. This hasn't come up before for us, since all reads are generally within the size of an operating system page on the host machine. However, with the `L2PayloadWitness` hint, we easily breach that boundary.
> fix(std-fpvm): Large file IO

- bin/node/src/flags/p2p.rs
This PR makes sure that dynamic ENR updates (at the discovery layer) are disabled when explicitly setting the advertised IP. This respects the behavior of the op-node that treats the advertised IP as static IP, hence that shouldn't be dynamically updated by the discovery layer. See [here](https://github.com/ethereum-optimism/optimism/blob/174e55f0a1e73b49b80a561fd3fedd4fea5770c6/op-node/p2p/discovery.go#L63)
Small note: there is also a small [one liner](https://github.com/op-rs/kona/pull/1558/files#diff-d72b5a9e5e10500d4de868bc3be0bcdc32530ba30a380f1c8b4919cfebdb92d3R374) that is an artifact of #1525 (it seems I missed that one)
> feat(node/p2p): disable dynamic ENR updates for static IPs

- Cargo.lock
- Cargo.toml
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/peers/utils.rs
Small PR that fixes the enr to multiaddress translation inside the kona-node. The produced multiaddresses did not contain the p2p (peer id) and the udp protocols from the ENRs.
> fix(node/p2p): Fix multiaddress translation

- bin/client/src/kona.rs
- bin/client/src/kona_interop.rs
- crates/proof/std-fpvm-proc/src/lib.rs
- crates/proof/std-fpvm/src/io.rs
- crates/proof/std-fpvm/src/malloc.rs
- crates/proof/std-fpvm/src/mips64/io.rs
- crates/proof/std-fpvm/src/mips64/syscall.rs
- crates/proof/std-fpvm/src/riscv64/io.rs
- crates/proof/std-fpvm/src/riscv64/syscall.rs
- crates/proof/std-fpvm/src/traits/basic.rs
Removes the statically sized heap in the FPVM-targeted client program, in favor of asking the kernel to lazily allocate pages at runtime. This enables `kona-proof` to be safe in the face of L2 chains scaling their throughput, often resulting in larger decompressed channel sizes and large transaction lists that the program must ephemerally hold onto.
Optimism's fault proof VMs support a minimal implementation of the `mmap` system call, where they bump a local variable in the kernel that keeps track of the current heap pointer. If a new allocation occurs within the mapped virtual memory, it will lazily allocate new pages for the program it is emulating to use. See [`cannon`'s mmap impl](https://github.com/ethereum-optimism/optimism/blob/18b74a03dea61c58a02e4e5a156e9091be9ccba7/cannon/mipsevm …
> feat(std-fpvm): Instruct kernel to lazily allocate pages

- Cargo.lock
- Cargo.toml
- crates/proof/std-fpvm/Cargo.toml
- crates/proof/std-fpvm/src/malloc.rs
- crates/proof/std-fpvm/src/traits/basic.rs
Switches `kona-std-fpvm` over to the `buddy_system_allocator`, now that memory usage isn't a very sensitive resource in the FPVM variant of the proof program (after #1567)
The `buddy_system_allocator` is much more efficient for some of the large allocations we have to do, for example during channel decompression. It does, however, come with the tradeoff of a larger memory footprint, since it allocates in `2^n` byte blocks.
> perf(std-fpvm): Switch to `buddy_system_allocator`

- bin/host/src/single/cfg.rs
- bin/host/src/single/handler.rs
Adds a new flag to `kona-host` to gate the use of `debug_payloadWitness`. This prevents runs from performing a call to this endpoint if they don't plan to use it.
> chore(host): Gate experimental `debug_payloadWitness` usage

- Cargo.lock
- bin/node/src/flags/p2p.rs
- crates/node/engine/src/client.rs
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/behaviour.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/gossip/error.rs
- crates/node/p2p/src/gossip/event.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/peers/nodes.rs
- crates/node/p2p/src/peers/utils.rs
- crates/node/p2p/src/rpc/request.rs
- crates/node/p2p/tests/common/mod.rs
- crates/node/service/src/service/standard/builder.rs
- crates/providers/providers-alloy/src/l2_chain_provider.rs
This PR brings an additional wave of fixes to the p2p layer for the kona node. In particular this PR:
- Enables the `identify` protocol for node discovery. This helps kickstart the gossip layer from the op-node
- Does a small change to the RPCClients to remove the `is_local` flag
- Removes the udp protocol from the converted multiaddresses from ENRs (it produces malformed multiaddresses)
- Does a couple of small log visibility changes that were useful to debug the kona-node inside kurtosis
Merging this PR will fix the p2p gossip for kona-nodes and allow them to receive/gossip blocks on the p2p layer. Kona-nodes can also communicate with op-nodes (tested in Kurtosis)
To some extent, merging this PR will fix #1396 
It seems that the peers get graylisted after a while and eventually get …
> fix(node/p2p): enable identify protocol. Additional small fixes

- .config/optimism_package.json
- .gitignore
- Justfile
Adds a few targets to the workspace `Justfile` to make it easier to work with kurtosis.
- `build-node`: Builds the `kona-node` docker image, tagging it as `kona-node:latest`.
- `optimism-package`: Clones the `optimism-package` repo specified in `.config/optimism_package.json` to `optimism-package`. This directory is ignored by git through `.gitignore`.
- `kurtosis-up`: Spins up kurtosis using the network params defined in `.config/kurtosis_network_params.yaml` from inside the `optimism-package`, installing it through `just optimism-package` if not already cloned.
- `kurtosis-down`: Cleans up kurtosis.
In another PR it would be nice to add a few targets that grab the logs for the `kona-node` and `op-node` instances for debugging.
> feat(workspace): Kurtosis Justfile Targets

- Justfile
Fixes the `build-node` justfile target.
This PR gets the kurtosis targets working properly with a local build of the `kona-node`.
> fix(workspace): Build Kona Node

- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/graph.rs
@tyler-smith's recent [spec PR](https://github.com/ethereum-optimism/specs/pull/691) updated the rules for referencing initiating messages. The check now strictly excludes the activation block.
> chore(interop): Update interop fork activation check for initiating messages

- bin/node/Cargo.toml
- crates/node/p2p/src/gossip/handler.rs
- crates/node/p2p/src/macros.rs
- crates/node/service/Cargo.toml
Enables metrics by toggling `kona-p2p` `metrics` feature flag on for the `kona-node` binary.
> fix(bin/node): Enable Metrics

- bin/client/justfile
- docker/docker-bake.hcl
- docker/fpvm-prestates/asterisc-repro.dockerfile
- docker/fpvm-prestates/cannon-repro.dockerfile
Updates the `cannon` tag to [`cannon/v1.5.0-alpha.1`](https://github.com/ethereum-optimism/optimism/tree/cannon/v1.5.0-alpha.1), which adds support for the `DCLO` and `DCLZ` instructions required to run `kona`'s `mips64r1` target.
> chore(docker): Update `cannon` tag

- docker/docker-bake.hcl
- docker/fpvm-prestates/asterisc-repro.dockerfile
- docker/fpvm-prestates/cannon-repro.dockerfile
- docker/fpvm-prestates/justfile
Adds a new parameter to the reproducible prestate bake targets that allows for specifying any available binary target of the `kona-client` crate. This allows for reproducible builds of FPVM prestates based off of `kona-int`, the interop variant of the client program.
> feat(docker): Enable reproducible prestate builds for interop program

- Cargo.lock
- bin/client/src/interop/consolidate.rs
- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/client/src/kona_interop.rs
- bin/host/src/interop/cfg.rs
- crates/proof/proof-interop/Cargo.toml
- crates/proof/proof-interop/src/consolidation.rs
Uses the `FpvmOpEvmFactory` in the interop proof program, adding support for accelerated precompiles.
closes #1543
> feat(interop): Use `FpvmOpEvmFactory` in interop proof program

- bin/client/src/fpvm_evm/factory.rs
- bin/client/src/fpvm_evm/precompiles/bls12_g1_add.rs
- bin/client/src/fpvm_evm/precompiles/bls12_g1_msm.rs
- bin/client/src/fpvm_evm/precompiles/bls12_g2_add.rs
- bin/client/src/fpvm_evm/precompiles/bls12_g2_msm.rs
- bin/client/src/fpvm_evm/precompiles/bls12_map_fp.rs
- bin/client/src/fpvm_evm/precompiles/bls12_map_fp2.rs
- bin/client/src/fpvm_evm/precompiles/bls12_pair.rs
- bin/client/src/fpvm_evm/precompiles/bn128_pair.rs
- bin/client/src/fpvm_evm/precompiles/ecrecover.rs
- bin/client/src/fpvm_evm/precompiles/kzg_point_eval.rs
- bin/client/src/fpvm_evm/precompiles/provider.rs
- bin/client/src/fpvm_evm/precompiles/utils.rs
- bin/client/src/interop/mod.rs
- bin/client/src/kona.rs
- bin/client/src/kona_interop.rs
- bin/client/src/single.rs
- bin/host/src/interop/cfg.rs
- bin/host/src/single/cfg.rs
Refactors the `FvpmOpEvmFactory` and accelerated precompiles to accept looser types. Rather than requiring a `HintWriter` and `OracleReader`, the constraints have been lowered to implementations of the `HintWriterClient` and `PreimageOracleClient`.
By default, both the single-chain and interop FPP entrypoints now construct the `FpvmOpEvmFactory` in the background, rather than requiring an `EvmFactory` implementation to be explicitly passed.
> chore(client): Loosen type constraints on `FpvmOpEvmFactory`

- Cargo.lock
- Cargo.toml
- crates/protocol/genesis/src/system/errors.rs
- crates/protocol/genesis/src/updates/batcher.rs
- crates/protocol/genesis/src/updates/eip1559.rs
- crates/protocol/genesis/src/updates/gas_config.rs
- crates/protocol/genesis/src/updates/gas_limit.rs
- crates/protocol/genesis/src/updates/operator_fee.rs
- crates/protocol/genesis/src/updates/signer.rs
`alloy-sol-types` `v1.1.0` re-introduces validation when ABI decoding. This PR reworks the `SystemConfig` event update parsing logic to use that, rather than the hacky external checks that we had to use with `v1.0.0`.
> chore(genesis): Use `abi_decode_validate`

- crates/node/engine/src/state/builder.rs
- crates/node/service/src/actors/engine.rs
Removes the genesis block info fallback in the `EngineStateBuilder`.
By letting the engine state have default block info for the safe and finalized heads, EL sync is correctly kicked off since the hashes are zeroed.
> fix(node/engine): Don't use Genesis in EngineState

- bin/node/src/commands/node.rs
Small PR to disable `discv5` logging by default. They're _incredibly_ noisy. Can be enabled manually through the env.
> chore(bin/node): Disable DISCV5 logging by default

- crates/node/engine/src/task_queue/tasks/task.rs
Temporary engine error logs spam the cli when temporarily stuck.
Since it's not a critical error, decrease the log level to `TRACE` since it's quite common.
Further, it's actually expected behaviour to receive a temporary error when the EL hasn't sync'd up to the L2 block for example in the consolidation task.
> chore(node/engine): Decrease Temporary Log Level

- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/graph.rs
- crates/protocol/interop/src/test_util.rs
Refactors the `MessageGraph` test utilities in `kona-interop` to be a bit more intuitive.
Note: The errors that caused block invalidity are still opaque to the consumer, and a follow up PR (#1644) exposes them in the API such that the consumer can inspect why a block was deemed to be invalid.
> chore(interop): Refactor `MessageGraph` test utilities

- crates/protocol/genesis/src/rollup.rs
- crates/protocol/protocol/src/batch/single.rs
- crates/protocol/protocol/src/info/variant.rs
Adds a few helper functions to the `RollupConfig` that check if a timestamp corresponds to the activation block of a hardfork.
closes #1603
> feat(genesis): Add `is_first_fork_block` helpers to `RollupConfig`

- bin/host/src/interop/handler.rs
- crates/protocol/genesis/src/rollup.rs
Adds a helper function to the `RollupConfig` to compute a block number from a given timestamp, relative to the config's L2 genesis time and block time.
> feat(genesis): Add `block_number_from_timestamp` helper

- crates/proof/proof-interop/src/consolidation.rs
- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/graph.rs
Refactors the API of the `MessageGraphError` to return the reason for a block's invalidation. Also adjusts the `MessageGraph` tests to assert the specific reasons for a graph resolution failure on the mock chain.
> feat(interop): Bubble up message validity errors

- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/graph.rs
Modifies the `MessageGraph` code to support unaligned activation times. Given that the superchain supports chains with various blocktimes, the check to exclude the activation block must account for this.
Specs ref: https://github.com/ethereum-optimism/specs/pull/694
> feat(interop): Support unaligned activation time

- bin/client/src/interop/transition.rs
- bin/client/src/single.rs
- bin/host/src/interop/handler.rs
- crates/proof/proof/src/l1/mod.rs
- crates/proof/proof/src/l1/pipeline.rs
- crates/proof/proof/src/sync.rs
This PR refactors the derivation pipeline in `kona-proof` to accept generic `ChainProvider`, `L2ChainProvider` and `DataAvailabilityProvider` types. This allows finer-grain customization of the derivation pipeline with less code duplication. 
For example, the following projects would need only plug in their custom providers instead of vendoring in the entire pipeline code just to change the `OracleDerivationPipeline`/`OracleDataProvider` type aliases:
* [Kailua](https://github.com/risc0/kailua/blob/15a2a8f8135eb25d055962ecde78ba3197844c99/crates/common/src/kona/pipeline.rs#L15)
* [Hokulea](https://github.com/Layr-Labs/hokulea/blob/4f8b33af384ef19d630eaf0f24885f11d3ea15d5/crates/proof/src/pipeline.rs#L47)
* [Hana](https://github.com/celestiaorg/hana/blob/50efa651802cdc601934ebb00e4af2865a20 …
> feat(proof): Derivation over generic L1/L2/DA providers

- .github/workflows/client_host.yaml
- docker/docker-bake.hcl
Bumps the `asterisc` tag to [`v1.3.0`](https://github.com/ethereum-optimism/asterisc/releases/tag/v1.3.0).
> chore(docker): Update `asterisc` tag

- crates/node/engine/src/attributes.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
Adds two small fixes to the `kona-node` for syncing.
1. The attributes transaction matching was incorrectly deserializing transactions using `serde_json` instead of the 2718 encoding.
2. The sync status used when inserting an unsafe payload was incorrect. For reference, see [the op-node](https://github.com/ethereum-optimism/optimism/blob/0c986c9b40b8aedfce663421d7074fb856229cde/op-node/rollup/engine/engine_controller.go#L375).
> fix(node/engine): Attributes Matching and Sync Status

- Cargo.lock
- crates/node/engine/src/client.rs
- crates/node/rpc/src/superchain.rs
- crates/node/service/Cargo.toml
- crates/node/service/src/actors/engine.rs
- crates/node/service/src/actors/mod.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/standard/builder.rs
- crates/node/service/src/service/standard/node.rs
- crates/node/service/src/service/validator.rs
Wires up runtime loading as a lightweight actor in the `kona-node-service`.
Right now, the `OpEngineApi` doesn't support the `engine_signalSuperchainV1` endpoint.
I've added support in [this PR](https://github.com/alloy-rs/op-alloy/pull/512).
Instead of using this for now, I've added a method to the `EngineClient` to send the
signal to the engine client directly using the inner client `.request(..)`.
The interval at which the runtime config can be fetched follows how the `op-node`
configures runtime loading, through the `--l1.runtime-config-reload-interval` cli flag.
Closes #1307
> feat(node/service): Superchain Signaling with Runtime Loading

- crates/node/engine/src/attributes.rs
- crates/node/engine/src/lib.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
- crates/node/engine/src/task_queue/tasks/mod.rs
- crates/node/engine/src/task_queue/tasks/task.rs
- crates/node/service/src/actors/engine.rs
- crates/protocol/protocol/src/deposits.rs
Allows tasks to be processed in a round-robin fashion based on their type.
Since consolidation tasks may need to wait for data in the derivation pipeline, we still want the engine to execute unsafe payload tasks in the meantime.
This round-robin type-based policy preserves strict ordering of the different task types, while allowing progress to be made on different tasks.
> fix(node/engine): Round Robin Task Execution

- crates/node/engine/src/task_queue/core.rs
- crates/node/service/src/actors/engine.rs
- crates/node/service/src/service/validator.rs
This PR transmits the most recent version of the `Engine` state over watch channels to the `EngineActor`. This will allow us to read the state with `RPC` handlers without blocking the `EngineTask` runner.
> feat(node/engine): transmit the most recent version of the `EngineState` over watch channels to the engine actor

- crates/protocol/hardforks/src/isthmus.rs
Small naming error spotted while sanity-checking https://github.com/ethereum-optimism/specs/pull/699, the `deposit_contract_source` is mis-named for the EIP-2935 deployment. Should be named to reference the block hash history contract.
> chore(hardforks): Correct EIP-2935 source name

- bin/node/src/commands/node.rs
- crates/node/engine/src/kinds.rs
- crates/node/engine/src/state/builder.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/service/src/actors/engine.rs
- crates/node/service/src/service/standard/builder.rs
- crates/node/service/src/service/validator.rs
Makes `kona-node` slightly more opinionated by only supporting EL sync.
Previously, the node broke since it couldn't kick off EL sync post-finalization.
Since the finalized and safe heads were populated using the execution engine, a
forkchoice state that kicks off EL sync (zero hash in finalized) wasn't constructed.
This PR removes the unused CL sync, deprecating the `--l2.enginekind` flag, and
moves the `kona-node` over to only support EL sync by initializing finalized
and safe heads to zero on startup, like the `op-node` does. This allows the first
unsafe insert task to kick off el sync.
> fix(node/service): EL Sync Only

- crates/node/engine/src/task_queue/tasks/build/error.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/task.rs
- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine.rs
- crates/node/service/src/service/validator.rs
Wires up the engine actor to send a signal to the derivation actor.
This is necessary when the engine api marks a payload `INVALID`.
Post-Holocene, the payload becomes deposit-only and is re-executed.
At the same time, the derivation pipeline needs to be flushed, so
the channel and remaining buffered batches are cleared.
Makes progress on #1239
> feat(node/service): Flush Channel on Invalid Payloads

- .github/CODEOWNERS
Enables automatic review notifications for all prs to `bin/supervisor` for @dhyaniarun1993 @itschaindev @sadiq1971 as code owners
> chore(meta): Add chainsafe as supervisor code owners

- crates/proof/executor/src/builder/assemble.rs
- crates/proof/executor/src/builder/mod.rs
- crates/proof/executor/src/lib.rs
This PR refactors `compute_receipts_root` as its own publicly exposed function outside of the `StatelessL2Builder` implementation to enable unvendored reuse by downstream packages such as [in Kailua](https://github.com/risc0/kailua/blob/15a2a8f8135eb25d055962ecde78ba3197844c99/crates/common/src/client/stitching.rs#L178).
> feat(executor): Public `compute_receipts_root` method

- crates/node/service/src/actors/derivation.rs
Checks the l2 safe head block number against the local safe head rather than a direct comparison.
> fix(node/service): Check L2 Safe Head BN

- .github/CODEOWNERS
- crates/node/engine/src/task_queue/tasks/build/task.rs
Fixes the engine to only re-attempt deposits only payload if holocene is active for the given payload timestamp.
Closes #1699
> fix(node/engine): Pre-Holocene Deposits Only

- crates/node/rpc/src/l1_watcher.rs
- crates/node/rpc/src/lib.rs
- crates/node/rpc/src/rollup.rs
- crates/node/service/src/actors/l1_watcher_rpc.rs
- crates/node/service/src/service/standard/node.rs
- crates/node/service/src/service/validator.rs
This PR adds an external query handler for the DA watcher. In particular it ensures we can get the necessary data to implement the rollup RPC endpoints.
This query handler makes sure we can access the DA watcher's state through external actors
Progress towards #1653
Depends on #1664
> feat(node/l1_watcher): adds query handler for the l1 watcher

- .config/optimism_package.json
Now that https://github.com/ethpandaops/optimism-package/pull/229 has been merged, we can track the `optimism-package` repo directly to get the most recent updates
> chore(kona/kurtosis): update the link to the optimism-package repo

- crates/node/engine/src/lib.rs
- crates/node/engine/src/query.rs
- crates/node/rpc/src/output.rs
- crates/node/rpc/src/rollup.rs
- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine.rs
- crates/protocol/protocol/src/output_root.rs
This PR fully implements the rollup RPC endpoints for the `kona-node`. Following the suggestion of the op-node's team I have not implemented the `optimism_safeHeadAtL1Block` endpoint as it is not required post-interop.
Merging this will close #1653
Depends on #1692 and #1664
> feat(node/rpc): implement the rollup RPC endpoints

- Cargo.lock
- Cargo.toml
- bin/client/Cargo.toml
- bin/host/Cargo.toml
Bumps `kona-client` and `kona-host` to `v1.0.0`
> feat: Bump `kona-client` and `kona-host` versions

- .github/CODEOWNERS
Adds @dhyaniarun1993 @itschaindev @sadiq1971 as code owners for new crate `kona-supervisor`
> chore(meta): Add chainsafe as code owners of `kona-supervisor`

- Cargo.lock
- Cargo.toml
- crates/node/engine/src/client.rs
- crates/node/service/Cargo.toml
- crates/node/service/src/actors/engine.rs
Small PR to bump `alloy` + `op-alloy` dependencies to their latest version.
`revm` and it's related deps still need to be bumped.
> chore(workspace): Update Alloy Deps

- Cargo.lock
- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/standard/error.rs
- crates/node/service/src/service/standard/node.rs
- crates/node/service/src/service/validator.rs
- crates/node/sources/Cargo.toml
- crates/node/sources/src/lib.rs
- crates/node/sources/src/sync/error.rs
- crates/node/sources/src/sync/forkchoice.rs
- crates/node/sources/src/sync/mod.rs
Fixes derivation to use the engine safe head instead of keeping its own local view.
> fix(node/engine): Derivation Sync Start

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/metrics/mod.rs
Fixes discovery event metric labels to be keyed under `type`, rather than under several different keys.
> fix(node-p2p): Discovery event metric labels

- crates/node/engine/src/state/builder.rs
- crates/node/engine/src/state/core.rs
- crates/node/rpc/src/rollup.rs
- crates/protocol/protocol/src/sync.rs
Removes the pending and backup unsafe heads from the `EngineState` to simplify. These were necessary pre-Holocene, and since `kona-node` only supports execution layer sync, it will never actually need this functionality in the wild.
> chore(engine): Remove pending/backup unsafe head

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine.rs
Allows the derivation actor to aggressively process channels, while it has the data available.
> feat(node-service): Aggressively process channels

- Cargo.lock
- Cargo.toml
- bin/node/Cargo.toml
- bin/node/build.rs
- bin/node/src/cli.rs
- bin/node/src/flags/metrics.rs
- bin/node/src/main.rs
- bin/node/src/metrics/mod.rs
- bin/node/src/metrics/version.rs
- bin/node/src/version.rs
Adds metrics for the version information of the node, including:
1. The binary version
2. The build timestamp
3. Any bin features enabled
4. The commit sha of the build
5. The target triple of the binary
6. The build profile
Also uses this rich version information for the `clap` version.
> feat(node): Version info metrics

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/service/validator.rs
When the derivation pipeline yields in order to wait for more data, it should be marked as idle to note that it is not currently expecting an L2 safe head update for the next `step`. This PR implements a flag in the derivation actor to allow for skipping checking if the safe head has updated during event processing while derivation is idle, enabling it to continue progressing once the tip of the safe chain has been reached.
> feat(node): Mark derivation as idle when it yields

- crates/node/engine/src/task_queue/tasks/consolidate/error.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
Changes the `MissingUnsafeL2Block` error to be a `Reset`. In the case where attributes are being compared with the unsafe block they're associated to, and the `needs_consolidation` check returns `true`, we've encountered an inconsistent engine state.
> fix(engine): Reset with inconsistent chain state

- Cargo.lock
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/discv5/driver.rs
Fixes the `kona-node` bootstrapping to use the manually passed bootnodes in the bootnode bootstrapping to ensure they are prioritized.
Previously, the custom bootnodes were only bootstrapped via the bootstore which is a lower priority than the bootnodes.
This PR also updates the initialization of the discovery service to use an exponential backoff strategy via [backon](https://crates.io/crate/backon).
Before, kona's discovery service would just try to restart in a loop.
> fix(node/p2p): Bootnodes in Bootstrap + Backoff Discv5 Restart

- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/config.rs
- crates/node/p2p/src/peers/score.rs
- crates/node/rpc/src/launcher.rs
Disables topic scoring for all topics like https://github.com/ethereum-optimism/optimism/pull/15719.
Previously the `kona-node` deviated from `op-node` policy on topic scoring. It scored all topics (v1 - v4). The `op-node` only scored the `v1` topic.
> fix(node/p2p): Disable Topic Scoring

- crates/node/p2p/src/discv5/driver.rs
Fixes the panic in the discv5 driver startup. `backon`'s `RetryableWithContext` has a quirk where it will panic if the `sleep` function is set after `context`. We can just remove it, though, since we've enabled the `tokio-sleep` feature by default.
> fix(p2p): Discv5 startup panic

- crates/node/engine/src/client.rs
- crates/node/engine/src/metrics/mod.rs
Adds a histogram for tracking the duration of `engine_forkchoiceUpdated`, `engine_getPayload`, and `engine_newPayload` method calls.
> feat(engine): Engine method call duration metrics

- bin/node/src/commands/node.rs
- bin/node/src/flags/metrics.rs
- bin/node/src/flags/p2p.rs
- bin/node/src/flags/rpc.rs
- bin/node/src/flags/sequencer.rs
Instead of redefining the argument defaults, use the values defined in the clap fields.
> fix(bin/node): Argument Defaults

- bin/node/src/metrics/version.rs
Adjusts the version info metrics to report "none" if no cargo features are enabled, rather than omitting the label entirely.
> chore(node): Empty cargo features metric

- .config/kurtosis_network_params.yaml
Fixes the kurtosis network params to be not fail when running with `just kurtosis-up`. Also ensures that the sequencer is run with `op-geth` as `op-reth` is not yet fully compatible with sequencer mode. Change log levels to debug
> fix(kurtosis): fix kurtosis configuration

- crates/node/engine/src/sync.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/service/src/actors/engine.rs
Updates the condition that the engine actor checks for in order to prompt the beginning of derivation. Previously, it used a call to `eth_syncing`, rather than the engine's own state. This would inadvertently kick off derivation before it EL sync had actually completed.
> fix(node-service): Engine sync completion condition

- .github/workflows/action_tests.yaml
Normalizes the forge version from the monorepo in the action tests job. `foundry-toolchain` requires appending a `v` to numbered versions since it directly downloads from the tagged release artifacts, and the monorepo's `mise.toml` doesn't do this.
This workaround can be removed once `foundry-toolchain` has implemented https://github.com/foundry-rs/foundry-toolchain/issues/73
> chore(ci): Normalize foundry version

- crates/protocol/interop/src/errors.rs
- crates/protocol/interop/src/lib.rs
- crates/protocol/interop/src/safety.rs
Closes #1779 
Also re-exported the `op-alloy` type from `kona-interop` to reduce excessive file changes.
> feat: replace SafetyLevel with op_alloy type

- crates/node/engine/src/task_queue/tasks/insert/task.rs
Tiny nit - updates the block insertion log such that the hash is rendered without quotes.
> chore(engine): Update block insertion log

- .github/workflows/client_host.yaml
- .github/workflows/rust_ci.yaml
Fixes the lint job by using the stable toolchain for the `fmt + lint` job. `cargo fmt` still uses nightly, but clippy uses stable.
> fix(ci): Use stable toolchain for lint job

- crates/node/engine/src/attributes.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/service/src/actors/derivation.rs
Sets the `safe` and `finalized` hashes to `B256::ZERO` while the EL syncs, and also only finalizes the unsafe ref if the client is undergoing its _initial_ sync.
Also moves the priority of the `sync_complete_rx.recv()` future in the biased select within the derivation actor. Since the futures are polled in-order, that future always resolves once the channel has been closed - it must be placed last.
> fix(node): Zero `safe` + `finalized` hashes while EL syncs

- crates/node/engine/src/attributes.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/service/src/actors/derivation.rs
Sets the `cross-unsafe` and `local-safe` labels along with the `unsafe` and `safe` labels. Pre-interop, these labels exactly track each other. When we get around to adding interop support, we'll need to add conditionals for cross-unsafety and reach out to the supervisor for `cross-safe` (`safe` label) promotion
> fix(node): Set `local-safe` and `cross-unsafe` labels

- crates/node/engine/src/sync.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/service/src/actors/engine.rs
- crates/node/sources/src/sync/error.rs
- crates/node/sources/src/sync/forkchoice.rs
- crates/node/sources/src/sync/mod.rs
Simplifies the EL sync startup routine, removing the `ExecutionLayerNotFinalized` stage. Rather than performing the sync start lookup at startup, the sync start routine is performed _after_ EL sync finishes now.
This also improves the security of the sync start routine. Because we no longer blindly promote `safe` + `finalized` when the first EL sync finishes, we can find a `safe` block by traversing backwards from the `unsafe` head, looking for an L2 block whose L1 origin is at least one sequence window behind the `unsafe` head's L1 origin block.
> feat(engine): Simplify EL sync startup routine

- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/block_validity.rs
- crates/proof/executor/src/builder/assemble.rs
- crates/proof/executor/src/constants.rs
Uses `alloy-eips`' `EMPTY_REQUESTS_HASH` constant, rather than defining constants of our own for the empty sha256 hash.
> chore(workspace): Use `alloy-eips`' `EMPTY_REQUESTS_HASH` constant

- crates/node/engine/src/metrics/mod.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/macros/src/metrics.rs
Adds a metric that tracks the number of times the engine has been reset.
closes https://github.com/op-rs/kona/issues/1627 (the engine reset, by proxy, is a derivation reset.)
> feat(engine): Engine reset counter metric

- Cargo.lock
- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/handler.rs
- crates/node/p2p/src/rpc/request.rs
To be able to properly test the `kona-node` synchronization primitives we need to add RPC methods that would allow to interact with the node's internal state.
This PR starts the implementation of the `opp2p_peers` endpoint. A series of follow-up PRs will complete the implementation
Progress towards #1562
> feat(node/p2p): enable support for the peers RPC endpoint

- .github/workflows/e2e_tests.yaml
Adds an action to free up some disk space prior to the kurtosis run. Seeing this job fail quite a bit due to running out of disk.
> fix(ci): Free disk space on kurtosis e2e tests

- tests/Justfile
- tests/go.mod
- tests/go.sum
This PR fixes the package versions of the go e2e test folder. This fix ensures that the kurtosis CI job fails if the `kona-node` fails to start inside kurtosis. This will help preventing breaking the kurtosis deployment (at least at startup).
Merging this PR means we'll be using the version of the monorepo from my fork `https://github.com/theochap/optimism`. This will be helpful to add features to the `devnet-sdk` without waiting for approval inside the `ethereum-optimism/optimism` repo. Once we stabilize the `devnet-sdk` we can remove the pointer to the forked version of the node.
> fix(node/kurtosis-e2e-test): fixes the versionning for the e2e testing package

- crates/node/p2p/src/discv5/driver.rs
- crates/node/p2p/src/discv5/handler.rs
- crates/node/p2p/src/rpc/request.rs
- crates/node/p2p/src/rpc/types.rs
- crates/node/rpc/src/jsonrpsee.rs
- crates/node/rpc/src/p2p.rs
This PR implements the `opp2p_peerStats` endpoint to expose more internal information from the node through RPC. 
This is progress towards #1634 and completes a good chunk of #1563 (this should close it)
> feat(node/p2p): implements the `opp2p_peerStats` endpoint

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine.rs
- crates/node/service/src/service/validator.rs
Forwards derivation reset events to the engine. In the case of the `HoloceneActivation` reset, the reset can be handled internal to the pipeline without informing the engine.
Additionally, adds functionality to block the derivation actor while it is waiting for a signal to be sent back. This will prevent it from attempting to advance while the engine is resetting.
> feat(node-service): Handle derivation reset events

- Cargo.lock
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/rpc/request.rs
- crates/node/p2p/src/rpc/types.rs
Small PR that fixes the `NodeId` serialization inside `opp2p_self`. Using the default `Display` impl strips the middle of the address for readability. We want to be able to return the full address in RPC
Also removes the special display for `Connectedness` which was causing the RPC responses for `opp2p_self` returned by `kona-node` to differ from ones from the `op-node` (only return a `u8`)
> fix(node/p2p): fix node id serialization and connectedness display

- crates/node/engine/src/metrics/mod.rs
Removes the zeroing of the block label gauges at startup.
> chore(engine): Don't zero block label gauges

- crates/node/p2p/src/rpc/request.rs
- tests/node/mod.go
- tests/node/node_test.go
- tests/node/opp2p_rpc.go
- tests/node/peer_count.go
- tests/simple-kona.yaml
This PR adds a very simple test for the node to ensure that nodes in Kurtosis can at least connect to one peer.
This test gives a basic structure to:
- Instantiate a basic e2e test for the `kona-node`
- Query the nodes through RPC for one of their publicly exposed methods
- Retrieve the associated data and perform assertions.
Note: depends on #1812
> feat(node/e2e-test): add peer count test in Kurtosis

- crates/node/p2p/src/rpc/request.rs
This PR fixes the formatting of the `opp2p-peers` rpc method by ensuring that a `NodeId` is correctly formatted. The `Display` impl of the `NodeId` only partially exposes the `NodeId` hex-string.
> fix(p2p/rpc): fix formatting for the `opp2p-peers` rpc method

- docker/README.md
- docker/recipes/kona-node/.gitignore
- docker/recipes/kona-node/README.md
- docker/recipes/kona-node/cfg.env
- docker/recipes/kona-node/docker-compose.yaml
- docker/recipes/kona-node/generate-jwt.sh
- docker/recipes/kona-node/grafana/dashboards/dashboard.yml
- docker/recipes/kona-node/grafana/dashboards/overview.json
- docker/recipes/kona-node/grafana/datasources/prometheus.yml
- docker/recipes/kona-node/justfile
- docker/recipes/kona-node/prometheus/prometheus.yml
Adds an initial recipe within `docker` that launches a `kona-node` + `op-reth` instance, with an accompanying `prometheus` server to scrape metrics and `grafana` instance to host visualizations.
> feat(docker): `kona-node` recipe

- crates/node/engine/src/query.rs
- crates/node/rpc/src/jsonrpsee.rs
- crates/node/rpc/src/lib.rs
- crates/node/rpc/src/ws.rs
- crates/node/service/src/service/validator.rs
This PR adds a couple of websocket endpoints to stream the sync state of the `kona-node`. These endpoints can be useful inside our e2e testing suite to ensure that the node is correctly syncing.
Maybe we should provide a configuration flag to make those RPC endpoints optional. We may not want to be able to subscribe to the current node state. Here is a ticket to track that #1842
Close #1825
> feat(node/p2p): streaming engine state through websockets

- .config/kurtosis_network_params.yaml
- .config/kurtosis_network_params_supervisor.yaml
- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona.yaml
Fixes the kurtosis configuration to use `teku` instead of `nimbus` for L1 consensus client. The latest version of `nimbus` seems to have broken the `optimism-package`.
Also sets the `cl_image` to point to a local image of the node by default. This will improve DX until we reach more stability
> fix(kurtosis/config): fix kurtosis config to use teku instead of nimbus.

- bin/node/src/flags/p2p.rs
This PR patches the default p2p params inside the kona-node to help with keeping gossip connections alive
> patch(node/p2p): patch the default p2p params

- docker/recipes/kona-node/grafana/dashboards/overview.json
Updates the grafana dashboard, including a new "Block Tags" panel in the overview and removing the override for the `finalized` block tag in the sync status panel.
> chore(docker): Update `kona-node` dashboard

- tests/devnets/simple-supervisor.yaml
Unblocks https://github.com/op-rs/kona/issues/1716. Allows writing supervisor e2e tests in kona and only running against `op-supervisor` until `kona-supervisor` support is integrated into `optimism-package`.
Ref
https://github.com/op-rs/kona/tree/main/tests/supervisor
https://github.com/ethpandaops/optimism-package/issues/281
> test(supervisor): Comment out kona-supervisor in kurtosis network params

- Justfile
- tests/Justfile
Removes the `build-node`, `build-node-with-tag`, and `build-supervisor-with-tag` recipes in favor of `docker/apps/justfile`'s recipes.
closes https://github.com/op-rs/kona/issues/1596
> chore(docker): Move root docker builds into `docker` dir

- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/rpc/src/jsonrpsee.rs
- crates/supervisor/rpc/src/lib.rs
Ref https://specs.optimism.io/interop/managed-mode.html
> chore(supervisor): Rename `ManagedNodeApi` to `ManagedModeApi` to match specs

- docker/apps/kona_app_generic.dockerfile
- tests/node/sync.go
Small PR that fixes the kurtosis sync tests. Since the op-nodes don't support the websocket endpoint this test was always failing
> fix(node/e2e-sync): fix large sync test

- .dockerignore
- docker/apps/kona_app_generic.dockerfile
This PR modifies the generic kona dockerfile to use cargo chef to cache external rust dependencies in docker.
> docker(cargo-chef): add cargo chef to cache rust builds in docker

- docker/apps/kona_app_generic.dockerfile
This PR adds a couple of parameters to the ubuntu installs inside kona's docker images to try to recover when package install fails.
> fix(docker): add fix-missing to fix docker builds

- mise.toml
- tests/justfile
This PR enables hot restarts of the kurtosis network by updating only the CL clients by swapping their docker image. This and #1896 greatly reduce the iteration time for local kurtosis development (from 5-10 mins to <1 min for reloading a kurtosis network).
Depends on #1914
> feat(node/e2e-tests): add a restart recipe for hot reloads of the kurtosis network

- .github/actions/setup/action.yml
Fixes the prefix-key designation in the generic Rust CI setup job. At the moment, the prefix key isn't being correctly set, causing cache collisions on jobs with dynamic prefix-key settings.
> fix(ci): Prefix-key designation in generic setup

- docker/apps/kona_app_generic.dockerfile
Removes `--fix-missing` from `kona_app_generic`'s `apt-get install` command, as recommended by the [best practices](https://docs.docker.com/build/building/best-practices/#apt-get) document from docker. Claude also recommends against it:
> fix(docker): Use cache busting for generic app dockerfile

- .github/actions/setup/action.yml
- .github/workflows/proof.yaml
- .github/workflows/rust_ci.yaml
Updates CI to use the `mold` linker for build performance.
> perf(ci): Use `mold` linker for performance

- .github/actions/setup/action.yml
- .github/workflows/proof.yaml
- .github/workflows/rust_ci.yaml
An attempt at reducing cache use. At the moment, we persist caches for every single workflow that is ran, causing a massive amount of cache use:
https://github.com/Swatinem/rust-cache/issues/95 mentions a different route that the `rust-libp2p` authors went, where they only persist caches on the `main` branch, allowing only for PRs to derive caches from `main`'s latest run.
Their setup also introduces a cache factory that generates caches for tests, but since we don't employ a similar strategy, this PR just adds `save-if: ${{ github.ref == 'refs/heads/main' }}` for now.
> perf(ci): Only persist rust cache on `main`

- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
Updates the consolidate task to only send a forkchoice update for safe head promotion if the attributes are either derived from a `SingleBatch`, or if the attributes are the last attributes within a `SpanBatch`.
closes #1757
> perf(engine): Batch safe-head FCUs

- crates/node/p2p/src/gossip/driver.rs
Fixes the `kona_node_gossipsub_connection` metrics to have proper `type` labels, allowing for filtering by `type` in the grafana visualizations.
> fix(node/p2p): Gossipsub connection metric keys

- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
Adds an `info` log for when the `ConsolidateTask` successfully promotes the safe head of the chain.
> feat(node/engine): Add `info` log for safe head promotion

- bin/node/src/flags/rpc.rs
- crates/node/rpc/src/config.rs
- crates/node/rpc/src/launcher.rs
- crates/node/service/src/actors/rpc.rs
- crates/node/service/src/service/validator.rs
Allows the RPC server to be restarted up to 3 times before failing and killing the node.
Closes #1320
> chore(rpc): Server Restarts

- bin/node/src/flags/globals.rs
- bin/node/src/metrics/cli_opts.rs
Records the initial rollup config values as labels for visibility into the node's config.
> chore(node): Rollup Config Metrics

- crates/node/p2p/src/metrics/mod.rs
- crates/node/p2p/src/net/driver.rs
Adds a histogram for peer scores over time in the gossipsub mesh
closes #1928
> feat(node/p2p): Peer score histogram

- Cargo.lock
- Cargo.toml
- bin/client/Cargo.toml
- bin/host/Cargo.toml
Bumps `kona-client` + `kona-host` to `v1.0.2`.
> chore(client/host): Prepare for `v1.0.2` release

- docker/recipes/kona-node/grafana/dashboards/overview.json
Updates the grafana dashboard with quite a few new metrics -
1. P2P Configuration
2. Rollup Configuration
> chore(docker): Update grafana dashboard

- crates/node/p2p/src/gossip/behaviour.rs
- crates/node/p2p/src/rpc/request.rs
Adds more fields to the `opp2p_peers` rpc call. In particular we now also support `user-agent` and `protocol_version` fields
Progress towards #1562
> feat(node/p2p): support user agent and protocol version in opp2p_peers rpc call

- docker/recipes/kona-node/docker-compose.yaml
Corrects the RPC port in the `kona-node` recipe. Also removes the `--p2p.redial 0` flag following @theochap's recent fix that resolved #1854.
> fix(docker): Correctly set RPC port in node recipe

- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona.yaml
- tests/justfile
- tests/node/node_test.go
This PR reactivates e2e tests for p2p gossip. I had to change the link to the stable branch of the `optimism-package` because it appears that the main version is broken
> fix(node/p2p): reactivate e2e tests for gossip.

- crates/protocol/derive/src/metrics/mod.rs
- crates/protocol/derive/src/stages/channel/channel_reader.rs
- crates/protocol/protocol/src/batch/mod.rs
- crates/protocol/protocol/src/batch/reader.rs
- crates/protocol/protocol/src/lib.rs
Adds two metrics to `kona-derive` tracking when the batch reader decompresses data and reads it into a batch as part of the `ChannelReader` stage of the derivation pipeline.
- Gauge that tracks the latest decompressed channel size.
- Gauge that tracks the latest decompressed channel type (brotli or zlib).
Closes #1999
> feat(derive): Decompressed Channel Size Metric

- crates/node/service/src/actors/l1_watcher_rpc.rs
Fixes the unsafe block signer update logic; Previously, it wasn't authenticating the source of the log.
> fix(node/service): Authenticate unsafe block signer updates

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/finalizer.rs
- crates/node/service/src/actors/l1_watcher_rpc.rs
- crates/node/service/src/actors/network.rs
- crates/node/service/src/service/standard/node.rs
- crates/node/service/src/service/validator.rs
Introduces backpressure within the DA watcher channels. This change ensures that if the consumers of the DA watcher events (L1 {head/finalized} updates, unsafe block signer updates) do not process their events in a timely manner, the DA watcher doesn't endlessly fill up the channel queue, and yields until the other actors can process its pending updates.
progress on #1993
> feat(node/service): Introduce backpressure in DA watcher channels

- Cargo.lock
- Cargo.toml
- crates/node/p2p/Cargo.toml
- crates/node/p2p/src/gossip/behaviour.rs
- crates/node/p2p/src/gossip/builder.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/gossip/error.rs
- crates/node/p2p/src/gossip/event.rs
- crates/node/p2p/src/net/driver.rs
- crates/node/p2p/tests/common/mod.rs
- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona.yaml
This PR adds a shim protocol for the sync-req-resp protocol supported by the op-node here https://specs.optimism.io/protocol/rollup-node-p2p.html#payload_by_number. 
This handler will always return the `Not Found` response. This will ensure that `op-nodes` are not penalizing the `kona-nodes` for not supporting it.
We can remove this handler once the `op-node` team phases out support for the `sync-req-resp` protocol.
This PR removes the environment variables in the kurtosis network configuration to disable the `req-resp` protocol. Network appears to remain stable and kona-nodes are not penalized
Closes #2032 and hopefully #1929
> feat(node/p2p): add a shim handler for sync req resp protocol

- Cargo.lock
- crates/node/p2p/src/rpc/request.rs
- crates/node/rpc/Cargo.toml
- crates/node/rpc/src/p2p.rs
Implements handling for the `opp2p_connectPeer` method using the Multiaddr string.
This follows how [the monorepo parses the addr string](https://github.com/ethereum-optimism/optimism/blob/51cb1a7523ac45e3c3703a1a2c6794b378f27cba/op-node/p2p/rpc_server.go#L353).
Closes #1575
> feat(rpc): Connect Peer RPC Method

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/network.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/service/validator.rs
- crates/supervisor/service/src/actors/l1_watcher_rpc.rs
> feat(node/service): removed unbounded channels in kona-service actors and replaced with bounded ones

- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/metrics/mod.rs
- crates/node/p2p/src/net/driver.rs
This PR improve the granularity of the `DIAL_PEER` metric by making sure we only increase the gauge when a peer is actually dialed. If that's not the case we emit the `DIAL_PEER_ERROR` metric
> feat(node/p2p): improve dial metric granularity

- crates/node/service/src/service/core.rs
Small nit; displays the `NodeMode` in the initialization log.
> chore(node/service): Display node mode in startup log

- bin/node/src/flags/p2p.rs
Raises the default dial threshold to a much higher value to ensure we don't ban peers too quickly. We can revert later if we realize this behavior is not good enough
> fix(node/p2p): raise default dial threshold

- bin/node/src/commands/node.rs
- bin/node/src/flags/rpc.rs
- crates/node/rpc/src/config.rs
- crates/node/rpc/src/launcher.rs
- crates/node/service/src/service/standard/builder.rs
- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona.yaml
- tests/node/node_test.go
e2e tests got broken after #1918 because this PR makes the websocket rpc endpoint disabled by default.
Fixes CI by enabling websockets rpc endpoints inside the kurtosis configurations.
Moves the `ws_enable` flag to the RPC CLI subcommand
> fix(node/e2e-tests): enable websockets for e2e tests

- .github/workflows/e2e_tests.yaml
- crates/node/sources/src/sync/forkchoice.rs
- tests/devnets/simple-kona-geth.yaml
Adds a `kona-node` + `op-geth` devnet config and runs the e2e tests against this config in CI.
> chore(tests): Add `kona-node` + `op-geth` config

- .github/workflows/e2e_tests.yaml
- tests/justfile
This PR aggressively caches the docker/go dependencies for e2e tests in CI. This allows to take advantage of `cargo-chef`. This seems to considerably improve CI runtimes if we're not updating the dependencies in rust/go.
Locally tested, works like a charm
> feat(ci): improve caching of e2e jobs

- .github/workflows/e2e_tests.yaml
Adjusts the E2E test matrix to not fail fast. Since we're seeing flakes on the large config, we don't want that to prevent the simple configs from executing.
> chore(ci): Don't fail fast on E2E matrix

- .github/workflows/e2e_tests.yaml
- tests/node/node_test.go
This should help with the flakiness. It seems that the op-nodes still have some flakiness displaying the right peer count after startup.
> fix(node/p2p): reduce number of peers that need to be connected for large e2e tests to pass

- bin/node/src/flags/p2p.rs
- crates/node/p2p/src/net/builder.rs
Allows for peer monitoring to be enabled, if it is configured.
> chore(node/p2p): Enable peer monitoring if configured

- crates/node/p2p/src/gossip/driver.rs
- crates/node/p2p/src/rpc/request.rs
Tracks peer ping latencies so we can return the latencies in the peer info response.
Progress on #1562
> feat(p2p): Track and Return Peer Ping Latencies

- bin/node/src/commands/node.rs
- bin/node/src/flags/sequencer.rs
- crates/utilities/cli/src/metrics_args.rs
Standardizes the envvar prefix for all kona-node CLI options.
Also adds the `KONA_` prefix for the global metrics args.
> chore(node): Standardize envvars

- crates/node/rpc/src/jsonrpsee.rs
- crates/node/rpc/src/p2p.rs
Small PR to remove the `IpNet` todo comments + `String` fields since `IpNet` can be serialized.
> chore(rpc): Cleanup IpNet TODOs

- crates/node/p2p/README.md
- crates/node/p2p/src/rpc/request.rs
This PR amends some of the changes from #2118 to only serve the total peer score inside `opp2p_peers`, as this is the only field supported by `rust_libp2p` as of now. 
See https://github.com/libp2p/rust-libp2p/issues/6058
> fix(node/p2p): fix opp2p_peers rpc handler. Only return total peer score

- crates/supervisor/core/src/chain_processor/chain.rs
- crates/supervisor/core/src/chain_processor/task.rs
- crates/supervisor/core/src/event/chain.rs
- crates/supervisor/core/src/event/mod.rs
- crates/supervisor/core/src/lib.rs
- crates/supervisor/core/src/syncnode/mod.rs
- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/core/src/syncnode/task.rs
- crates/supervisor/core/src/syncnode/traits.rs
- crates/supervisor/service/src/actors/l1_watcher_rpc.rs
- crates/supervisor/storage/src/chaindb.rs
- crates/supervisor/storage/src/chaindb_factory.rs
- crates/supervisor/storage/src/lib.rs
- crates/supervisor/storage/src/traits.rs
Part of #2069 
This PR refactors the event handling architecture and introduces support for finalized L1 block events, including their storage and processing.
Key Changes:
**Refactor Node Event Handling**
- Moves `NodeEvent` out of the `syncnode` module and renames it to `ChainEvent`
- All chain-processing will now be handled by the chain processor. Other modules will emit `ChainEvent` to the chain processor for unified handling.
**Finalized L1 Event Support**
- Introduces database logic for storing and retrieving the finalized L1 block
Motivation
- Centralizes all per-chain event processing, making the codebase easier to reason about and maintain.
- Enables future extensibility for new event types and sources.
> feat(supervisor/core): finalized l1 process handling

- bin/supervisor/src/flags/supervisor.rs
- crates/supervisor/core/src/supervisor.rs
- crates/supervisor/core/src/syncnode/error.rs
- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/core/src/syncnode/task.rs
Potentially fixes #2028 
Introduced `l1_provider` in ManageNode and ManagedEventTask and passed it to start_subscription and in the implementations for ManagedEventTask
> chore(supervisor): passing l1_provider instead of l1_rpc_url

- crates/supervisor/core/src/syncnode/task.rs
> feat(supervisor/core): remove hardcoded finalized head from reset event

- bin/supervisor/src/flags/supervisor.rs
- crates/protocol/interop/src/depset.rs
- crates/supervisor/core/src/rpc/server.rs
This PR 
- removes the timestamps from the depset since we are now using rollup config for it.
- this is also inline with the the response of the rpc method.
> fix(interop): remove timestamps from the depset

- .github/CODEOWNERS
Adds @dhyaniarun1993 @itschaindev @sadiq1971 as code owners for interop protocol types to unblock merging prs relating to these types during OP Labs collective pause
> Add chainsafe as codeowners of `kona-interop`

- bin/supervisor/src/flags/supervisor.rs
- crates/protocol/interop/src/depset.rs
- crates/supervisor/core/src/rpc/server.rs
> fix(protocol/interop): made `override_message_expiry_window` as optional

- crates/protocol/derive/src/errors/pipeline.rs
- crates/protocol/derive/src/pipeline/core.rs
- crates/protocol/derive/src/stages/attributes_queue.rs
- crates/protocol/derive/src/stages/batch/batch_queue.rs
- crates/protocol/derive/src/stages/batch/batch_validator.rs
- crates/protocol/derive/src/stages/l1_traversal.rs
- crates/protocol/derive/src/types/signals.rs
Adds a `Signal` variant for the supervisor to provide the next l1 block to the traversal stage.
Closes #2226
> feat(protocol/derive): Provide Block Signal

- bin/node/src/flags/p2p.rs
Increases error verbosity on port binding failures. Right now, it assumes every issue is related to port binding.
> chore(bin/node): Increase error verbosity on port binding failure

- bin/node/src/flags/sequencer.rs
- bin/node/src/flags/supervisor.rs
Moves the conductor flags from the supervisor args to the sequencer args
> chore(bin/node): Move conductor flags to sequencer args

- Cargo.lock
- crates/node/engine/Cargo.toml
- crates/node/service/Cargo.toml
- crates/node/sources/Cargo.toml
- crates/providers/providers-alloy/Cargo.toml
- docker/apps/kona_app_generic.dockerfile
Uses `rustls` over `request-default-tls`.
> chore(workspace): Use `rustls` over `request`'s default TLS feature

- crates/protocol/hardforks/src/ecotone.rs
- crates/protocol/hardforks/src/fjord.rs
- crates/protocol/hardforks/src/forks.rs
- crates/protocol/hardforks/src/interop.rs
- crates/protocol/hardforks/src/isthmus.rs
- crates/protocol/hardforks/src/traits.rs
Properly use backtick code comment references in `kona-hardforks`.
> chore(hardforks): Code Comment References

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/l1_watcher_rpc.rs
- crates/node/service/src/actors/network.rs
- crates/node/service/src/actors/rpc.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/actors/supervisor/actor.rs
- crates/node/service/src/actors/traits.rs
This PR removes the `process` method from `NodeActor` trait to simplify the structure of the `NodeActor`
Progress to #2176
> chore(node/service): remove process method from NodeActor trait

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/mod.rs
- crates/node/service/src/actors/l1_watcher_rpc.rs
- crates/node/service/src/actors/mod.rs
- crates/node/service/src/actors/network.rs
- crates/node/service/src/actors/rpc.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/actors/supervisor/actor.rs
- crates/node/service/src/actors/supervisor/mod.rs
- crates/node/service/src/actors/traits.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/standard/node.rs
- crates/node/service/src/service/util.rs
First attempt to decouple channel handling from the individual actors. This PR merely refactors the `NodeActor` trait to add a `Context` associated type that gets passed to the `start` method in the trait.
I think from here we can make the structure simpler by:
- Refactoring the `process` private methods into separate methods. That should remove the extra arguments for the `EngineActor`
- Abstracting the actor building process behind the `new` methods of the individual actors. In particular, split up the context using inbound/outbound associated types and define channels inside the actor's `new` methods.
> chore(node/service): refactor node actor trait. take context out of the actor

- crates/node/p2p/src/net/builder.rs
- crates/node/p2p/src/net/driver.rs
https://github.com/op-rs/kona/pull/1910 introduced back a bug that caused high CPU usage by the kona-node. This PR removes it.
> fix(node/p2p): fix immediately resolved future

- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona-geth.yaml
- tests/devnets/simple-kona.yaml
- tests/devnets/simple-supervisor.yaml
- tests/go.mod
- tests/node-devstack/cpu_monitor_test.go
- tests/node-devstack/mixed_preset.go
- tests/node-devstack/p2p_test.go
Adds a cpu usage test for kona to ensure that we're not overusing the CPU and prevent CPU contention such as what described in #2286 from being reintroduced.
Also fixes the kona kurtosis deployments
> feat(node/test): monitor cpu usage inside test

- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona-geth.yaml
- tests/devnets/simple-kona.yaml
- tests/devnets/simple-supervisor.yaml
- tests/go.mod
- tests/node-devstack/cpu_monitor_test.go
- tests/node-devstack/mixed_preset.go
- tests/node-devstack/p2p_test.go
- tests/node-devstack/rpc_endpoints_test.go
Adds a simple RPC endpoint retriever from kurtosis services. This will allow us to finally deprecate the devnet-sdk by migrating the remaining tests using the RPC endpoint provider to the devstack.
> feat(node/test): add a way to retrieve RPC endpoints addresses from kurtosis services

- crates/supervisor/core/src/chain_processor/chain.rs
- crates/supervisor/core/src/chain_processor/task.rs
- crates/supervisor/core/src/event/chain.rs
- crates/supervisor/core/src/safety_checker/cross.rs
- crates/supervisor/core/src/safety_checker/task.rs
- crates/supervisor/core/src/supervisor.rs
- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/core/src/syncnode/traits.rs
- crates/supervisor/storage/src/chaindb.rs
- crates/supervisor/storage/src/chaindb_factory.rs
- crates/supervisor/storage/src/metrics.rs
- crates/supervisor/storage/src/traits.rs
Closes #2214 
Closes #2215 
Closes #2255 
Closes #2256
> feat(supervisor):  broadcast cross head update events to managed node

- crates/supervisor/core/src/syncnode/metrics.rs
- crates/supervisor/core/src/syncnode/mod.rs
- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/core/src/syncnode/task.rs
Closes https://github.com/op-rs/kona/issues/2088
Implement RPC metrics for `ManagedModeApiClient` RPC calls
> feat(supervisor/syncnode): Observe `ManagedModeApiClient` RPC calls

- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/mod.rs
- crates/node/service/src/actors/mod.rs
- crates/node/service/src/lib.rs
Small PR to refactor the process method out of the engine actor. See https://github.com/op-rs/kona/pull/2271#discussion_r2165354387
> chore(node/engine): refactor process method

- crates/node/engine/src/task_queue/tasks/build/error.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/mod.rs
- crates/node/service/src/actors/sequencer/actor.rs
- crates/node/service/src/actors/sequencer/mod.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/standard/node.rs
Modifies the `BuildTask` in `kona-node-engine` to allow for passing back the built payload. This is necessary for the sequencer to receive an acknowledgement that the attributes were successfully built and imported, and then for it to schedule the payload to be signed and gossipped to the rest of the network.
> feat(node/engine): Build task modifications for sequencing

- crates/node/service/src/actors/mod.rs
- crates/node/service/src/actors/sequencer/actor.rs
- crates/node/service/src/actors/sequencer/mod.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/standard/node.rs
This PR refactors the sequencer module using the new builder pattern. In particular this moves the process of building the initial sequencer actor state inside the sequencer actor's `start` method.
@clabby for visibility
> chore(node/sequencer): refactor the sequencer module using the builder pattern

- crates/node/service/src/actors/derivation.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/mod.rs
- crates/node/service/src/actors/l1_watcher_rpc.rs
- crates/node/service/src/actors/mod.rs
- crates/node/service/src/actors/network.rs
- crates/node/service/src/actors/rpc.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/actors/sequencer/actor.rs
- crates/node/service/src/actors/sequencer/mod.rs
- crates/node/service/src/actors/supervisor/actor.rs
- crates/node/service/src/actors/supervisor/mod.rs
- crates/node/service/src/actors/traits.rs
- crates/node/service/src/lib.rs
- crates/node/service/src/service/core.rs
This PR inverts the way actors build their channels. Instead of emitting a list of `OutboundData` (channels to send data to) and using `InboundData` (channels to receive data from) as `Context`, it rather emits `InboundData` and uses `OutboundData` as context. 
This allows to define data flows where several actors send to the same receiver (using `mpsc` channels for instance).
> fix(node/service): invert the channel arrows in the rollup node service

- docker/recipes/kona-supervisor/grafana/dashboard/dashboard.yml
- docker/recipes/kona-supervisor/grafana/dashboard/kona-supervisor.json
> chore(supervisor): grafana dashboard

- crates/node/service/src/actors/engine/actor.rs
Closes #2319. This is pretty straightforward: it simply requires to connect the channel to receive block building requests to the engine
> feat(node/sequencer): connect build tasks to the engine

- bin/node/src/commands/node.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/util.rs
> feat(node/service): Propagated errors raised during NodeActor::start

- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/runtime.rs
- crates/node/service/src/actors/supervisor/actor.rs
- crates/node/service/src/service/util.rs
This PR adds drop guards to every actor to ensure they're all cancelled whenever any actor drops.
> feat(node/service): use drop guards to ensure actors are cancelled properly

- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/standard/builder.rs
- crates/node/service/src/service/standard/node.rs
- tests/go.mod
Small PR to move the node mode parameter from the `RollupNodeService` trait to the `EngineActor`. This also improves the safety of the engine select statement branch for incoming block building requests by being able to catch communication drops from the sequencer engine.
> feat(node/sequencer): move node mode from rollup node service trait to engine actor.

- bin/node/src/commands/net.rs
- bin/node/src/flags/rpc.rs
- crates/node/rpc/src/config.rs
- crates/node/service/src/actors/rpc.rs
- crates/node/service/src/service/core.rs
- crates/node/service/src/service/standard/builder.rs
A simple PR that removes the `rpc_disabled` field inside the `RpcBuilder`. This field was redundant since the `RpcBuilder` is now provided as an `Option` inside the `RollupNodeService`
> chore(node/rpc): remove rpc disabled field in rpc builder

- tests/devnets/simple-supervisor.yaml
`op-node` spec is being updated and we need to stick to the versioned release to make sure to avoid compatibility issues in future.
> chore(supervisor): op-node devnet version

- crates/supervisor/core/src/chain_processor/chain.rs
- crates/supervisor/core/src/chain_processor/task.rs
- crates/supervisor/core/src/supervisor.rs
- crates/supervisor/core/src/syncnode/error.rs
- crates/supervisor/core/src/syncnode/mod.rs
- crates/supervisor/core/src/syncnode/node.rs
- crates/supervisor/core/src/syncnode/resetter.rs
- crates/supervisor/core/src/syncnode/task.rs
- crates/supervisor/core/src/syncnode/traits.rs
- crates/supervisor/storage/src/providers/derivation_provider.rs
- crates/supervisor/storage/src/traits.rs
> fix(supervisor/core): derivation reset

- book/src/examples/new-l1-block-info-tx-hardfork.md
fix 404 URL  for `book/src/examples/new-l1-block-info-tx-hardfork.md`.
> chore: fix 404 URL

- crates/node/engine/src/lib.rs
- crates/node/engine/src/state/core.rs
- crates/node/engine/src/state/mod.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/engine/src/task_queue/tasks/build/error.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
- crates/node/engine/src/task_queue/tasks/finalize/task.rs
- crates/node/engine/src/task_queue/tasks/forkchoice/error.rs
- crates/node/engine/src/task_queue/tasks/forkchoice/task.rs
- crates/node/engine/src/task_queue/tasks/insert/error.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/engine/src/task_queue/tasks/task.rs
- crates/node/rpc/src/rollup.rs
- crates/node/rpc/src/ws.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/finalizer.rs
- crates/protocol/protocol/src/block.rs
This PR refactors the core logic of the engine task handler. In particular, it moves duplicate code from the build and the insert unsafe tasks to the forkchoice task.
Changes:
- Add an associated `Output` type for the `EngineTaskExt` trait which allows the implementors of this trait to be composed. In particular, the `ForkchoiceTask` may returns the payload id that was inserted in the EL, which can be used by the `BuildTask` to consolidate the payload into the engine state.
- Allows the `ForkchoiceTask` to directly insert newly built payload attributes into the EL (by adding an `Option<OpAttributeWithParent>` argument to the `ForkchoiceTask`). This allows to refactors both calls to the `FCU` inside the `BuildTask` using the `ForkchoiceTask` and avoids manually handling the forkchoice …
> feat(node/engine): refactor engine tasks. fix sequencer startup logic

- crates/node/engine/src/lib.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/engine/src/task_queue/tasks/build/error.rs
- crates/node/engine/src/task_queue/tasks/build/task.rs
- crates/node/engine/src/task_queue/tasks/consolidate/error.rs
- crates/node/engine/src/task_queue/tasks/consolidate/task.rs
- crates/node/engine/src/task_queue/tasks/finalize/error.rs
- crates/node/engine/src/task_queue/tasks/finalize/task.rs
- crates/node/engine/src/task_queue/tasks/forkchoice/error.rs
- crates/node/engine/src/task_queue/tasks/forkchoice/task.rs
- crates/node/engine/src/task_queue/tasks/insert/error.rs
- crates/node/engine/src/task_queue/tasks/insert/mod.rs
- crates/node/engine/src/task_queue/tasks/insert/task.rs
- crates/node/engine/src/task_queue/tasks/mod.rs
- crates/node/engine/src/task_queue/tasks/task.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/actors/engine/error.rs
This PR does the following cleanups to the engine tasks:
- Use explicit error types instead of `dyn Box<...>` for the `EngineTaskError`. The goal of this is twofold:
- Improve the composability of engine tasks (and be able to do some control flow when an engine task emits an error)
- Allows explicit testing of the error cases (in the future when we'll add tests for the engine tasks)
- Refactors the build task in the engine to reuse the `InsertUnsafe` task logic. This task is now called `InsertTask` to also encapsulate the case where we insert a derived block.
Close #2390. Progress towards #2389
> chore(node/engine): cleanup engine tasks errors. refactors the engine build task to reuse the insert task

- crates/node/engine/src/task_queue/core.rs
- crates/node/service/src/actors/sequencer/actor.rs
Sends an initial engine reset request and waits for it to conclude at the startup of the `SequencerActor`. This initializes the `EngineState`, and gives the sequencer a chain to begin building blocks on top of.
closes #2413
> feat(node/service): Reset engine prior to block building

- bin/node/src/flags/supervisor.rs
- book/src/node/cli.md
Fixes the `KONA_NODE_SUPERVISOR_PORT` environment variable.
> fix(bin/node): Fix `SUPERVISOR_PORT` envvar typo

- Cargo.lock
- bin/host/src/bin/host.rs
- crates/utilities/cli/Cargo.toml
- crates/utilities/cli/src/lib.rs
- crates/utilities/cli/src/log.rs
- crates/utilities/cli/src/tracing.rs
- examples/discovery/src/main.rs
- examples/execution-fixture/src/main.rs
- examples/gossip/src/main.rs
This PR adds options for logging format to kona's tracing utilities and propagates them to the CLI.
Logging options:
- json
- full (default)
- compact
- pretty
Tested inside kurtosis
> feat(kona/logs): add logging format options

- crates/supervisor/core/src/error.rs
- crates/supervisor/storage/src/error.rs
- crates/supervisor/storage/src/providers/derivation_provider.rs
- crates/supervisor/storage/src/providers/log_provider.rs
> fix(supervisor): error consistency

- tests/supervisor/pre_interop/post_test.go
- tests/supervisor/pre_interop/pre_test.go
This PR
- adds the acceptance test for the preinterop which is being skipped as of now due `op_contract_deployer_params ` issues
- fix the flaky existing test cases
Closes #2272
> test(supervisor): preinterop acceptance test

- crates/node/service/src/actors/sequencer/rpc.rs
Adds a few logs to the sequencer's admin RPC to observe important sequencer state updates triggered by the conductor.
> feat(node/service): Add sequencer admin RPC logs

- docs/docs/pages/sdk/examples/batch-to-frames.mdx
- docs/docs/pages/sdk/examples/frames-to-batch.mdx
Fixes examples to use proper links and vite callouts.
> fix(docs): Callouts and Doc Links

- crates/node/p2p/src/gossip/block_validity.rs
> Fix invalid blocks marked as seen

- tests/go.mod
- tests/go.sum
- tests/node/mixed_preset.go
Update monorepo fork to latest version of develop. Goes up to https://github.com/ethereum-optimism/optimism/commit/709d3eff834d9ef6eb0c1cbcb86f3b1b57807fe9
> chore(node/test): update monorepo fork

- tests/devnets/simple-kona-sequencer.yaml
- tests/node/conductor_test.go
- tests/node/mixed_preset_with_conductor.go
Adds an e2e test for leadership transfer in a network with an `op-node` and `kona-node` in the conductor set.
closes #2243
> feat(tests): Leadership transfer test

- crates/supervisor/storage/src/chaindb.rs
- crates/supervisor/storage/src/providers/derivation_provider.rs
- crates/supervisor/storage/src/providers/head_ref_provider.rs
- crates/supervisor/storage/src/providers/log_provider.rs
> chore(supervisor/storage): log improvements

- .github/workflows/e2e_tests.yaml
- Cargo.lock
- bin/node/Cargo.toml
- bin/node/src/cli.rs
- bin/node/src/commands/bootstore.rs
- bin/node/src/commands/info.rs
- bin/node/src/commands/net.rs
- bin/node/src/commands/node.rs
- bin/node/src/flags/globals.rs
- bin/node/src/flags/p2p.rs
- bin/node/src/metrics/cli_opts.rs
- bin/node/src/metrics/mod.rs
- crates/protocol/registry/src/lib.rs
- tests/README.md
- tests/devnets/large-kona.yaml
- tests/devnets/simple-kona-conductor.yaml
- tests/devnets/simple-kona-geth.yaml
- tests/devnets/simple-kona-sequencer.yaml
- tests/node/cpu_monitor_test.go
- tests/node/mixed_preset.go
- tests/node/rpc_test.go
- tests/node/sync_test.go
This PR:
- Tests `RollupConfig` rpc endpoint
- Fixes the rollup config metrics in grafana if the chain id is not part of the scr
- Adds a test to ensure the other nodes of the network are lagging behind the sequencer unsafe head
> test(node/rpc): test rollup config rpc endpoint. fix rollup config metrics

- crates/node/service/src/actors/sequencer/actor.rs
- crates/node/service/src/metrics/mod.rs
Adds a metric for the duration that it takes to commit the built payload to the conductor.
> feat(node/service): Conductor commitment time metric

- crates/protocol/genesis/src/chain/config.rs
Hey team! Found and fixed dead link
https://github.com/ethereum-optimism/superchain-registry/blob/main/superchain/superchain.go#L80 - old link
https://github.com/ethereum-optimism/superchain-registry/blob/main/ops/internal/config/superchain.go#L70 - new link
> fix dead link

- docs/docs/pages/node/run/mechanics.mdx
Removes the mention of the `RuntimeActor` from the docs. It was removed in #2535
> chore(docs): Remove `RuntimeActor` mention

- crates/supervisor/core/src/chain_processor/chain.rs
- crates/supervisor/core/src/chain_processor/task.rs
- crates/supervisor/core/src/l1_watcher/watcher.rs
- crates/supervisor/core/src/logindexer/indexer.rs
- crates/supervisor/core/src/rewinder/chain.rs
- crates/supervisor/core/src/rpc/server.rs
- crates/supervisor/core/src/safety_checker/task.rs
- crates/supervisor/core/src/supervisor.rs
- crates/supervisor/core/src/syncnode/client.rs
- crates/supervisor/core/src/syncnode/resetter.rs
- crates/supervisor/core/src/syncnode/task.rs
- crates/supervisor/core/src/syncnode/utils.rs
- crates/supervisor/service/src/service.rs
- crates/supervisor/storage/src/chaindb.rs
- crates/supervisor/storage/src/chaindb_factory.rs
- crates/supervisor/storage/src/providers/derivation_provider.rs
- crates/supervisor/storage/src/providers/head_ref_provider.rs
- crates/supervisor/storage/src/providers/log_provider.rs
Ref https://github.com/op-rs/kona/issues/2123, https://github.com/op-rs/kona/issues/2283
Adds `supervisor` path to log targets in supervisor. This makes it easier to tell `kona-node` and `kona-supervisor` components apart when running `kona-node` as an embedded system in `kona-supervisor`.
> chore(supervisor): Add supervisor path to log targets

- Cargo.lock
- bin/node/Cargo.toml
- bin/node/src/flags/mod.rs
- bin/node/src/flags/p2p.rs
- bin/node/src/flags/signer.rs
- crates/node/service/src/actors/network/builder.rs
- crates/node/service/src/actors/network/config.rs
- examples/gossip/src/main.rs
This PR integrates the remote signer in our CLI interface. It ensures we are replicating the op-node's interface.
> feat(node/sequencer): integrate remote signer in CLI

- bin/node/README.md
- bin/node/src/commands/node.rs
- crates/node/engine/README.md
- crates/node/engine/src/client.rs
- crates/node/engine/src/task_queue/core.rs
- crates/node/engine/src/task_queue/tasks/finalize/task.rs
- crates/node/service/src/actors/engine/actor.rs
- crates/node/service/src/service/standard/builder.rs
- docker/recipes/kona-node/docker-compose.yaml
- docs/docs/pages/node/configuration.mdx
- docs/docs/pages/node/design/sequencer.mdx
- docs/docs/pages/node/run/binary.mdx
Removes the `--l2.provider` flag from the `kona-node` in favor of proxying L2 RPC requests through the engine API.
This change is breaking to the CLI interface, and will require an update to:
> feat!(bin/node): Remove `--l2.provider` flag

- .github/workflows/e2e_tests.yaml
- crates/node/engine/src/query.rs
- crates/node/engine/src/state/core.rs
- crates/node/service/src/actors/sequencer/actor.rs
- tests/devnets/first-kona-conductor.yaml
> patch(node/conductor): patch conductor bootstrap

- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- bin/node/Cargo.toml
- crates/node/engine/Cargo.toml
- crates/node/p2p/Cargo.toml
- crates/node/peers/Cargo.toml
- crates/node/rpc/Cargo.toml
- crates/node/service/Cargo.toml
- crates/node/sources/Cargo.toml
- crates/protocol/comp/Cargo.toml
- crates/protocol/derive/Cargo.toml
- crates/protocol/genesis/Cargo.toml
- crates/protocol/hardforks/Cargo.toml
- crates/protocol/interop/Cargo.toml
- crates/protocol/protocol/Cargo.toml
- crates/protocol/registry/Cargo.toml
- crates/providers/providers-alloy/Cargo.toml
- crates/utilities/cli/Cargo.toml
- crates/utilities/macros/Cargo.toml
- crates/utilities/serde/Cargo.toml
Release diff for `kona-node` v0.1.2. Already published to crates.io.
> release(kona-node): 0.1.2

- crates/node/engine/src/task_queue/tasks/build/error.rs
- crates/node/engine/src/task_queue/tasks/insert/error.rs
- docs/docs/pages/node/design/p2p.mdx
This commit addresses several small but important typo fixes in both Rust error enums and documentation:
Corrected spelling:
- re-atttempt → re-attempt in BuildTaskError
- forchoice → forkchoice in InsertTaskError
Fixed typo:
- paylaod → payload in the P2P design spec (p2p.mdx)
These changes improve clarity and maintain consistency across code and documentation. No functional behavior is modified.
> Fix typos in task errors and P2P block validation docs

- crates/supervisor/storage/src/chaindb.rs
- crates/supervisor/storage/src/error.rs
- crates/supervisor/storage/src/traits.rs
> fix(supervisor/storage): prevent log rewinding beyond local safe

- crates/supervisor/core/src/reorg/task.rs
segregated the changes into a different pr. [Ref](https://github.com/op-rs/kona/pull/2655#discussion_r2260642691)
> chore (supervisor): remove dynamic type 

- docs/docs/pages/sdk/protocol/derive/intro.mdx
Fixed broken markdown link [channel-provider] in intro.mdx:
Updated path from kona_derive/stages/struct.ChannelProvider.html
To the correct path: kona_derive/struct.ChannelProvider.html
> fix: correct dead link to ChannelProvider struct in documentation

- tests/README.md
Changed ./mise.toml to ../mise.toml to fix broken file reference
> fix: update mise.toml path in tests README

- crates/supervisor/core/src/l1_watcher/watcher.rs
- crates/supervisor/core/src/reorg/task.rs
> fix(supervisor): reorg at startup

- tests/node/mixed_preset.go
> chore: fix function name

- bin/node/src/commands/bootstore.rs
- bin/node/src/flags/p2p.rs
- crates/node/disc/src/builder.rs
- crates/node/disc/src/driver.rs
- crates/node/peers/src/lib.rs
- crates/node/peers/src/store.rs
- crates/node/service/src/actors/network/actor.rs
- crates/node/service/src/actors/network/builder.rs
- crates/node/service/src/actors/network/config.rs
This PR adds a CLI argument to disable writing/recovering the bootstore to/from a file. This is useful for our integration tests because we want to ensure we always have the same behavior between runs.
Revamps the bootstore
> feat(node/p2p): allow disabling the bootstore

- crates/proof/std-fpvm/src/channel.rs
- crates/proof/std-fpvm/src/types.rs
Corrected spelling mistakes in doc comments in `channel.rs` and `types.rs` (`rudamentary` → `rudimentary`, `standaard` → `standard`).
> chore: fix typos in documentation comments

- .github/workflows/claude-code-review.yml
Claude was getting noisy by commenting for every commit. We just want to have it once per PR
> chore(ga): only run claude once per pull request

- crates/providers/providers-alloy/src/chain_provider.rs
- Add missing colon in error message for RPC receipts conversion in chain_provider.rs
> fix: Add missing colon in error message

- .github/workflows/proof.yaml
- .gitignore
- Cargo.lock
- Cargo.toml
- bin/client/justfile
Adds a CI job to run `kona-client` on `cannon64`.
Also upgrades the dep of `nybbles`; There was a bug that I introduced recently for big-endian targets, fix included in https://github.com/alloy-rs/nybbles/pull/35.
> feat(ci): Add `kona` + `cannon` job

- crates/proof/mpt/src/noop.rs
- crates/protocol/protocol/src/predeploys.rs
ixed typo in doc comment (Providers → Provides).
updated OPERATOR_FEE_VAULT address to include 0x prefix for consistency.
> fix: correct typos in docs and address formatting

- Cargo.lock
- Cargo.toml
- crates/utilities/cli/Cargo.toml
- crates/utilities/cli/src/prometheus.rs
- docker/recipes/kona-supervisor/grafana/dashboard/kona-supervisor.json
Closes #2714 and #2713 
Dashboard preview:
This should also work with other Kona services.
> chore (supervisor): add global metrics

- .github/workflows/node_e2e_kurtosis_tests.yaml
- .github/workflows/node_e2e_sysgo_tests.yaml
- tests/node/common/conductor_test.go
- tests/node/common/init_test.go
- tests/node/common/p2p_test.go
- tests/node/common/rpc_test.go
- tests/node/common/sync_test.go
- tests/node/kurtosis/cpu_monitor_test.go
- tests/node/kurtosis/engine_test.go
- tests/node/kurtosis/sync_ws_test.go
- tests/node/restart/conn_drop_test.go
- tests/node/restart/init_test.go
- tests/node/restart/restart_test.go
- tests/node/sysgo/init_test.go
- tests/node/utils/mixed_preset.go
- tests/node/utils/mixed_preset_with_conductor.go
- tests/node/utils/mod.go
Try to restructure e2e tests go package to prevent race conditions in CI
> feat(node/e2e-tests): refactor test package

- .github/workflows/node_e2e_kurtosis_tests.yaml
- .github/workflows/node_e2e_sysgo_tests.yaml
- tests/go.mod
- tests/go.sum
- tests/node/common/conductor_test.go
- tests/node/common/init_test.go
- tests/node/common/p2p_test.go
- tests/node/common/restart_test.go
- tests/node/common/rpc_test.go
- tests/node/common/sync_test.go
- tests/node/kurtosis/cpu_monitor_test.go
- tests/node/kurtosis/engine_test.go
- tests/node/kurtosis/sync_ws_test.go
- tests/node/restart/conn_drop_test.go
- tests/node/restart/init_test.go
- tests/node/restart/restart_test.go
- tests/node/sysgo/init_test.go
- tests/node/utils/mixed_preset.go
- tests/node/utils/mixed_preset_with_conductor.go
- tests/node/utils/mod.go
This PR adds restart tests for the kona node
> feat(node/e2e-tests): add restart tests

- crates/supervisor/core/src/error.rs
- crates/supervisor/core/src/supervisor.rs
This PR fixes checkAccessList errors as per the golang implementation.
> fix(supervisor/rpc): fix checkAccessList errors

- crates/supervisor/core/src/rpc/metrics.rs
- crates/supervisor/core/src/rpc/server.rs
- crates/supervisor/core/src/supervisor.rs
- crates/supervisor/rpc/src/jsonrpsee.rs
- crates/supervisor/service/src/actors/rpc.rs
Closes #2771
Spec: https://github.com/ethereum-optimism/specs/pull/753
> feat(supervisor/rpc): `supervisor_localSafe` added

- Cargo.lock
- Cargo.toml
- bin/rollup/Cargo.toml
- crates/utilities/cli/Cargo.toml
- mise.toml
- tests/.config/optimism_package.json
- tests/go.mod
- tests/go.sum
- tests/justfile
Fixes CI by:
- updating all dependencies (optimism-package, kurtosis, monorepo)
- fixing cargo hack failures caused by #2762 
- fixing udeps failure caused by #2762 
- fixing sysgo job failure upstream caused by #2762
> fix(node/ci): fixes several CI issues

- .github/workflows/node_e2e_sysgo_tests.yaml
- tests/node/l2_reorg/init_test.go
- tests/node/l2_reorg/l2_reorg_test.go
- tests/node/utils/mixed_preset.go
- tests/node/utils/mod.go
- tests/node/utils/test_sequencer_preset.go
Add a couple of l2 reorg tests with an appropriate network configuration.
> feat(node/test): add l2 reorg tests

- bin/client/src/interop/mod.rs
- bin/client/src/interop/transition.rs
- bin/host/src/backend/offline.rs
bin/client/src/interop/mod.rs
the
// the - **fix duplicate**
bin/client/src/interop/transition.rs
`and the fetch` - `and fetch the`
bin/host/src/backend/offline.rs
traits.] -- `delete extra ]`
> chore: fix spelling issues

- Cargo.toml
Sync reth version, apparently the version is v1.6.0 now
> chore: sync reth version

- bin/node/src/commands/node.rs
Replace incorrect --l2-jwt-secret in the inline example with the canonical --l2-engine-jwt-secret. This aligns the comment with the actual Clap flag (l2_engine_jwt_secret) and the CLI reference/README/docker examples, preventing confusion for users copying the example.
> fix(node): use canonical --l2-engine-jwt-secret in CLI example

- Cargo.lock
- Cargo.toml
Per title, should allow to fix #2437
> chore(node/deps): update rocksdb version

- tests/.gitignore
- tests/justfile
- tests/node/long-running/README.md
- tests/node/long-running/init_test.go
- tests/node/long-running/tx_producer_test.go
This PR adds a test and an associated just recipe that can act as a background transaction generator to simulate network load under realistic conditions
> feat(node/test): add long running background tests

- docker/apps/kona_app_generic.dockerfile
I'd like to test this to see if this fixes building images for macs. The arm64 build tries to use the `cntw` instruction which is part of the [SVE instruction set](https://developer.arm.com/documentation/ddi0602/2025-06/SVE-Instructions) but apple does not support the full SVE extension.
Fixes #2815
> Build for generic CPU instead of native CPU

- crates/providers/providers-alloy/src/chain_provider.rs
Remove unnecessary `hash_slow()` call when creating BlockInfo in the alloy chain provider.
Since we already verify the header hash matches the requested hash in `verify_header_hash()`, we can directly use the input hash parameter instead of recomputing it.
> fix: avoid redundant hash computation in block_info_and_transactions_by_hash

- crates/node/gossip/src/rpc/types.rs
Remove unnecessary `use std::string::String;` import since String is available in the Rust prelude by default
> remove redundant String import from gossip RPC types

- crates/supervisor/service/src/service.rs
Drop the unnecessary clone when instantiating AdminRpc so the channel sender is moved directly, eliminating an extra allocation without changing behavior.
> fix: remove redundant AdminRpc clone
